name: Unleash
description: Unleash is an open-source feature management software designed to
  cater to the needs of large enterprises. It provides a private, secure, and
  scalable platform that is ready to handle complex setups right out of the box.
  Unleash allows you to code freely, release confidently, and then scale your
  software. It offers a 'buy, then build' solution that is flexible,
  multilingual, and scales along with your business processes. This results in
  reduced costs, efficient hours, and less technical debt. Unleash also allows
  for progressive, targeted feature rollouts, enabling you to release features
  to selected users the moment you're ready. It supports change requests and
  approvals, and provides resilience during service outages. With Unleash, you
  can easily customize the software to your specific use cases, build multiple
  environments on separate instances, and keep your user data safe through
  privacy by design, data residency, and flexible hosting options.
instructions: Login with admin:unleash4all
changeLog:
  - date: 2023-04-12
    description: first release
links:
  - label: Website
    url: https://getunleash.io
  - label: Documentation
    url: https://docs.getunleash.io
  - label: Github
    url: https://github.com/Unleash/unleash
  - label: Demo
    url: https://www.getunleash.io/interactive-demo
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: unleash
    appServiceImage:
      type: string
      title: App Service Image
      default: unleashorg/unleash-server:4.22.5
    databaseServiceName:
      type: string
      title: Database Service Name
      default: unleash-db
