name: LibreOffice
description: LibreOffice is a free and powerful office suite app that serves as
  a successor to OpenOffice.org. It features a clean interface and feature-rich
  tools that help you unleash your creativity and enhance your productivity. The
  app can be accessed at http://yourhost:3000/ or https://yourhost:3001/. It is
  designed to deliver a true lossless image at a high framerate to your web
  browser. The app also supports multiple architectures, ensuring that it can be
  used on a variety of platforms. This app is perfect for those who need a
  comprehensive office suite for their daily tasks.
instructions: null
changeLog:
  - date: 2022-11-14
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-libreoffice
  - label: Github
    url: https://github.com/linuxserver/docker-libreoffice
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: libreoffice
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/libreoffice:latest
