name: linkding
description: Linkding is a self-hosted bookmark manager that allows you to
  efficiently manage and organize your bookmarks. With a clean and optimized
  user interface, you can easily add, share, and edit bookmarks. The app also
  allows you to add notes to your bookmarks using Markdown and provides a 'read
  it later' functionality. It automatically generates titles, descriptions, and
  icons for your bookmarked websites and creates snapshots of them on the
  Internet Archive Wayback Machine. You can also import and export bookmarks in
  Netscape HTML format. The app offers light and dark themes for your
  convenience. It also provides a REST API for developing third-party apps and
  an admin panel for user self-service and raw data access.
instructions: If the login fails with a error 500, please restart the "linkding"
  app service. This can be caused by the database not being properly reachable
  at linkding's first start.
changeLog:
  - date: 2023-03-18
    description: Template created (v1.17.2)
links:
  - label: Github
    url: https://github.com/sissbruecker/linkding
  - label: Demo
    url: https://demo.linkding.link/
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - linkdingSuperuserName
    - linkdingSuperuserPassword
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: linkding
    appServiceImage:
      type: string
      title: App Service Image
      default: sissbruecker/linkding:1.17.2
    linkdingSuperuserName:
      type: string
      title: Superuser Name
    linkdingSuperuserPassword:
      type: string
      title: Superuser Password
    linkdingDisableBackgroundTasks:
      type: boolean
      title: Disable background tasks
      default: false
    linkdingDisableURLValidation:
      type: boolean
      title: Disable URL validation
      default: false
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
        - enum:
            - postgres
          title: PostgreSQL
    databaseServiceName:
      type: string
      title: Database Service Name (Can be ignored if SQLite)
      default: linkding-db
