name: Tolgee
description: Tolgee is a revolutionary localization platform designed to
  simplify and speed up the translation process of your application. With
  Tolgee, you can translate your app into any language without modifying your
  code. It offers a range of features including in-context translating,
  translation memory, machine translations, auto translation, and activity log.
  The in-context translating feature allows you to translate strings directly in
  the app you develop, even in production. Translation memory ensures you don't
  translate the same string twice by reusing strings you've already translated.
  Machine translations let you leverage the power of DeepL, Google Translate,
  and AWS translate. Auto translation delivers your translations instantly right
  after you add them. The activity log feature helps you monitor the translation
  activities. Tolgee also allows users to add screenshots with a single click,
  providing context for translations. It is designed to be developer-friendly
  with easy integration with all major JS frameworks. Tolgee is not only easy to
  use for developers but also for translators, making the localization process
  seamless and efficient.
instructions: null
changeLog:
  - date: 2023-3-28
    description: first release
links:
  - label: Website
    url: https://tolgee.io
  - label: Documentation
    url: https://tolgee.io/platform
  - label: Github
    url: https://github.com/tolgee/tolgee-platform
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - userUsername
    - userPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: tolgee
    appServiceImage:
      type: string
      title: App Service Image
      default: tolgee/tolgee:v3.11.4
    databaseServiceName:
      type: string
      title: Database Service Name
      default: tolgee-db
    userUsername:
      type: string
      title: Username
    userPassword:
      type: string
      title: Password
