name: Hastebin
description: Haste is an open-source software that allows you to quickly and
  easily share text snippets. It's designed to be simple, pretty, and easy to
  use. With Haste, you can create a 'paste' of your text and it will generate a
  unique URL that you can share. This is particularly useful for sharing code
  snippets or other information that you want to quickly share with others.
  Haste is written in node.js and can be backed by either a file system or
  redis, providing flexibility in how it's set up. It also includes a utility
  called haste-client that allows you to create pastes directly from your
  command line. Haste is designed to work well with a variety of browsers,
  including Firefox, Chrome, and Safari.
instructions: null
changeLog:
  - date: 2022-11-22
    description: first release
links:
  - label: Documentation
    url: https://github.com/toptal/haste-server/wiki
  - label: Github
    url: https://github.com/toptal/haste-server
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: hastebin
    appServiceImage:
      type: string
      title: App Service Image
      default: rlister/hastebin:latest
