name: GoToSocial
description: GoToSocial is a lightweight, customizable, and safety-focused
  social network server that provides a fun and fast entryway into the
  Fediverse. It is written in Golang and allows you to keep in touch with
  friends, post, read, and share images and articles without being tracked or
  advertised to. If you've used platforms like Twitter or Tumblr, GoToSocial
  will feel familiar. You can follow people, have followers, make posts that
  others can favorite, reply to, and share, and scroll through posts from people
  you follow using a timeline. You can write long or short posts, post images,
  and even block people or limit unwanted interactions by posting just to your
  friends. GoToSocial is not designed for influencers with tens of thousands of
  followers, nor is it designed to be addictive. Your timeline and experience
  are shaped by who you follow and how you interact with people, not by
  engagement metrics. GoToSocial is ideal for small or single-user instances
  running on low-powered devices, like single-board computers or old laptops
  repurposed as home servers. It is simple to install and maintain, and
  prioritizes good security and sensible defaults.
instructions: null
changeLog:
  - date: 2023-5-26
    description: First release
links:
  - label: Website
    url: https://gotosocial.org/
  - label: Documentation
    url: https://docs.gotosocial.org/en/latest/
  - label: Github
    url: https://github.com/superseriousbusiness/gotosocial/
contributors:
  - name: Michael Kinder
    url: https://github.com/ressonix
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gotosocial
    appServiceImage:
      type: string
      title: App Service Image
      default: superseriousbusiness/gotosocial:0.9.0
