name: Cachet
description: Meet Cachet, the open-source status page system designed to improve
  downtime communication. Used by great companies worldwide, Cachet allows you
  to effectively communicate downtime and system outages to your customers,
  teams, and shareholders. It comes with a beautifully crafted design that is
  responsive and works seamlessly on your desktop, tablet, and phone. Cachet
  supports multiple languages and comes with a powerful JSON API for updating
  your status page with incidents and component status changes. It also allows
  you to schedule maintenance events ahead of time and provides a dashboard for
  setting up metrics to measure various aspects such as uptime, error rates,
  etc. For added security, Cachet supports two-factor authentication. It's a
  beautifully simple service for managing your service statuses.
instructions: null
changeLog:
  - date: 2023-3-28
    description: first release
links:
  - label: Website
    url: https://cachethq.io
  - label: Documentation
    url: https://docs.cachethq.io/
  - label: Github
    url: https://github.com/cachethq/cachet
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cachet
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/supernova3339/docker-cachet-hq:2.3.18
    databaseServiceName:
      type: string
      title: Database Service Name
      default: cachet-db
