name: OpenProject
description: OpenProject is an open-source project management software designed
  to facilitate efficient project management in a secure environment. It caters
  to various project management styles including classic, agile, or hybrid. The
  software allows you to take control of your data with the highest standards in
  data security and privacy. OpenProject can be installed on-premises in your
  own infrastructure, ensuring full control and 100% data ownership. It offers a
  variety of security features such as https encryption of your data, password
  security, two-factor authentication, and more. OpenProject supports agile
  project management and methodologies such as Scrum and Kanban, allowing teams
  to deliver better and faster. It also features a team planner to visually
  assign tasks to team members, helping to plan activities and gain perspective
  on the team's workload. OpenProject is also a powerful tool for project
  planning and scheduling, enabling teams to collaboratively create and
  visualize project plans, analyze required activities, and create a detailed
  plan for project deliverables.
instructions: The default login credentials are admin:admin
changeLog:
  - date: 2023-03-26
    description: First Release
links:
  - label: Website
    url: https://openproject.org/
  - label: Docs
    url: https://openproject.org/docs/
  - label: Github
    url: https://github.com/opf/openproject
  - label: Docker
    url: https://hub.docker.com/r/openproject/community
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: openproject
    appServiceImage:
      type: string
      title: App Service Image
      default: openproject/community:12
