name: RSSHub
description: RSSHub is an open-source, user-friendly, and extensible RSS feed
  generator. It is designed to create RSS feeds from virtually any content. With
  the ability to aggregate millions of contents from various sources, RSSHub
  ensures the delivery of new routes, features, and bug fixes. The app is
  compatible with the browser extension RSSHub Radar and mobile auxiliary apps
  RSSBud (iOS) and RSSAid (Android). It has adapted to hundreds of websites and
  thousands of content types, making it a versatile tool for generating RSS
  feeds.
instructions: null
changeLog:
  - date: 2023-07-09
    description: First Release
links:
  - label: Website
    url: https://rsshub.app/
  - label: Documentation
    url: https://docs.rsshub.app/
  - label: Github
    url: https://github.com/DIYgod/RSSHub
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rsshub
    appServiceImage:
      type: string
      title: App Service Image
      default: diygod/rsshub:latest
