name: Coder
description:
instructions:
changeLog:
  - date: 2024-01-23
    description: first release
links:
  - label: Website
    url: https://coder.com
  - label: Documentation
    url: https://coder.com/docs/v2/latest
  - label: Github
    url: https://github.com/coder/coder
contributors:
  - name: Serban Alexandru
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: coder
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/coder/coder:latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: coder-db
