name: Blender
description: Blender is a comprehensive, free and open-source 3D computer
  graphics software toolset. It is used for creating animated films, visual
  effects, art, 3D printed models, motion graphics, interactive 3D applications,
  virtual reality, and computer games. The app is designed to be accessed at
  your host, providing a desktop GUI for easy interaction. It supports hardware
  acceleration for an enhanced desktop experience, although GPU rendering is not
  supported out of the box. The app is compatible with multiple architectures,
  ensuring it can be used on a variety of systems. Please note that while this
  app can run on Arm devices, it is recommended not to mount in /dev/dri due to
  the OpenGL ES version not being high enough to run Blender.
instructions: null
changeLog:
  - date: 2023-04-12
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-blender
  - label: Github
    url: https://github.com/linuxserver/docker-blender
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: blender
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/blender:latest
