name: Langflow
description: Langflow is an innovative application designed to facilitate the
  experimentation and prototyping of LangChain pipelines. It provides a
  user-friendly interface for creating flows by simply dragging and connecting
  LangChain components such as LLMs, prompt serializers, agents, and chains. You
  can easily modify prompt parameters, link chains and agents, track an agent's
  thought process, and export your flow. Once your flow is ready, you can export
  it as a JSON file for use with LangChain. Langflow also integrates with
  langchain-serve for one-command deployment to Jina AI Cloud. With Langflow,
  building and deploying LangChain pipelines has never been easier.
instructions: null
changeLog:
  - date: 2023-06-22
    description: first release
links:
  - label: Github
    url: https://github.com/logspace-ai/langflow
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - username
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: langflow
    username:
      type: string
      title: Username
    password:
      type: string
      title: Password
