name: Answer
description: Answer is an open-source knowledge-based software designed to
  facilitate a Q&A environment for your products, customers, teams, and more. It
  allows users to ask questions and get answers, fostering a dynamic exchange of
  information. The app features a modern and responsive UI, and it's extensible
  with plugins. It also offers content organization capabilities, allowing you
  to categorize and tag your content for easy navigation. Additionally, Answer
  integrates with your existing tools and services to streamline your workflow.
  The app also incorporates gamification elements, rewarding users for their
  contributions, making the process of knowledge sharing more engaging. It's a
  powerful tool for product technical support, customer support, and user
  communication.
instructions: Go to /install and select sqlite database
changeLog:
  - date: 2022-12-21
    description: first release
links:
  - label: Documentation
    url: https://answer.dev/docs
  - label: Github
    url: https://github.com/answerdev/answer
  - label: Website
    url: https://answer.dev/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: answer
    appServiceImage:
      type: string
      title: App Service Image
      default: answerdev/answer:1.0.9
