name: Languagetool
description: LanguageTool is your personal writing assistant, designed to
  enhance your writing skills and ensure error-free communication. This
  multilingual app offers a comprehensive spelling, style, and grammar checker,
  capable of correcting or paraphrasing texts in a variety of languages. It
  integrates seamlessly with various platforms including browsers like Chrome,
  Edge, Firefox, Safari, Opera, and email platforms like Gmail and Outlook. It
  also works with office plugins such as Google Docs, Word, OpenOffice, and
  LibreOffice. LanguageTool is equipped with an AI-based style and grammar
  checker trusted by renowned organizations worldwide. It offers a
  distraction-free writing experience, a personal dictionary, and quality
  scoring for evaluating style and grammar. The app also features a 'Picky Mode'
  for advanced punctuation, style, and typography suggestions. LanguageTool is
  not just about correcting mistakes, it also helps improve your writing style
  by detecting overused phrases, foreign terms, redundant words, and improper
  word choice. It even assists in paraphrasing sentences to make them more
  formal, fluent, simple or concise. LanguageTool is the perfect tool for anyone
  who wants to deliver clear, precise, and stylistically correct writing.
instructions: null
changeLog:
  - date: 2023-2-24
    description: first release
links:
  - label: Website
    url: https://languagetool.org
  - label: Github
    url: https://github.com/languagetool-org/languagetool
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: languagetool
    appServiceImage:
      type: string
      title: App Service Image
      default: silviof/docker-languagetool:6.0
