name: Collabora Office
description: Collabora Online is a powerful, flexible, and secure online office
  suite designed to break free from vendor lock-in and put you in full control
  of your documents. It offers a private office suite in the cloud, compatible
  with trillions of existing documents, and can be integrated into your own
  infrastructure or accessed via one of our trusted hosting partners. It is
  excellent for enterprises that need a powerful office suite in the cloud, or
  on-premise, that protects their privacy and allows them to keep full control
  of their sensitive corporate data. Collabora Online offers a range of business
  benefits that support collaboration and productivity whilst maintaining your
  digital sovereignty and keeping your corporate documents secure. It includes a
  text document editor, a spreadsheet tool, a presentation creator, and a
  drawing tool, all designed to provide a true WYSIWYG editing experience and
  make visualising your document layout incredibly easy. You can open any
  document, add comments, track changes, format and style your pages, create
  spreadsheets with advanced formulas, design attractive presentations, and draw
  shapes and diagrams with ease. Collabora Online is fully open source, offering
  native integration in Android and iOS, and prioritizing privacy by default.
instructions: Access the admin console at https://<domain>/browser/dist/admin/admin.html
changeLog:
  - date: 2023-07-14
    description: First Release
links:
  - label: Website
    url: https://collaboraonline.com
  - label: Documentation
    url: https://sdk.collaboraonline.com/docs
  - label: Github
    url: https://github.com/CollaboraOnline
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appUsername
    - appPassword
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appUsername:
      type: string
      title: Username
    appPassword:
      type: string
      title: Password
    appServiceName:
      type: string
      title: App Service Name
      default: collabora
    appServiceImage:
      type: string
      title: App Service Image
      default: collabora/code:latest
