name: Tandoor
description: Tandoor is an online recipe management app designed to help you
  manage and grow your recipe collection. It allows you to drop your collection
  of links and notes, and provides a platform for recipe management, storage,
  sharing, and collaborative cooking. Tandoor is equipped with a powerful fuzzy
  search engine that helps you find your recipes faster. You can search for
  keywords, ingredients and more. The app also allows you to import your
  favorite recipes from thousands of websites online, and if you already have a
  digital recipe collection, you can import your data from many other managers.
  Tandoor also provides the functionality to create shopping lists for your
  recipes, making meal planning and shopping a breeze. It's the perfect tool for
  cooking enthusiasts looking to digitize and share their cookbooks and recipes.
instructions: null
changeLog:
  - date: 2023-04-10
    description: first release
links:
  - label: Website
    url: https://tandoor.dev
  - label: Documentation
    url: https://docs.tandoor.dev
  - label: Github
    url: https://github.com/TandoorRecipes/recipes
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: tandoor
    appServiceImage:
      type: string
      title: App Service Image
      default: vabene1111/recipes:1.4.8
    databaseServiceName:
      type: string
      title: Database Service Name
      default: tandoor-db
