name: Grav
description: Grav is an award-winning, open-source, flat-file content management
  system (CMS) designed to help you build faster websites. It's been voted 'Best
  Open Source CMS' in 2016 and 'Best Flat File CMS' in 2017, 2019, 2020, and
  2021. Grav is known for its fast performance, extensibility, and user-friendly
  interface. With Grav, you can easily modify flexible configuration settings,
  edit content with a powerful markdown editor, and install a wide range of
  modern themes with one click. It also offers a built-in package manager for
  easy plugin installation. Grav is packed with features and tools that make
  content creation enjoyable. It supports one-click installs, powerful content
  filtering, dynamic content types, multi-language support, simple backups and
  restores, image media processing, and easy theme customization. Whether you're
  creating landing pages, portfolios, product sites, personal resumes,
  e-commerce sites, blogs, business sites, or documentation, Grav provides the
  flexibility and power you need.
instructions: null
changeLog:
  - date: 2023-03-19
    description: Template created (v1.7.39)
links:
  - label: Website
    url: https://getgrav.org
  - label: Documentation
    url: https://learn.getgrav.org
  - label: Github
    url: https://github.com/getgrav/grav
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - timezone
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: grav
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/grav:1.7.40
    timezone:
      type: string
      title: Timezone
      default: Etc/UTC
