name: Mongo Express
description: mongo-express is a web-based MongoDB admin interface designed with
  Node.js, Express, and Bootstrap3. It allows you to connect to multiple
  databases, view, add, delete databases, and manage collections. You can also
  view, add, update, and delete documents within these collections. The app
  supports previewing audio, video, and image assets inline in the collection
  view. Large or nested objects are collapsible for easy overview, and big
  document properties are loaded on-demand to keep the collection view fast. The
  app also supports GridFS, enabling you to add, get, and delete incredibly
  large files. It uses BSON data types in documents and is mobile responsive,
  thanks to Bootstrap 3. The app also supports connection and authentication to
  individual databases, as well as admin authentication to view all databases.
  It includes features for database blacklist/whitelist, custom CA, and CA
  validation disabling, and supports replica sets.
instructions: null
changeLog:
  - date: 2023-07-10
    description: First Release
links:
  - label: Github
    url: https://github.com/mongo-express/mongo-express
  - label: Docker
    url: https://hub.docker.com/_/mongo-express/
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appMongoUrl
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appMongoUrl:
      type: string
      title: Mongo URL
      description: mongodb://admin:pass@localhost:27017/db?ssl=false
    appAuthUsername:
      type: string
      title: Username
    appAuthPassword:
      type: string
      title: Password
    appServiceName:
      type: string
      title: App Service Name
      default: mongo-express
    appServiceImage:
      type: string
      title: App Service Image
      default: mongo-express:1.0.0-alpha
