name: Keycloak
description: Keycloak is an open-source Identity and Access Management tool that
  adds authentication to applications and secures services with minimal effort.
  It eliminates the need for storing or authenticating users, providing user
  federation, robust authentication, user management, and fine-grained
  authorization. Keycloak offers a Single-Sign On feature, allowing users to
  authenticate with Keycloak rather than individual applications, ensuring a
  seamless login experience across multiple applications. It also supports
  social login and can authenticate users with existing OpenID Connect or SAML
  2.0 Identity Providers. Keycloak has built-in support to connect to existing
  LDAP or Active Directory servers and provides a centralized admin console for
  managing all aspects of the server. It also offers an account management
  console for users to manage their own accounts. Based on standard protocols,
  Keycloak supports OpenID Connect, OAuth 2.0, and SAML, and provides
  fine-grained authorization services for advanced permission management.
instructions: null
changeLog:
  - date: 2023-3-16
    description: first release
links:
  - label: Website
    url: https://www.keycloak.org
  - label: Documentation
    url: https://www.keycloak.org/documentation
  - label: Github
    url: https://github.com/keycloak/keycloak
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - keycloakUsername
    - keycloakPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: keycloak
    appServiceImage:
      type: string
      title: App Service Image
      default: bitnami/keycloak:21.1.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: keycloak-db
    keycloakUsername:
      type: string
      title: Username
    keycloakPassword:
      type: string
      title: Password
