name: Ghost
description: Ghost is a robust application designed for new-media creators
  looking to turn their audience into a business. It provides a suite of modern
  tools to build a website, publish engaging content, send newsletters, and
  offer paid subscriptions to members. Ghost allows you to launch your website
  with a selection of beautiful free themes and design settings that can be
  tweaked to match your brand and style. It also offers an editor built for
  professionals, with advanced workflows and a user-friendly interface. With
  Ghost, you can expand your story beyond words, incorporating image galleries,
  gifs, video, audio, and more into your content. The app also includes built-in
  newsletters, allowing you to deliver posts by email to your audience. Ghost
  simplifies the process of building an indie publication with memberships and
  subscriptions, with native signup forms that convert anonymous views into
  logged-in members. It also provides detailed engagement analytics to
  understand what content is getting the most attention and who your biggest
  fans are. Ghost also supports offers and promotions to entice new subscribers
  and grow your business.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-02-24
    description: Update to v5.35.1
  - date: 2023-06-30
    description: Update to v5.53.3
links:
  - label: Website
    url: https://ghost.org/
  - label: Documentation
    url: https://ghost.org/resources/
  - label: Github
    url: https://github.com/docker-library/ghost
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
  - name: siriokun
    url: https://github.com/siriokun
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ghost
    appServiceImage:
      type: string
      title: App Service Image
      default: ghost:5.53.3-alpine
    databaseServiceName:
      type: string
      title: Database Service Name
      default: ghost-db
