name: Owncloud
description: ownCloud Infinite Scale 3.0 is a secure cloud platform designed for
  real-time content collaboration. It is trusted by over 200 million users
  worldwide and offers a revolutionary project folder concept, Spaces, to boost
  seamless digital collaboration for remote teams of all sizes. The platform
  also provides a suite of powerful integrations through Web Office, including
  OnlyOffice, Microsoft 365, Collabora Online, and Microsoft Office Online,
  enabling users to collaborate seamlessly and securely from any location and
  device. ownCloud Infinite Scale 3.0 is designed with state-of-the-art security
  standards and best practices, ensuring superior data protection and privacy.
  It allows organizations to control their data at all times, anywhere, and can
  be deployed on-premises, in a data center of choice, or in a hybrid setup. The
  platform also supports multi-factor authentication, encryption, and elaborate
  file lifecycle management for enhanced security. ownCloud Infinite Scale 3.0
  is designed to increase productivity by enabling modern teams to store, share,
  and work on their data and documents through a single point of access.
instructions: null
changeLog:
  - date: 2023-2-28
    description: first release
links:
  - label: Website
    url: https://owncloud.com/
  - label: Documentation
    url: https://doc.owncloud.com/
  - label: Github
    url: https://github.com/owncloud/core
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
    - redisServiceName
    - adminUsername
    - adminPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: owncloud
    appServiceImage:
      type: string
      title: App Service Image
      default: owncloud/server:10.12.1
    databaseType:
      type: string
      title: Database Type
      default: postgres
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: owncloud-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: owncloud-redis
    adminUsername:
      type: string
      title: Username
    adminPassword:
      type: string
      title: Password
