name: Pterodactyl Panel
description: Pterodactyl® is a free, open-source game server management panel
  that allows you to manage your game servers with ease and efficiency. It is
  built with PHP, React, and Go, and designed with a focus on security.
  Pterodactyl runs all game servers in isolated Docker containers, providing a
  secure environment for each game. It also offers a beautiful and intuitive
  user interface, making it easy for anyone to use. The platform supports a wide
  variety of games, including Minecraft, Rust, Terraria, Teamspeak, Mumble, Team
  Fortress 2, Counter Strike Global Offensive, Garry's Mod, ARK Survival
  Evolved, and many more. With Pterodactyl, you can host your games across the
  world without having to bloat each physical machine with additional
  dependencies. It's time to make game servers a first-class citizen on your
  platform with Pterodactyl.
instructions: After installing, open the console and run "php artisan p:user:make".
changeLog:
  - date: 2023-07-10
    description: Update to v1.11
links:
  - label: Website
    url: https://pterodactyl.io/
  - label: Documentation
    url: https://pterodactyl.io/project/introduction.html
  - label: Github
    url: https://github.com/pterodactyl/panel
contributors:
  - name: Dane Everitt
    url: https://github.com/DaneEveritt
  - name: Matthew Penner
    url: https://github.com/matthewpi
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - redisServiceName
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: panel
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/pterodactyl/panel:latest
    redisServiceName:
      type: string
      title: Redis Service Name
      default: panel-redis
    databaseServiceName:
      type: string
      title: Database Service Name
      default: panel-db
