name: Nocobase
description: NocoBase is an open-source, no-code development platform designed
  with scalability in mind. It allows you to build your own collaboration
  platform or management system without any programming required. With NocoBase,
  you can create independent data models using a variety of field types and
  association relationships. The platform also provides a free combination of
  block types for displaying and manipulating data within a page. It supports
  various operations to process data, including filtering, exporting, adding,
  deleting, modifying, and viewing. NocoBase also features role-based control of
  user's system configuration rights, data action rights, and menu access
  rights. It replaces repetitive tasks with automation to increase efficiency
  and requires manual approval for important matters. NocoBase is built for
  extended development with a microkernel architecture that is flexible and easy
  to extend. It is Node.js-based and uses popular frameworks and technologies.
instructions: The initial account and password are admin@nocobase.com and admin123.
changeLog:
  - date: 2023-3-29
    description: first release
links:
  - label: Documentation
    url: https://docs.nocobase.com
  - label: Github
    url: https://github.com/nocobase/nocobase
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nocobase
    appServiceImage:
      type: string
      title: App Service Image
      default: nocobase/nocobase:0.9.1-alpha.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nocobase-db
