name: Komga
description: Komga is a free and open source comics/mangas server that provides
  an intuitive platform for comic and manga enthusiasts. It allows you to browse
  libraries, series, and books via a responsive web UI that is compatible with
  desktops, tablets, and phones. With Komga, you can easily organize your
  library with collections and read lists, and edit metadata for your series and
  books. The app also has the ability to import embedded metadata automatically.
  It features a web reader with multiple reading modes and allows you to manage
  multiple users with per-library access control, age restrictions, and labels
  restrictions. Additionally, Komga offers a REST API for interaction with other
  tools and scripts, and provides features for downloading book files, whole
  series, or read lists. It also has a duplicate files detection system and can
  import books from outside your libraries directly into your series folder.
  Komga also supports the import of ComicRack cbl read lists.
instructions: null
changeLog:
  - date: 2022-12-11
    description: first release
links:
  - label: Github
    url: https://github.com/gotson/komga
  - label: Website
    url: https://komga.org
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: komga
    appServiceImage:
      type: string
      title: App Service Image
      default: gotson/komga:0.165.0
