name: WPS Office
description: WPS Office is a comprehensive office suite that is lightweight yet
  feature-rich. It offers high compatibility and a range of professional office
  software tools. With WPS Office, you can edit files in Writer, Presentation,
  Spreadsheet, and PDF, enhancing your work efficiency. The application can be
  accessed at your host on ports 3000 and 3001. This container is based on
  Docker Baseimage KasmVNC, which provides additional environment variables and
  run configurations to enable or disable specific functionality. The
  application also supports the docker manifest for multi-platform awareness,
  ensuring the correct image for your architecture is retrieved.
instructions: use abc:abc to login. To access the login interface, add
  ?login=true to your URL.
changeLog:
  - date: 2023-5-7
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-wps-office
  - label: Github
    url: https://github.com/linuxserver/docker-wps-office
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wps-office
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/wps-office:latest
