name: Plex
description: "Plex Media Server is a powerful app that makes it easy to manage
  and stream your media collection to all your devices, anytime, anywhere. With
  Plex, you can stream your video, music, and photo collections from your phone,
  tablet, gaming console, smart TV, or any other favorite streaming device. The
  app is designed to work with three types of networking: bridge, host, and
  macvlan, each offering a unique way to connect your media server to your
  devices. Plex also offers advanced features like hardware transcoding support
  for Intel Quick Sync, making it a versatile choice for all your media
  streaming needs."
instructions: If you get a libusb error, please ignore it.
changeLog:
  - date: 2022-11-23
    description: first release
links:
  - label: Documentation
    url: https://support.plex.tv/articles/catagories/plex-media-server
  - label: Github
    url: https://github.com/plexinc/pms-docker
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: plex
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/plex:latest
