name: UptimeKuma
description: Uptime Kuma is a self-hosted monitoring tool designed to keep track
  of your website's uptime. It provides a comprehensive monitoring solution for
  HTTP(s), TCP, HTTP(s) Keyword, HTTP(s) Json Query, Ping, DNS Record, Push,
  Steam Game Server, and Docker Containers. The tool features a user-friendly,
  reactive, and fast UI/UX. It offers notifications via various platforms
  including Telegram, Discord, Gotify, Slack, Pushover, and Email (SMTP), among
  others. Uptime Kuma supports multi-language interfaces and multiple status
  pages, allowing users to map status pages to specific domains. It also
  provides ping charts, certificate info, proxy support, and 2FA support for
  enhanced security. This tool is perfect for those who want to ensure their
  website is always up and running.
instructions: null
changeLog:
  - date: 2022-08-02
    description: first release
links:
  - label: Website
    url: https://uptime.kuma.pet
  - label: Documentation
    url: https://github.com/louislam/uptime-kuma/wiki
  - label: Github
    url: https://github.com/louislam/uptime-kuma
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: uptimekuma
    appServiceImage:
      type: string
      title: App Service Image
      default: louislam/uptime-kuma:1.21.3
