name: NodeBB
description: NodeBB is a next-generation forum software that is powerful,
  mobile-ready, and easy to use. It is designed to provide a modern platform for
  your audience, fostering engagement and retaining customers. With NodeBB, you
  can enjoy a perfect experience on every device and screen, thanks to its
  mobile-first software. It offers built-in localization support with over 50
  languages actively translated, making it a truly global platform. NodeBB is
  also search optimized with human-readable URLs, semantic HTML with embedded
  microdata, and more. It allows for social media integration, bringing more
  visitors to your community by sharing content to Facebook, Google, and
  Twitter. NodeBB also offers real-time interaction with instant notifications,
  streaming posts, and real-time chats. It comes with a native analytics
  dashboard so you can know what content your users enjoy most. Whether you're a
  self-starter, a growing business, or a large corporation, NodeBB has a plan
  that works best for you.
instructions: null
changeLog:
  - date: 2023-03-24
    description: First Release
links:
  - label: Website
    url: https://nodebb.org/
  - label: Documentation
    url: https://docs.nodebb.org/
  - label: Github
    url: https://github.com/NodeBB/NodeBB
  - label: Demo
    url: https://try.nodebb.org/
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    nodebbAdminUsername:
      type: string
      title: Admin Username
    nodebbAdminMail:
      type: string
      title: Admin Mail
    nodebbAdminPassword:
      type: string
      title: Admin Password
    appServiceName:
      type: string
      title: App Service Name
      default: nodebb
    appServiceImage:
      type: string
      title: App Service Image
      default: nodebb/docker:2.8.9
    databaseServiceType:
      type: string
      title: Database Service Type
      default: mongo
      oneOf:
        - enum:
            - mongo
          title: MongoDB
        - enum:
            - redis
          title: Redis
        - enum:
            - postgres
          title: Postgres
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nodebb-db
