name: Barrage
description: Barrage is a minimalistic Deluge WebUI app with full mobile
  support. It features a responsive mobile-first design, allowing you to manage
  your torrents with ease from any device. With Barrage, you can add torrents by
  URL or magnet, sort and filter your torrents, and set global upload and
  download speed limits. It also allows you to change file priorities and modify
  torrent options. The app is designed to be deployed with Docker, making it a
  convenient and efficient tool for managing your torrents.
instructions: null
changeLog:
  - date: 2023-1-25
    description: first release
links:
  - label: Github
    url: https://github.com/maulik9898/barrage
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - domain
    - appServiceImage
    - delugeUrl
    - delugePassword
    - barragePassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: barrage
    appServiceImage:
      type: string
      title: App Service Image
      default: maulik9898/barrage:0.3.0
    delugeUrl:
      type: string
      title: Deluge URL
    delugePassword:
      type: string
      title: Deluge Password
    barragePassword:
      type: string
      title: Barrage Password
