name: Planka
description: Planka is a free, open-source Kanban board designed to streamline
  project management for workgroups. With Planka, you can create projects,
  boards, lists, cards, labels, and tasks, all in one place. It allows you to
  add card members, track time, set due dates, add attachments, and write
  comments. It also supports markdown in card descriptions and comments. The app
  provides real-time updates, ensuring all changes in cards or boards are
  instantly visible to your colleagues. You can customize your project
  background and filter tasks by members and labels. User notifications keep
  everyone in the loop about project updates. The app also supports multiple
  languages, making it a versatile tool for international teams.
instructions: Login with demo@demo.demo:demo
changeLog:
  - date: 2023-3-21
    description: first release
links:
  - label: Website
    url: https://planka.app
  - label: Documentation
    url: https://docs.planka.cloud
  - label: Github
    url: https://github.com/plankanban/planka
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: planka
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/plankanban/planka:1.11.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: planka-db
