name: EvoBot
description: EvoBot is a music bot designed for Discord, a popular communication
  platform. It's built with TypeScript and discord.js, and it uses a Command
  Handler from discordjs.guide. The bot allows users to play music directly from
  YouTube either by using a URL or a search query. It also supports playing
  YouTube playlists. In addition to playing music, EvoBot offers a variety of
  commands for managing the playback. Users can control the volume, pause and
  resume playback, skip songs, and even move songs within the queue. The bot
  also provides lyrics for songs and can show its uptime. EvoBot supports
  multiple languages, making it accessible to users around the world.
instructions: null
changeLog:
  - date: 2023-04-05
    description: first release
links:
  - label: Github
    url: https://github.com/eritislami/evobot
  - label: Documentation
    url: https://github.com/eritislami/evobot#%EF%B8%8F-configuration
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - discordToken
    - maxPlaylistSize
    - locale
    - defaultVolume
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: discord_music_bot
    appServiceImage:
      type: string
      title: App Service Image
      default: eritislami/evobot:2.7.0
    discordToken:
      type: string
      title: Discord Token
    maxPlaylistSize:
      type: number
      title: Maximum Playlist Size
      default: 10
    locale:
      type: string
      title: Bot Locale
      default: en
    defaultVolume:
      type: number
      title: Default Music Volume
      default: 100
      minimum: 0
      maximum: 100
