name: It Tools
description: IT-Tools is a comprehensive suite of handy tools designed to assist
  developers in their day-to-day tasks. It includes a wide range of features
  such as Crypto Token generator, Hash text Bcrypt, UUIDs v4 generator,
  Encrypt/Decrypt text, BIP39 passphrase generator, and many more. The app also
  offers various converters like Date-time converter, Integer base converter,
  Roman numeral converter, and Base64 string encoder/decoder among others. It
  provides a platform for developers to generate QR codes, SVG placeholders, and
  even record videos from their camera. With additional features like Git
  cheatsheet, Random port generator, Crontab generator, and JSON prettify and
  format, IT-Tools is a one-stop solution for all developer needs.
instructions: null
changeLog:
  - date: 2023-3-29
    description: first release
links:
  - label: Website
    url: https://it-tools.tech
  - label: Github
    url: https://github.com/CorentinTh/it-tools
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ittools
    appServiceImage:
      type: string
      title: App Service Image
      default: corentinth/it-tools
