name: Drone
description: Drone is a Container-Native, Continuous Delivery Platform
instructions:
changeLog:
  - date: 2022-08-04
    description: first release
links:
  - label: Website
    url: https://drone.io/
  - label: Documentation
    url: https://github.com/harness/drone#setup-documentation
  - label: Github
    url: https://github.com/harness/drone
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - domain
    - serviceName
    - clientID
    - clientSecret
    - rpcProtocol
    - runnerServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    domain:
      type: string
      title: Domain
    serviceName:
      type: string
      title: Service Name
      default: drone
    runnerServiceName:
      type: string
      title: Runner Service Name
      default: drone-runner
    clientID:
      type: string
      title: GitHub OAuth Client ID
    clientSecret:
      type: string
      title: GitHub OAuth Client Secret
      default: secret
    rpcProtocol:
      type: string
      title: RPC Protocol
      default: https
      oneOf:
        - enum:
            - https
          title: https
        - enum:
            - http
          title: http
    installRunner:
      type: boolean
      title: Install Runner Service
      default: false
    runnerCapacity:
      type: number
      title: Capacity for runner if enabled
      default: 2
