name: Drone
description: Drone.io is a self-service Continuous Integration platform designed
  for busy development teams. It automates software build and testing, making it
  an essential tool for efficient and effective software development. Drone.io
  is configured with a simple, easy-to-read file that you commit to your git
  repository, and each pipeline step is executed inside an isolated Docker
  container that is automatically downloaded at runtime. The platform integrates
  seamlessly with multiple source code management systems, including GitHub,
  GitHubEnterprise, Bitbucket, and GitLab, and supports multiple operating
  systems and architectures. Drone.io works with any language, database or
  service that runs inside a Docker container, and allows you to create and
  share plugins for pre-configured steps in your pipeline. Advanced
  customization is made easy with Drone.io, with features for implementing
  custom access controls, approval workflows, secret management, yaml syntax
  extensions and more. The platform also ensures isolated builds to avoid
  conflicts on shared servers, and offers effortless scaling.
instructions: null
changeLog:
  - date: 2022-08-04
    description: first release
links:
  - label: Website
    url: https://drone.io/
  - label: Documentation
    url: https://github.com/harness/drone#setup-documentation
  - label: Github
    url: https://github.com/harness/drone
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - runnerServiceName
    - runnerServiceImage
    - clientID
    - clientSecret
    - rpcHost
    - rpcProtocol
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: drone
    appServiceImage:
      type: string
      title: App Service Image
      default: drone/drone:2.16.0
    runnerServiceName:
      type: string
      title: Runner Service Name
      default: drone-runner
    runnerServiceImage:
      type: string
      title: Runner Service Image
      default: drone/drone-runner-docker:1.8.3
    clientID:
      type: string
      title: GitHub OAuth Client ID
    clientSecret:
      type: string
      title: GitHub OAuth Client Secret
      default: secret
    rpcHost:
      type: string
      title: RPC Host
    rpcProtocol:
      type: string
      title: RPC Protocol
      default: https
      oneOf:
        - enum:
            - https
          title: https
        - enum:
            - http
          title: http
    installRunner:
      type: boolean
      title: Install Runner Service
      default: false
    runnerCapacity:
      type: number
      title: Capacity for runner if enabled
      default: 2
