name: AdGuard Home
description: AdGuard Ad Blocker is a comprehensive solution designed to enhance
  your online browsing experience by eliminating all kinds of ads, from annoying
  banners and pop-ups to intrusive video ads. It not only removes these
  distractions but also maintains the functionality and appearance of the
  websites you visit. The app also offers privacy protection, shielding your
  data from web analytics and online trackers. In addition, AdGuard ensures
  browsing security by protecting against phishing and malicious sites. It also
  includes a parental control feature, providing a safe online environment for
  children by blocking inappropriate and adult content. The app is designed to
  work across all browsers and apps, offering a seamless ad-free experience.
  Moreover, it saves traffic and speeds up page loading by filtering ads before
  they reach your device. AdGuard is more than just an ad blocker; it's a tool
  that enhances your online safety and browsing speed.
instructions: During the setup phase, set the Admin Web Interface Port to 3000.
  To use the DHCP feature, you must also open ports 67/udp 68/tcp-udp.
changeLog:
  - date: 2023-07-11
    description: First Release
links:
  - label: Website
    url: https://adguard.com
  - label: Github
    url: https://github.com/AdguardTeam/AdGuardHome
  - label: Docker
    url: https://hub.docker.com/r/adguard/adguardhome
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: adguardhome
    appServiceImage:
      type: string
      title: App Service Image
      default: adguard/adguardhome:latest
