name: Jellyseerr
description: Overseerr is a powerful application designed to streamline the
  process of managing your media library. It offers full Plex integration,
  allowing you to log in and manage user access with Plex, and syncs with your
  Plex library to show what titles you already have. The app also integrates
  with Sonarr and Radarr, with plans for more services in the future. Overseerr
  features an easy-to-use request system, letting users request individual
  seasons or movies through a clean, user-friendly interface. The app also
  boasts a simple request management UI, making it easy to approve recent
  requests without having to navigate through the app. It also offers a granular
  permission system and localization into other languages. The mobile-friendly
  design ensures you can approve requests on the go. Jellyseerr, a fork of
  Overseerr, extends these features to Jellyfin and Emby media servers, offering
  full integration with these platforms. It also supports movies, shows, mixed
  libraries, and allows for easy integration with your existing services.
  Jellyseerr also offers a customizable request system, a simple request
  management UI, a granular permission system, and support for various
  notification agents.
instructions: none
changeLog:
  - date: 2022-12-20
    description: first release
links:
  - label: Documentation
    url: https://github.com/Fallenbagel/jellyseerr/tree/develop/docs
  - label: Github
    url: https://github.com/Fallenbagel/jellyseerr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: jellyseerr
    appServiceImage:
      type: string
      title: App Service Image
      default: fallenbagel/jellyseerr:1.3.0
