name: Commento
description: Commento is a comments widget designed to enhance the interaction
  on your website. It allows your readers to contribute to the discussion by
  upvoting comments that add value and downvoting those that don't. The widget
  supports markdown formatting, enabling bold, italics, external links, quotes,
  bullet points, code, and more. Commento also provides moderation tools to
  manage the conversation, allowing you to lock heated threads, remove off-topic
  comments, and enforce timeouts. It features a spam detection system, saving
  you the hassle of dealing with spammers. The widget supports nested replies,
  making discussions easier to follow. Importantly, Commento does not require
  your readers to sign up, reducing friction and encouraging more interaction.
  You can easily customize the look of the widget to match your website's
  aesthetics.
instructions: null
changeLog:
  - date: 2022-12-13
    description: first release
links:
  - label: Website
    url: https://commento.io/
  - label: Documentation
    url: https://commento.io/
  - label: Gitlab
    url: https://gitlab.com/commento/commento
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Derock
    url: https://github.com/ItzDerock
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: commento
    appServiceImage:
      type: string
      title: App Service Image
      default: registry.gitlab.com/commento/commento
    databaseServiceName:
      type: string
      title: Database Service Name
      default: commento-db
