name: pgweb
description: Pgweb is a simple, web-based, cross-platform PostgreSQL database
  explorer. It is designed to work seamlessly on Mac, Linux, and Windows
  machines. The app is distributed as a single binary with zero dependencies,
  making it incredibly easy to use. It supports PostgreSQL 9.1 and later
  versions, and allows for multiple database sessions. With Pgweb, you can
  execute and analyze custom SQL queries, export table and query data to
  CSV/JSON/XML, and keep track of your query history. The app also supports
  native SSH tunnels and server bookmarks for easy navigation.
instructions: null
changeLog:
  - date: 2023-3-15
    description: first release
links:
  - label: Documentation
    url: https://github.com/sosedoff/pgweb/wiki
  - label: Github
    url: https://github.com/sosedoff/pgweb
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: pgweb
    appServiceImage:
      type: string
      title: App Service Image
      default: sosedoff/pgweb:0.14.0
