name: Vaultwarden
description: Vaultwarden is an unofficial Bitwarden server implementation
  designed for self-hosted deployments. It is written in Rust and is compatible
  with the official Bitwarden clients. This application is ideal for
  individuals, families, and smaller organizations who find the official
  resource-heavy service undesirable. Vaultwarden supports a wide range of
  features including personal and organization vault support, password sharing
  and access control, file attachments, two-step login via email, Duo, YubiKey,
  and FIDO2 WebAuthn, and many more. It also supports live sync for
  desktop/browser clients/extensions and mobile clients (Android/iOS). However,
  it does not prioritize the development of features mainly useful to larger
  organizations such as single sign-on and directory syncing.
instructions: To access the administration interface, please go to /admin on
  your installation url. The admin token is in your "Environment" tab.
changeLog:
  - date: 2022-11-19
    description: first release
links:
  - label: Documentation
    url: https://github.com/dani-garcia/vaultwarden/wiki
  - label: Github
    url: https://github.com/dani-garcia/vaultwarden
  - label: Enviroment Variables
    url: https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: vaultwarden
    appServiceImage:
      type: string
      title: App Service Image
      default: vaultwarden/server:latest
