name: Homarr
description: Homarr is a powerful dashboard designed to simplify the management
  of your server. It provides a sleek, modern interface that brings all your
  apps and services together in one place, allowing you to access and control
  everything with ease. Homarr seamlessly integrates with the apps you've added,
  offering valuable insights and complete control. You can add your self-hosted
  applications or favorite websites to your dashboard and organize them as you
  like. Homarr supports integration with many popular applications to enhance
  your user experience. It is customizable, accessible, and supports 23
  languages. With Homarr, you can control and monitor your network directly, use
  integrations to display data and control apps, and even create your own
  dashboard using a comprehensible and easy-to-use visual editor. Homarr is
  open-source and allows commercial usage. It features a quick search function
  to easily navigate through your apps and supported integrations.
instructions: null
changeLog:
  - date: 2022-12-20
    description: First Release
links:
  - label: Website
    url: https://homarr.dev/
  - label: Documentation
    url: https://homarr.dev/docs
  - label: Github
    url: https://github.com/ajnart/homarr
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: homarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/ajnart/homarr:0.11.2
    serviceTimezone:
      type: string
      title: Timezone
      default: America/New_York
