name: PsiTransfer
description: PsiTransfer is a simple, open-source, self-hosted file sharing
  solution designed to provide an alternative to paid services like Dropbox and
  WeTransfer. The app allows for the sharing of many and very large files with
  ease, thanks to its support for streams. It also offers resumable uploads and
  downloads, ensuring you never lose progress. With PsiTransfer, you can set an
  expiry time for your upload bucket, and even offer one-time downloads. The app
  also supports downloading all files as a zip or tar.gz archive, and provides a
  modal-style file preview. For added security, PsiTransfer offers a
  password-protected download list. The app is lightweight and mobile-friendly,
  making it easy to use on any device. It also allows for explicit named bucket
  IDs with a query param sid=<myBucketID>.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Documentation
    url: https://github.com/psi-4ward/psitransfer/tree/master/docs
  - label: Github
    url: https://github.com/psi-4ward/psitransfer
contributors:
  - name: Mark Topper
    url: https://github.com/marktopper
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: psitransfer
    appServiceImage:
      type: string
      title: App Service Image
      default: psitrax/psitransfer:v2.1.1
