name: Shiori
description: Shiori is a straightforward bookmarks manager, designed as a simple
  alternative to Pocket. It is written in the Go language and can be used as
  either a command line application or a web application. Shiori allows for
  basic bookmark management, including adding, editing, deleting, and searching
  bookmarks. It also supports importing and exporting bookmarks from and to
  Netscape Bookmark file and importing bookmarks from Pocket. The application
  features a clean command line interface and a user-friendly web interface. It
  is portable and supports sqlite3, PostgreSQL, and MySQL as its database.
  Shiori also creates an offline archive of the webpage where possible. The
  Shiori Web Extension is a simple extension for managing bookmarks using
  Shiori, intended to integrate Shiori with your favorite web browser, allowing
  you to save and remove bookmarks in Shiori without leaving your current page.
instructions: The default account is "shiori" with password "gopher". It is
  removed once another "owner" account is created.
changeLog:
  - date: 2023-03-17
    description: Template created (v1.5.4)
links:
  - label: Github
    url: https://github.com/go-shiori/shiori
  - label: Web Extension
    url: https://github.com/go-shiori/shiori-web-ext
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: shiori
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/go-shiori/shiori:v1.5.4
    databaseServiceName:
      type: string
      title: Database Service Name
      default: shiori-db
