name: NocoDB
description: NocoDB is an innovative open-source platform that transforms any
  database into a smart spreadsheet. It's a powerful alternative to Airtable,
  designed to be flexible and user-friendly. With NocoDB, you can create
  unlimited grid views, gallery views, and form views from your own data. It
  offers ultra-ease in searching, sorting, and filtering columns and rows. You
  can invite your team with fine-grained access control, share views publicly or
  with password protection. NocoDB also allows you to build automations with
  your favourite apps like Microsoft Teams, Slack, Discord, Whatsapp, Twilio,
  Email & SMS. It provides instant REST APIs with Swagger. NocoDB is trusted by
  over 2000 organizations worldwide and is the fastest growing open source
  project. It's free and self-hostable, offering endless solutions for your
  business workflows.
instructions: null
changeLog:
  - date: 2023-02-8
    description: first release
links:
  - label: Website
    url: https://www.nocodb.com/
  - label: Documentation
    url: https://docs.nocodb.com/getting-started/installation/
  - label: Github
    url: https://github.com/nocodb/nocodb
contributors:
  - name: spacec0de
    url: https://github.com/spacec0de
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nocodb
    appServiceImage:
      type: string
      title: App Service Image
      default: nocodb/nocodb:0.106.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nocodb-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: nocodb-redis
