name: Mailhog
description: MailHog is an intuitive email testing tool designed for developers.
  It allows you to configure your application to use MailHog for SMTP delivery,
  enabling you to view your outgoing emails in a user-friendly web UI. The app
  also offers the option to release messages to real SMTP servers for delivery.
  With MailHog, you can view messages in the web UI or retrieve them using the
  JSON API. It supports SMTP AUTH and PIPELINING, and provides real-time updates
  using EventSource. MailHog also includes a Chaos Monkey for failure testing
  and HTTP basic authentication for its UI and API. It's lightweight, portable,
  and requires no installation.
instructions: null
changeLog:
  - date: 2022-10-31
    description: first release
links:
  - label: Github
    url: https://github.com/mailhog/MailHog/
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mailhog
    appServiceImage:
      type: string
      title: App Service Image
      default: mailhog/mailhog:latest
