name: SuiteCRM
description: SuiteCRM is the world's leading Open Source CRM, designed to help
  you sell, market, and service smarter. This feature-rich, enterprise-ready
  alternative to Salesforce offers all the benefits of CRM at a significantly
  lower cost, with the freedom and flexibility of Open Source. With SuiteCRM,
  you can gain a 360-degree view of your customers by creating a central
  repository for all your customer data, enabling you to gain key insights to
  enhance and nurture your business relationships. The platform is highly
  customizable and easy to use, with hundreds of extensions and integrations.
  SuiteCRM 8, our most advanced upgrade to date, promises to give you better
  control of your data and business solutions. The platform also allows for
  seamless integration with core business systems using our open REST API,
  enhancing productivity across your organization. With SuiteCRM, you can
  automate key actions, improve efficiency, understand your customers' needs,
  convert more leads, and engage your customers more effectively with
  personalized experiences and consistent messaging. It also empowers your
  customer service team to service smarter, faster, and more professionally.
instructions: null
changeLog:
  - date: 2023-1-12
    description: first release
  - date: 2023-07-12
    description: Added default user registration
links:
  - label: Website
    url: https://suitecrm.com/
  - label: Documentation
    url: https://docs.suitecrm.com/
  - label: Github
    url: https://github.com/salesagility/SuiteCRM
contributors:
  - name: Mxrcy
    url: https://github.com/DrMxrcy
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    suitecrmUsername:
      type: string
      title: Username
    suitecrmPassword:
      type: string
      title: Password
    suitecrmEmail:
      type: string
      title: Email
    appServiceName:
      type: string
      title: App Service Name
      default: suitecrm
    appServiceImage:
      type: string
      title: App Service Image
      default: bitnami/suitecrm:8
    databaseServiceName:
      type: string
      title: Database Service Name
      default: suitecrm-db
