name: Ackee
description: Ackee is a self-hosted, Node.js based analytics tool designed for
  those who value privacy. It operates on your own server, analyzing the traffic
  of your websites and providing valuable statistics through a minimalistic
  interface. Ackee offers an overview of all your websites, allowing you to
  analyze their collective performance. It provides insights into views,
  referrers, durations, and more. You can easily add, edit, and delete your
  domains, with a new tracking code just a few clicks away. Ackee's minimal UI
  allows you to analyze your data without losing focus, and its multi-step
  anonymization process ensures your users' privacy. The app allows you to
  analyze as many domains and apps as you want, and its interface is designed to
  be fast and easy to navigate. Ackee also offers a centralized GraphQL API,
  perfect for collecting data from a variety of sources. It uses a multi-step
  process to keep tracked data anonymized while still providing helpful
  analytics.
instructions: null
changeLog:
  - date: 2022-06-04
    description: first release
links:
  - label: Website
    url: https://ackee.electerious.com/
  - label: Documentation
    url: https://docs.ackee.electerious.com/
  - label: Github
    url: https://github.com/electerious/Ackee
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - ackeeUsername
    - ackeePassword
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    ackeeUsername:
      type: string
      title: Ackee Username
    ackeePassword:
      type: string
      title: Ackee Password
    appServiceName:
      type: string
      title: App Service Name
      default: ackee
    appServiceImage:
      type: string
      title: App Service Image
      default: electerious/ackee:3.4.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: ackee-db
