name: Rotki
description: Rotki is a comprehensive asset management and accounting
  application, specifically designed for crypto assets. The app is designed to
  help with tax reporting by importing, displaying, storing, and generating
  reports and statistics from cryptocurrency transaction data and other assets.
  It integrates with multiple exchanges, providing a centralized platform for
  managing your crypto assets. Rotki also offers the ability to generate
  profit/loss reports, making it easier to understand your financial standing.
  It's important to note that while Rotki aids in tax reporting, it does not
  provide tax or legal advice, and it's the user's responsibility to ensure the
  accuracy of the data provided to the service. The app is not intended for
  continuous monitoring of transaction data or for automatic transmission of
  your transaction data to any tax authority.
instructions: null
changeLog:
  - date: 2023-2-9
    description: first release
links:
  - label: Documentation
    url: https://rotki.readthedocs.io/en/latest/
  - label: Github
    url: https://github.com/rotki/rotki
  - label: Website
    url: https://rotki.com/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rotki
    appServiceImage:
      type: string
      title: App Service Image
      default: rotki/rotki:v1.27.1
