name: Webcord
description: "WebCord is an application designed to enhance your Discord
  experience. It is a pack of security and privacy hardenings, Discord features
  reimplementations, Electron / Chromium / Discord bugs workarounds,
  stylesheets, internal pages and wrapped https://discord.com page. It is
  designed to conform with ToS as much as it is possible. The application can be
  accessed at: http://yourhost:3000/ or https://yourhost:3001/. This container
  is based on Docker Baseimage KasmVNC which means there are additional
  environment variables and run configurations to enable or disable specific
  functionality."
instructions: use abc:abc to login. To access the login interface, add
  ?login=true to your URL.
changeLog:
  - date: 2023-5-7
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-webcord
  - label: Github
    url: https://github.com/SpacingBat3/WebCord
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: webcord
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/webcord:latest
