name: Cockpit
description: Cockpit is a headless content platform designed to streamline the
  creation, connection, and delivery of content for creators, marketers, and
  developers. It is built with an API-first approach, enabling limitless digital
  solutions. Cockpit offers a range of features including a content hub,
  multichannel localization, roles & permissions, and revisions. It also comes
  with a set of ready-to-use addons to support your projects. These include
  flexible structured content models, an assets manager, SEO and menu routes,
  content migration, custom action triggers, component-based layouts, full-text
  search for your content, form submissions collection, and localization.
  Cockpit is designed to fit your favorite tech stack, making it a versatile
  tool for all your content needs.
instructions: Navigate to /install to create the initial user account.
changeLog:
  - date: 2023-3-20
    description: first release
links:
  - label: Website
    url: https://getcockpit.com
  - label: Documentation
    url: https://getcockpit.com/documentation
  - label: Github
    url: https://github.com/Cockpit-HQ
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cockpit
    appServiceImage:
      type: string
      title: App Service Image
      default: cockpithq/cockpit:core-2.4.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: cockpit-db
