name: Chatpad
description: Chatpad AI is a premium quality user interface for ChatGPT,
  designed to provide the ultimate chatting experience. It's not just another
  ChatGPT interface, but a broader vision to revolutionize the way users
  interact with ChatGPT. The app is free and open-source, with its source code
  readily available on GitHub for anyone interested. Privacy is a top priority
  in Chatpad AI, with no tracking, no cookies, and all data being stored
  locally. The app is crafted with love and care, ensuring the best possible
  experience for its users. It's available as a web app and a desktop app,
  providing flexibility and convenience. Chatpad AI is also self-hostable using
  Docker, giving users full control over their data and usage.
instructions: null
changeLog:
  - date: 2023-3-26
    description: first release
links:
  - label: Website
    url: https://chatpad.ai
  - label: Github
    url: https://github.com/deiucanta/chatpad
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: chatpad
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/deiucanta/chatpad
