name: Heimdall
description: Heimdall Application Dashboard is a versatile and visually pleasing
  dashboard for all your web applications. It provides a simple and elegant
  interface where you can add links to any web application or site you
  frequently use. The app is designed with simplicity in mind, avoiding the trap
  of over-complication that many projects fall into. With Heimdall, you can add
  a link to anything, whether it's intrinsically supported or not, by simply
  filling in the name, background color, and the link URL. The app also supports
  Foundation and Enhanced apps. Foundation apps are those supported by Heimdall,
  and Enhanced apps are like Foundation apps but with the added feature of
  displaying extra information automatically by entering API credentials.
  Heimdall is all about making your web application experience smooth, simple,
  and enjoyable.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-2-24
    description: Update to v2.5.5
links:
  - label: Website
    url: https://heimdall.site/
  - label: Documentation
    url: https://heimdall.site/
  - label: Github
    url: https://github.com/linuxserver/Heimdall
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: heimdall
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/heimdall:2.5.6
    serviceTimezone:
      type: string
      title: Timezone
      default: Europe/London
