name: Isso
description: Isso is a lightweight commenting server designed to be a seamless
  alternative to Disqus. It is written in Python and JavaScript, and it allows
  users to leave comments on your website in a simple and straightforward
  manner. The app supports anonymous comments, preserving the identity of your
  users, and is easy to manage. Users can write comments in Markdown, and they
  also have the ability to edit or delete their own comments within a default
  time frame of 15 minutes. The app uses a SQLite backend, ensuring that your
  comments are not treated as Big Data. Additionally, it offers Disqus and
  WordPress import features, allowing you to migrate your existing comments
  without any hassle. The app is easily integrated into your website by
  embedding a single JavaScript file.
instructions: Go to /admin for administration interface
changeLog:
  - date: 2023-2-9
    description: first release
links:
  - label: Documentation
    url: https://isso-comments.de/docs/
  - label: Github
    url: https://github.com/posativ/isso
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - adminPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: isso
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/isso-comments/isso:0.13.0
    adminPassword:
      type: string
      title: Admin Password
