name: Shaarli
description: Shaarli is a personal, minimalist, super-fast, and database-free
  bookmarking service. It allows you to manage and share the links you discover,
  making it an ideal tool for those who frequently come across interesting
  content on the web. With Shaarli, you can share, comment, and save links, use
  it as a minimal blog or writing platform, or even as a read-it-later/todo
  list. It also serves as a notepad for drafting and saving articles, posts, or
  ideas, and a knowledge base for keeping notes, documentation, and code
  snippets. You can edit, view, and search your links, organize them with tags,
  and even generate ATOM and RSS feeds. Shaarli is self-hosted, meaning you
  install it on your own server, ensuring your data remains yours. It's an
  excellent alternative to commercial services, and it's free and open-source.
instructions: null
changeLog:
  - date: 2023-04-04
    description: first release
links:
  - label: Documentation
    url: https://demo.shaarli.org/doc/html/index.html
  - label: Github
    url: https://github.com/shaarli/Shaarli
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: shaarli
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/shaarli/shaarli:v0.12.2
