name: Budibase
description: Budibase is an open-source platform designed to simplify the
  creation of internal tools, saving teams hundreds of hours in the process.
  With Budibase, you can generate powerful internal tools and forms in just a
  few seconds, without any coding experience required. The platform allows you
  to connect to an external database, pull data from a Rest API, import a CSV,
  or start from scratch with Budibase's built-in database. You can design your
  tools using drag-and-drop components and automate workflows with just a few
  clicks. Budibase is trusted by over 75,000 teams and is designed to speed up
  your business operations. Whether you need to collect data securely, automate
  tasks, or streamline operations, Budibase has you covered.
instructions: Budibase takes a few minutes to get ready. Sit back, relax, and
  have a cup of tea!
changeLog:
  - date: 2022-10-30
    description: first release
links:
  - label: Website
    url: https://budibase.com/
  - label: Documentation
    url: https://docs.budibase.com/docs
  - label: Github
    url: https://github.com/Budibase/budibase
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: budibase
    appServiceImage:
      type: string
      title: App Service Image
      default: budibase/budibase:v2.5.6
