name: Oxigen
description: Oxigen is a dynamic social media image generator designed to
  streamline the process of creating and customizing og images. With a
  user-friendly interface and API, Oxigen allows you to effortlessly generate
  images tailored to your specific needs. Whether you're looking to create
  unique images for your social media posts or need a reliable tool for
  generating og images, Oxigen offers a flexible and efficient solution.
instructions: null
changeLog:
  - date: 2023-1-22
    description: first release
links:
  - label: Github
    url: https://github.com/yuriizinets/oxigen
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: oxigen
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/yuriizinets/oxigen:2.0-rc2
