name: Calibre
description: Calibre is a comprehensive e-book management tool designed to
  organize, convert, and read your e-book collection. It supports most of the
  major e-book formats and is compatible with various e-book reader devices.
  Calibre can fetch metadata for your books from the internet, enhancing your
  library with relevant information. It also allows you to download newspapers
  and convert them into e-books for a more convenient reading experience. The
  app is cross-platform, running on Linux, Windows, and macOS. With Calibre, you
  can easily add books to your library, convert them to a format your reader
  understands, and send them to your device. It also offers advanced features
  like e-book editing, metadata editing, and e-book comparison. The app is
  user-friendly, but also offers a Command Line Interface for more power and
  versatility.
instructions: Login using user ABC with your set password
changeLog:
  - date: 2023-3-1
    description: first release
links:
  - label: Website
    url: https://calibre-ebook.com/
  - label: Documentation
    url: https://manual.calibre-ebook.com/
  - label: Github
    url: https://github.com/kovidgoyal/calibre
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: calibre
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/calibre:6.14.0
    password:
      type: string
      title: Password
