name: Whiteboard
description: Whiteboard is a lightweight, NodeJS-based collaborative sketchboard
  that can be easily customized to your needs. It allows multiple users to draw
  and write together in real-time, with each user's cursor visible to others.
  The app provides a range of features including the ability to undo and redo
  actions, drag and drop or copy and paste images or PDFs, resize, move, rotate
  and draw images, write text and sticky notes, and save the whiteboard to an
  image or JSON. You can also draw angle lines and squares by pressing 'Shift'
  while drawing. The app is compatible with PC, tablet, and mobile devices, and
  can be used in various projects such as WebRTC conference tools and online
  collaboration learning activities.
instructions: null
changeLog:
  - date: 2022-08-01
    description: first release
links:
  - label: Website
    url: https://github.com/cracker0dks/whiteboard
  - label: Documentation
    url: https://github.com/cracker0dks/whiteboard
  - label: Github
    url: https://github.com/cracker0dks/whiteboard
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: whiteboard
    appServiceImage:
      type: string
      title: App Service Image
      default: rofl256/whiteboard:latest
