name: Matrix Synapse
description: Matrix is an open network designed for secure, decentralised
  communication. This app allows you to chat with friends, family, communities,
  and co-workers, providing a cozy, safe, and supercharged environment for your
  conversations. You can reclaim your space and build advanced, rich
  communication applications on top of Matrix. The app is part of a rich
  ecosystem that includes clients, servers, bots, and application services. It's
  an open-source project, generously hosted by UpCloud. With Matrix, you can
  start a conversation, build apps, and explore the vast possibilities of a
  decentralised communication network.
instructions: To create a user, simply execute the command
  "register_new_matrix_user -c data/homeserver.yaml" via console connection.
changeLog:
  - date: 2023-03-28
    description: First Release
links:
  - label: Website
    url: https://matrix.org
  - label: Docs
    url: https://matrix-org.github.io/synapse
  - label: Github
    url: https://github.com/matrix-org/synapse
  - label: Docker
    url: https://hub.docker.com/r/matrixdotorg/synapse
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    reportStats:
      type: boolean
      title: Report Stats
      default: true
    appServiceName:
      type: string
      title: App Service Name
      default: synapse
    appServiceImage:
      type: string
      title: App Service Image
      default: matrixdotorg/synapse:v1.80.0
    databaseType:
      type: string
      title: Database Type
      default: postgres
      oneOf:
        - enum:
            - postgres
          title: PostgreSQL
        - enum:
            - sqlite
          title: SQLite
    databaseServiceName:
      type: string
      title: Database Service Name
      default: synapse-db
