name: Change Detection
description: Changedetection.io is an intelligent tool designed to monitor
  changes on websites. It is perfect for smart shoppers, data journalists,
  research engineers, data scientists, security researchers, and more. The app
  allows you to watch up to 5,000 URLs and supports over 85 notification
  formats. It is capable of monitoring simple changes on a website, like price
  alterations or restock notifications, to deep inspections such as PDF text
  changes, JSON and XML monitoring, and extensive text triggers. The app also
  features intelligent product restock detection, making it easier for you to
  keep track of product availability. Additionally, it can perform interactive
  browser steps such as filling in text boxes, clicking buttons, and setting up
  your change detection scenario. With Changedetection.io, you can live your
  data life proactively, receiving notifications straight away when changes
  occur on your watched websites.
instructions: null
changeLog:
  - date: 2022-08-15
    description: first release
links:
  - label: Website
    url: https://changedetection.io
  - label: Github
    url: https://github.com/dgtlmoon/changedetection.io
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: changedetection
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/dgtlmoon/changedetection.io:0.42.2
