name: Openblocks
description: Openblocks is an open-source low code platform designed to help you
  build internal apps quickly and efficiently. With Openblocks, you can create
  admin panels, dashboards, approval queues, and client support apps with ease
  and speed. The platform offers over 50 built-in UI components, allowing you to
  build beautiful, functional, and user-friendly apps. You can also customize
  new components and embed them seamlessly into your apps. Openblocks connects
  to most databases and any REST API platform within clicks, enabling full
  integration of heterogeneous data from anywhere. It's a developer-first
  platform, allowing you to extend built-in components using JavaScript and
  leverage external JavaScript libraries. Openblocks also ensures security and
  reliability with role-based access control and audit logs. It's loved by
  developers for its super-polished interface and mind-blowing functionality.
instructions: null
changeLog:
  - date: 2023-02-21
    description: first release
links:
  - label: Website
    url: https://openblocks.dev/
  - label: Documentation
    url: https://docs.openblocks.dev/
  - label: Github
    url: https://github.com/openblocks-dev/openblocks
  - label: Discord Community
    url: https://discord.com/invite/z5W2YHXdtt
contributors:
  - name: spaceb0t
    url: https://github.com/spacec0de
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: openblocks
    appServiceImage:
      type: string
      title: App Service Image
      default: openblocksdev/openblocks-ce:1.1.6
