name: Github Desktop
description: Github Desktop is an open-source, Electron-based application that
  simplifies the way you interact with GitHub. Written in TypeScript and using
  React, this app provides a user-friendly interface for managing your GitHub
  repositories. It allows you to access your GitHub account, manage your
  repositories, make changes, and track updates, all from the convenience of
  your desktop. The app is accessible via http://yourhost:3000/ or
  https://yourhost:3001/. It supports multiple architectures and can be easily
  deployed using Docker. Please note that this app requires specific environment
  variables and run configurations for optimal functionality.
instructions: use abc:abc to login. To access the login interface, add
  ?login=true to your URL.
changeLog:
  - date: 2023-04-12
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-github-desktop
  - label: Github
    url: https://github.com/desktop/desktop
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: github-desktop
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/github-desktop
