name: Meilisearch
description: Meilisearch Cloud is a next-generation, open-source search engine
  designed to enhance your search experience. This powerful tool can be
  effortlessly integrated into any website or application, providing
  lightning-fast, hyper-relevant search results in less than 50 milliseconds.
  With Meilisearch, you can deploy a user-focused search experience in just a
  few minutes, thanks to its smart presets that require zero configuration. It
  offers the most advanced full-text search engine with great relevancy that
  fits every use case. Meilisearch supports all languages and automatically
  detects them, allowing for a truly global search experience. It also allows
  for custom relevancy, enabling you to create your own ranking rules.
  Meilisearch ensures secure searches with API keys and tenant tokens, and even
  allows for real-world geo searches. With Meilisearch Cloud, you can enhance
  your user's search experience with custom filters and build a faceted search
  interface in just a few lines of code.
instructions: null
changeLog:
  - date: 2022-10-31
    description: first release
links:
  - label: Website
    url: https://meilisearch.com/
  - label: Documentation
    url: https://docs.meilisearch.com/
  - label: Github
    url: https://github.com/meilisearch/meilisearch/
  - label: Discord
    url: https://discord.gg/meilisearch
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - dataVolumeName
    - meiliEnv
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: meilisearch
    appServiceImage:
      type: string
      title: App Service Image
      default: getmeili/meilisearch:v0.30
    dataVolumeName:
      type: string
      title: Meilisearch Database Volume Name
      default: meilisearch
    meiliEnv:
      type: string
      title: Meilisearch Environment
      default: production
      oneOf:
        - enum:
            - production
          title: Production
        - enum:
            - development
          title: Development
    meiliMasterKey:
      type: string
      title: Meilisearch Master Key
    meiliNoAnalytics:
      type: boolean
      title: Disable Meilisearch Analytics
      default: false
    meiliScheduleSnapshot:
      type: boolean
      title: Enable Database Scheduled Snapshots
      default: false
    meiliSnapshotInterval:
      type: string
      title: Scheduled Snapshots Interval (in seconds)
      default: "86400"
