name: OpenSpeedTest
description: OpenSpeedTest is a powerful and accurate online bandwidth test
  application that works on any web browser without the need for Flash or Java.
  It is designed to replicate your real-world connection speed and is capable of
  testing any connection, from 1 Kbps to 1 Gbps+. The application uses the
  latest technology to automatically detect your stable download and upload
  speed from our servers. It also provides a guide on how to increase your
  internet speed and get more out of your connection. You can create your own
  network speed test without any client-side software or plugin. The application
  can also be embedded to your website or application, allowing your users to
  test their internet speed without leaving your page. It is also available as a
  standalone application for home or small office LAN and can be used for
  large-scale deployments as a self-hosted/on-premise network speed test.
instructions: null
changeLog:
  - date: 2022-11-30
    description: first release
links:
  - label: Website
    url: https://openspeedtest.com/
  - label: Github
    url: https://github.com/openspeedtest/Speed-Test
contributors:
  - name: Migu2k
    url: https://github.com/migu2k
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: openspeedtest
    appServiceImage:
      type: string
      title: App Service Image
      default: openspeedtest/latest
