name: Servas
description: Servas is a self-hosted bookmark management tool that allows you to
  organize and access your bookmarks in a more efficient and streamlined manner.
  With Servas, you can categorize your bookmarks using tags and groups, which
  can also be nested for better organization. The app also features a 'Later
  List' where you can add bookmarks that you wish to access at a later time.
  Servas also comes with a Chrome browser extension, allowing you to add sites
  to your bookmark list directly from your browser. The app supports multiple
  user accounts and boasts a responsive design that ensures it looks good on all
  your devices. For added security, Servas also offers Two Factor
  Authentication.
instructions: Visit /register to create an account
changeLog:
  - date: 2023-1-30
    description: first release
links:
  - label: Github
    url: https://github.com/beromir/Servas
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: servas
    appServiceImage:
      type: string
      title: App Service Image
      default: beromir/servas:0.0.4
    databaseServiceName:
      type: string
      title: Database Service Name
      default: servas-db
