name: Umami
description: Umami is a privacy-focused, open-source alternative to Google
  Analytics. It is designed to respect user privacy by not collecting any
  personal information, using cookies, or tracking users across websites. It is
  GDPR compliant and ensures that all data collected is anonymized, making it
  impossible to identify any individual user. Umami is simple and easy to use,
  collecting only the metrics you care about and presenting them on a single
  page. It is a reliable and transparent product with over 4 million downloads.
  With Umami, you can own your data and stay compliant with ever-changing data
  privacy laws.
instructions: You can login with username "admin" and password "umami".
changeLog:
  - date: 2022-09-27
    description: first release
links:
  - label: Website
    url: https://umami.is/
  - label: Github
    url: https://github.com/umami-software/umami
  - label: Documentation
    url: https://umami.is/docs
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: umami
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/umami-software/umami:postgresql-latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: umami-db
