name: Firefox
description: Firefox Browser, also known as Mozilla Firefox or simply Firefox,
  is a free and open-source web browser developed by the Mozilla Foundation and
  its subsidiary, the Mozilla Corporation. This app allows you to deploy and run
  Firefox in a containerized environment, providing a secure and isolated space
  for your browsing activities. Firefox uses the Gecko layout engine to render
  web pages, implementing current and anticipated web standards. The app
  supports multiple architectures and can be accessed via HTTP or HTTPS. It also
  offers additional environment variables and run configurations to enable or
  disable specific functionalities. This containerized version of Firefox is
  capable of delivering a true lossless image at a high framerate to your web
  browser, providing an optimal browsing experience.
instructions: use abc:abc to login. To access the login interface, add
  ?login=true to your URL.
changeLog:
  - date: 2022-11-14
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-firefox
  - label: Github
    url: https://github.com/linuxserver/docker-firefox
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: firefox
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/firefox:latest
