name: Radicale
description: Radicale is a small but powerful CalDAV (calendars, to-do lists) and CardDAV (contacts) server. It allows you to share calendars and contact lists through CalDAV, CardDAV, and HTTP. Radicale supports events, todos, journal entries, and business cards. It works out-of-the-box, requiring no complicated setup or configuration. Radicale can limit access by authentication and secure connections with TLS. It works with many CalDAV and CardDAV clients, stores all data on the file system in a simple folder structure, and can be extended with plugins. Radicale is GPLv3-licensed free software.
instructions: Login with any username or password
changeLog:
  - date: 2023-3-27
    description: first release
links:
  - label: Website
    url: https://radicale.org/
  - label: Documentation
    url: https://radicale.org/v3.html
  - label: Github
    url: https://github.com/Kozea/Radicale
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: radicale
    appServiceImage:
      type: string
      title: App Service Image
      default: tomsquest/docker-radicale:3.1.8.1
