name: Supertokens Core
description: SuperTokens is an advanced user authentication solution designed to
  streamline your app's security. It offers a range of features including user
  roles, two-factor authentication (2FA), Single Sign-On (SSO) with platforms
  like AD and Okta, session management, user management, account linking, and
  machine authentication. The app is trusted by startups and enterprises alike
  for its ease of setup and use. With SuperTokens, you can host your login page
  on your own domain, eliminating the need for redirects. It also provides
  prebuilt UIs and frontend SDKs to help you build your own login page quickly.
  SuperTokens is also capable of handling multitenant SSO, allowing each
  customer to have their own user pool. Loved by the world's best teams,
  SuperTokens is your go-to solution for user authentication and session
  management.
instructions: Check environment tab for your API key
changeLog:
  - date: 2023-2-22
    description: first release
links:
  - label: Website
    url: https://supertokens.com/
  - label: Documentation
    url: https://supertokens.com/docs
  - label: Github
    url: https://github.com/supertokens
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: supertokens-core
    appServiceImage:
      type: string
      title: App Service Image
      default: supertokens/supertokens-postgresql:4.3
    databaseServiceName:
      type: string
      title: Database Service Name
      default: supertokens-core-db
