name: Hiccup
description: Hiccup is a static start page application designed to help you
  access your most important links quickly and efficiently. It allows you to
  categorize your links, add them via drag and drop, and even search for them
  using various search providers. The app also supports multiple profiles,
  enabling you to switch between different sets of links based on your needs.
  Hiccup also features a built-in config manager for easy management of your
  link configurations. The app is designed to be used anywhere you can serve a
  static webpage from, such as your home server or a new browser tab. It also
  supports full keyboard navigation for quick and easy access to your links.
instructions: null
changeLog:
  - date: 2023-3-21
    description: first release
links:
  - label: Github
    url: https://github.com/ashwin-pc/hiccup
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: hiccup
    appServiceImage:
      type: string
      title: App Service Image
      default: bleckbeard/hiccup:v0.4.3
