name: PowerDNS-Admin
description: PowerDNS-Admin is a comprehensive web interface for PowerDNS with a
  plethora of advanced features. It offers forward and reverse zone management,
  zone templating, and user management with role-based access control. The app
  also provides zone-specific access control and activity logging. It supports
  various authentication methods including Local User, SAML, LDAP, and OAuth
  with Google, GitHub, Azure, and OpenID. It also supports two-factor
  authentication (TOTP). PowerDNS-Admin is equipped with PDNS Service
  Configuration & Statistics Monitoring and supports the DynDNS 2 protocol. It
  makes IPv6 PTR record editing easy and provides an API for zone and record
  management. The app also fully supports IDN/Punycode. PowerDNS-Admin can be
  run in several ways, with Docker being the quickest.
instructions: null
changeLog:
  - date: 2022-11-28
    description: first release
links:
  - label: Github
    url: https://github.com/PowerDNS-Admin/PowerDNS-Admin
  - label: Documentation
    url: https://github.com/PowerDNS-Admin/PowerDNS-Admin/wiki
contributors:
  - name: Migu2k
    url: https://github.com/migu2k
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: powerdns-admin
    appServiceImage:
      type: string
      title: App Service Image
      default: ngoduykhanh/powerdns-admin:latest
