name: Jellyfin
description: Jellyfin is a free software media system that allows you to take
  full control of your media. It enables you to collect, manage, and stream your
  media from your own server to any device. With Jellyfin, you can enjoy your
  entire movie collection, watch your favorite shows, listen to your music, and
  even read your books and comics. It also offers features for live TV and DVR,
  allowing you to watch TV and set automatic recordings to expand your library.
  Jellyfin also provides a SyncPlay feature, making remote movie nights easier
  than ever. The app is available on most popular platforms, ensuring your media
  is ready to follow you wherever you go. Jellyfin is licensed under the GNU
  GPL, meaning you can use, study, modify, build, and distribute it for free. It
  is a privacy-focused solution with no tracking or central servers collecting
  your data.
instructions: Jellyfin takes a few minutes to get ready. Sit back, relax, and
  get some popcorn!
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Website
    url: https://jellyfin.org/
  - label: Documentation
    url: https://jellyfin.org/docs
  - label: Github
    url: https://github.com/jellyfin/jellyfin
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: jellyfin
    appServiceImage:
      type: string
      title: App Service Image
      default: jellyfin/jellyfin:10.8.9
