name: Element
description: Element is a secure communications platform designed to protect and
  strengthen your business critical communications. It offers real-time trusted
  communication across organizations, giving you the freedom to communicate on
  your own terms. With Element, you can control your data through its open
  source and flexible hosting, enabling data sovereignty. The app allows you to
  structure discussion spaces, customize chat rooms, and share live data through
  widgets and integrations to boost your productivity. It also provides instant
  messaging, voice/video calls, location sharing, voting polls and more. Element
  ensures your data is secure by default, allowing you to focus on getting your
  work done. You have complete independence to own and control your entire
  communication platform, configure networks to suit organizational
  requirements, and strengthen cybersecurity and business continuity plans.
  Element is led by the creators of Matrix, the decentralized open standard for
  secure and sovereign real time communication.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
  - date: 2023-2-24
    description: Update to v1.11.23
links:
  - label: Website
    url: https://element.io/
  - label: Documentation
    url: https://github.com/vector-im/element-web/wiki
  - label: Github
    url: https://github.com/vector-im/element-web
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: element
    appServiceImage:
      type: string
      title: App Service Image
      default: vectorim/element-web:v1.11.30
