name: Wizarr
description: Wizarr is an automatic user invitation system designed to
  streamline the process of inviting users to your media server. Whether you're
  using Plex, Jellyfin, or Emby, Wizarr allows you to create a unique link to
  share with users, automatically inviting them to your server. The app also
  guides users on how to download the necessary client and provides instructions
  on how to use your request software. Wizarr offers a secure invitation
  environment, plug and play SSO support, multi-tiered invitations, and
  customizable duration for membership. It also integrates with Discord,
  allowing you to invite users to your Discord server. The app is customizable,
  allowing you to add any custom HTML as needed.
instructions: null
changeLog:
  - date: 2023-03-1
    description: first release
  - date: 2023-03-22
    description: Update to v2.1.3
links:
  - label: Documentation
    url: https://docs.wizarr.dev
  - label: Github
    url: https://github.com/Wizarrrr/wizarr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wizarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/wizarrrr/wizarr:2.1.3
