name: Monica
description: OfficeLife is an all-in-one tool designed to manage a company
  efficiently. It serves as your personal CRM, helping you organize and
  follow-up on your social interactions, thereby strengthening your
  relationships. With Monica, you can easily log and remember important details
  about your friends, family, and colleagues. It allows you to store everything
  you know about your loved ones in one place, from their work information,
  family details, activities you've done together, to reminders about important
  dates. Monica is designed for busy individuals striving to maintain a good
  work-life balance. It's a private space, free from ads or malicious software,
  where you can safely document what you know about who you love. Monica is open
  source, ensuring transparency and security.
instructions: null
changeLog:
  - date: 2023-03-17
    description: First Release
links:
  - label: Website
    url: https://monicahq.com
  - label: Github
    url: https://github.com/monicahq/monica
  - label: Docker
    url: https://hub.docker.com/_/monica
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - redisServiceName
    - databaseServiceName
    - databaseType
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: monica
    appServiceImage:
      type: string
      title: App Service Image
      default: monica:4.0.0
    redisServiceName:
      type: string
      title: Redis Service Name
      default: monica-redis
    databaseServiceName:
      type: string
      title: Database Service Name
      default: monica-db
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
    databasePrefix:
      type: string
      title: Database Prefix
    databaseUseUtf8mb4:
      type: boolean
      title: Database use utf8mb4
      default: true
    monicaAppDisableSignup:
      type: boolean
      title: Disable Signup
      default: true
    monicaCheckVersion:
      type: boolean
      title: Check Version
      default: true
