name: Kopia
description: Kopia is a robust open-source backup and restore tool designed to
  provide fast and secure backups of your important data. It allows you to
  create encrypted snapshots of your files and directories, which can be stored
  on the cloud storage of your choice, network-attached storage, server, or
  locally on your machine. Kopia supports a wide range of storage locations
  including Amazon S3, Azure Blob Storage, Backblaze B2, Google Cloud Storage,
  and many more. It also supports both CLI and GUI versions, making it
  accessible for both advanced and regular users. Kopia's unique features
  include compression, deduplication, end-to-end 'zero knowledge' encryption,
  and error correction, ensuring your data is safe, secure, and easily
  retrievable.
instructions: null
changeLog:
  - date: 2023-07-10
    description: First Release
links:
  - label: Website
    url: https://kopia.io/
  - label: Docs
    url: https://kopia.io/docs/
  - label: Github
    url: https://github.com/kopia/kopia/
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - kopiaUsername
    - kopiaPassword
  properties:
    projectName:
      type: string
      title: Project Name
    kopiaUsername:
      type: string
      title: Username
    kopiaPassword:
      type: string
      title: Password
    appServiceName:
      type: string
      title: App Service Name
      default: kopia
    appServiceImage:
      type: string
      title: App Service Image
      default: kopia/kopia:0.13
