name: Ntfy
description: ntfy, pronounced as 'notify', is a simple, HTTP-based pub-sub
  notification service that allows you to send push notifications to your phone
  or desktop from any computer. It operates via scripts using simple HTTP PUT or
  POST requests. This makes it a handy tool for notifying yourself when scripts
  fail or when long-running commands complete. To use ntfy, you simply need to
  install the app on your phone, subscribe to a topic of your choice, and start
  sending messages to your topic. The app is available on Google Play, F-Droid,
  and the App Store. ntfy is open-source and free to use, but also offers paid
  plans for those who wish to support its development.
instructions: null
changeLog:
  - date: 2022-11-21
    description: first release
links:
  - label: Documentation
    url: https://docs.ntfy.sh
  - label: Github
    url: https://github.com/binwiederhier/ntfy
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ntfy
    appServiceImage:
      type: string
      title: App Service Image
      default: binwiederhier/ntfy:v2.4.0
