name: Cusdis
description: Cusdis is a lightweight, open-source comment system designed with
  privacy as a priority. It serves as an alternative to Disqus, offering a
  simple and user-friendly way to integrate a comment system into your existing
  website. The app is incredibly lightweight, with the JS SDK embedded to your
  website being only around 5kb. It features built-in i18n and dark-mode for a
  seamless user experience. Cusdis ensures you stay updated with new comments
  through email notifications, and allows for quick approval of comments
  directly from the notification email or webhook. You can also set a webhook
  URL that triggers when your website receives a new comment, allowing you to
  integrate Cusdis with your favorite tools such as Telegram. The app offers
  flexibility with its pricing, providing a free self-hosting option, a free
  cloud option with limited features, and a Cloud Pro option for unlimited
  access.
instructions: null
changeLog:
  - date: 2023-04-12
    description: first release
links:
  - label: Website
    url: https://cusdis.com
  - label: Documentation
    url: https://cusdis.com/docs
  - label: Github
    url: https://github.com/djyde/cusdis/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - username
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cusdis
    appServiceImage:
      type: string
      title: App Service Image
      default: djyde/cusdis:1.3.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: cusdis-db
    username:
      type: string
      title: Username
    password:
      type: string
      title: Password
