name: Lenpaste
description: Lenpaste is a web service that allows you to share notes
  anonymously. It is an open-source alternative to pastebin.com. The app
  supports multiple languages and uses cookies only to store settings. It can
  work without JavaScript and has its own API. Lenpaste allows you to set
  maximum length for the paste title and body, maximum lifetime of the paste,
  and rate limits for viewing and creating pastes. It also provides options to
  prohibit search engine crawlers from indexing the site and to set information
  about the server admin. Lenpaste is self-hosted and provides a list of public
  servers managed by various contributors.
instructions: null
changeLog:
  - date: 2023-1-28
    description: update to v1.3
  - date: 2022-12-20
    description: first release
links:
  - label: Documentation
    url: https://git.lcomrade.su/root/lenpaste/src/branch/main/docs
  - label: Gitea
    url: https://git.lcomrade.su/root/lenpaste
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Leonid Maslakov
    url: https://lcomrade.su
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: lenpaste
    appServiceImage:
      type: string
      title: App Service Image
      default: git.lcomrade.su/root/lenpaste:1.3
