name: CubeJS
description: Cube is a Semantic Layer for every data app that aims to connect
  data silos, drive consistent metrics, and power your AI and analytics with
  context. It allows you to define and manage metrics upstream to consolidate
  your workflow, centralize definitions, and create a single source of truth.
  The app also provides granular access controls to grant column- and role-based
  operational and viewing permissions upstream. Cube ensures your data is
  reliably performant with a powerful caching layer and advanced preaggregation
  capabilities. Furthermore, it allows you to connect your data to any front-end
  application to build beautiful custom visualizations with Cube’s GraphQL,
  REST, and SQL APIs. Cube is an API-first, four-part semantic layer that
  enables data engineers and developers to make their data consistent, secure,
  performant, and accessible across every application.
instructions: null
changeLog:
  - date: 2023-2-27
    description: first release
links:
  - label: Website
    url: https://cube.dev
  - label: Documentation
    url: https://cube.dev/docs
  - label: Github
    url: https://github.com/cube-js/cube.js
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cubejs
    appServiceImage:
      type: string
      title: App Service Image
      default: cubejs/cube:v0.31.66
    databaseServiceName:
      type: string
      title: Database Service Name
      default: cubejs-db
