name: Netbox
description: NetBox is a comprehensive solution designed to be the single source
  of truth for everything on your network. It provides a detailed overview of
  both physical and virtual assets, including power systems, cabling, IP
  addresses, and VLANs. The app is designed to facilitate network automation and
  monitoring, drawing from an authoritative plan to push out configurations and
  monitor changes across the enterprise. It offers a complete DCIM solution,
  providing visibility and control across the entire enterprise. NetBox also
  features efficient IP Address Management, ensuring the safe and efficient
  management of IP assets across the enterprise, thereby minimizing the risk of
  data entry errors. The app is customizable and can be integrated to extend its
  functionality to fit your specific needs.
instructions: null
changeLog:
  - date: 2023-3-17
    description: first release
links:
  - label: Website
    url: https://netbox.dev
  - label: Documentation
    url: https://docs.netbox.dev/
  - label: Github
    url: https://github.com/netbox-community/netbox
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
    - netboxEmail
    - netboxPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: netbox
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/netbox:3.4.6
    databaseServiceName:
      type: string
      title: Database Service Name
      default: netbox-db
    redisServiceName:
      type: string
      title: Database Service Name
      default: netbox-redis
    netboxEmail:
      type: string
      title: E-Mail Address
    netboxPassword:
      type: string
      title: Password
