name: Strapi
description: Strapi is a leading open-source headless CMS that is fully
  customizable and built with 100% JavaScript. It allows you to manage any
  content, anywhere, providing you with the freedom to use your favorite tools
  and frameworks. With Strapi, you can build apps quickly, getting your backend
  done in minutes instead of weeks. You can easily build customizable content
  APIs and use them with a modern tech stack. Strapi also allows you to
  effortlessly create content structures that flex to your needs, write, edit,
  and manage any content types, and build apps and digital experiences without
  the distraction of CMS complexities. You can consume Strapi API from any
  client using REST or GraphQL, and deploy on Strapi Cloud or on any cloud
  platforms.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://strapi.io/
  - label: Documentation
    url: https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html
  - label: Github
    url: https://github.com/strapi
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: strapi
    appServiceImage:
      type: string
      title: App Service Image
      default: strapi/strapi:3.6.8-alpine
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: strapi-db
