name: Calcom
description: Cal.com is a versatile scheduling app designed to streamline the
  process of setting up meetings, appointments, and events. It allows users to
  set their availability, connect their existing calendars, and share a personal
  link for others to book a meeting at a time that works for both parties. The
  app ensures you never get double booked by checking for conflicts across all
  your calendars. It also offers workflow automation, enabling you to build
  processes around your events with automatic notifications, reminders, and
  follow-ups. With features like round-robin scheduling, routing forms, and
  meeting overload prevention, Cal.com adapts to any business, making it an
  ideal solution for doctors, companies, teachers, and experts. The app is
  available in over 26 languages and can be embedded anywhere for easy access.
  It also offers simple rescheduling and requires confirmation to ensure smooth
  scheduling.
instructions: null
changeLog:
  - date: 2023-04-03
    description: First Release
links:
  - label: Website
    url: https://cal.com
  - label: Github
    url: https://github.com/calcom/cal.com
  - label: Docker
    url: https://hub.docker.com/r/calcom/cal.com
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    enableStudio:
      type: boolean
      title: Enable Prisma Studio
      default: false
    appServiceName:
      type: string
      title: App Service Name
      default: calcom
    appServiceImage:
      type: string
      title: App Service Image
      default: calcom/cal.com:v2.7.6
    databaseServiceName:
      type: string
      title: App Service Name
      default: calcom-db
