name: Pufferpanel
description: PufferPanel is a free, open-source game server management panel
  that simplifies the management of your game servers. It supports a wide
  variety of games including Minecraft, Forge, Spigot, Sponge, Source Dedicated
  Servers, BungeeCord, PocketMine, and many more. With PufferPanel, you can
  easily manage multiple game servers from one central location, providing a
  streamlined and efficient way to control your gaming environment. Whether
  you're an individual user or a large network, PufferPanel's user-friendly
  interface makes game server management a breeze.
instructions: Run "./pufferpanel user add" in the console to create a new user.
changeLog:
  - date: 2023-3-21
    description: first release
links:
  - label: Website
    url: https://pufferpanel.com/
  - label: Documentation
    url: https://docs.pufferpanel.com/en/latest
  - label: Github
    url: https://github.com/PufferPanel/PufferPanel
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: pufferpanel
    appServiceImage:
      type: string
      title: App Service Image
      default: pufferpanel/pufferpanel:2.6.6
