name: Joplin
description: Joplin is an open-source note-taking application that allows you to capture your thoughts and access them securely from any device. It supports multimedia notes, including images, videos, PDFs, and audio files, and even allows the creation of math expressions and diagrams. With Joplin Cloud, you can share your notes and collaborate with others. The app also features a web clipper extension for saving web pages or screenshots as notes. Joplin can be customized with plugins, themes, and multiple text editors, and it synchronizes with various services, including Joplin Cloud, Dropbox, and OneDrive. All notes are saved in an open format and secured with end-to-end encryption.
instructions: null
changeLog:
  - date: 2023-03-16
    description: First Release
links:
  - label: Website
    url: https://joplinapp.org/
  - label: Github
    url: https://github.com/laurent22/joplin/
  - label: Docker
    url: https://hub.docker.com/r/joplin/server
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: joplin
    appServiceImage:
      type: string
      title: App Service Image
      default: joplin/server:2.10.10-beta
    databaseServiceName:
      type: string
      title: Database Service Name
      default: joplin-db
