name: pgvector
description: pgvector is an open-source app designed to facilitate vector
  similarity search for Postgres. It allows you to store all your application
  data in one place, supporting both exact and approximate nearest neighbor
  search. The app is capable of handling L2 distance, inner product, and cosine
  distance, making it versatile for various data analysis needs. It is
  compatible with any language that has a Postgres client. The app also boasts
  of ACID compliance, point-in-time recovery, JOINs, and all the other great
  features of Postgres. With pgvector, you can create a new table with a vector
  column or add a vector column to an existing table, insert vectors, upsert
  vectors, update vectors, and delete vectors. It also allows you to get the
  nearest neighbors to a vector or a row, and get rows within a certain
  distance. The app also supports indexing for improved search performance. It
  is a powerful tool for managing and analyzing your data in a Postgres
  environment.
instructions: null
changeLog:
  - date: 2023-06-30
    description: first release
links:
  - label: Github
    url: https://github.com/pgvector/pgvector
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - serviceName
    - serviceImage
  properties:
    projectName:
      type: string
      title: Project Name
    serviceName:
      type: string
      title: Service Name
    serviceImage:
      type: string
      title: Service Image
      default: ankane/pgvector:v0.4.4
