name: HumHub
description: HumHub is a flexible open-source social network kit designed to
  facilitate communication and collaboration. It allows you to create your own
  customized social network, social intranet, or large social enterprise
  application tailored to your specific needs. Whether you're looking to boost
  your business, support your customers, educate your students, or organize your
  football club, HumHub provides the tools to make it happen. It features an
  intuitive user interface and a powerful module system that can be extended
  with third-party tools, your own creations, or existing software. With HumHub,
  you have full control over your server and data. The app also offers features
  like posts and updates, file sharing, liking and commenting, and 'Spaces' for
  group communication. You can extend your profile, create a portfolio, connect
  with others, and find people with specific skills. With its module system, you
  can modify anything on HumHub according to your requirements. The app also
  supports live updates, notifications, activity streams, dashboards, user
  profiles, groups, directories, file sharing, public access, search
  functionality, and mobile readiness.
instructions: null
changeLog:
  - date: 2023-1-22
    description: first release
links:
  - label: Website
    url: https://www.humhub.com
  - label: Documentation
    url: http://docs.humhub.org/
  - label: Github
    url: https://github.com/humhub/humhub/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: humhub
    appServiceImage:
      type: string
      title: App Service Image
      default: mriedmann/humhub:1.13.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: humhub-db
