name: Dokuwiki
description: DokuWiki is a highly versatile, open-source wiki software that is
  simple to use and doesn't require a database. It is known for its clean and
  readable syntax, making it a favorite among administrators due to its ease of
  maintenance, backup, and integration. DokuWiki is equipped with built-in
  access controls and authentication connectors, making it particularly useful
  in an enterprise context. It supports a wide range of use cases beyond a
  traditional wiki, thanks to the large number of plugins available. DokuWiki is
  designed for collaboration, allowing quick updates and easy addition of new
  pages while maintaining a history of every change. It can be used as a
  corporate knowledge base, private notebook, software manual, project
  workspace, CMS, intranet, and more. DokuWiki supports customization at all
  levels of expertise, from easy configuration via the admin interface to
  developing your own extensions.
instructions: Go to http://IP-ADDRESS:PORT/install.php to configure your install
  then restart your container when finished to remove install.php
changeLog:
  - date: 2023-3-16
    description: first release
links:
  - label: Website
    url: https://dokuwiki.org
  - label: Documentation
    url: https://www.dokuwiki.org/manual
  - label: Github
    url: https://github.com/splitbrain/dokuwiki
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: dokuwiki
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/dokuwiki:version-2022-07-31a
