name: PhotoPrism
description: PhotoPrism is an AI-powered photos app designed for the decentralized web. It uses the latest technologies to automatically tag and find pictures without interrupting your workflow. You can run it at home, on a private server, or in the cloud. PhotoPrism allows you to browse all your photos and videos without worrying about RAW conversion, duplicates, or video formats. It offers powerful search filters to easily find specific pictures and includes high-resolution world maps to relive your favorite trips. The app supports playing Live Photos by hovering over them in albums and search results, recognizes the faces of your family and friends, and automatically classifies pictures based on their content and location. PhotoPrism is committed to user and privacy-friendly solutions, ensuring your data is never shared without your consent.
instructions: null
changeLog:
  - date: 2023-03-16
    description: First Release
links:
  - label: Website
    url: https://photoprism.app
  - label: Demo
    url: https://try.photoprism.app
  - label: Github
    url: https://github.com/photoprism/photoprism
  - label: Docker
    url: https://hub.docker.com/r/photoprism/photoprism
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - photoprismAdminUser
    - photoprismAdminPassword
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: photoprism
    appServiceImage:
      type: string
      title: App Service Image
      default: photoprism/photoprism:221118-jammy
    photoprismAdminUser:
      type: string
      title: Username
    photoprismAdminPassword:
      type: string
      title: Password
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - sqlite
          title: SQLite
    databaseServiceName:
      type: string
      title: Database Service Name
      default: photoprism-db
