name: DomainMod
description: DomainMOD is a comprehensive open-source application designed to
  help you manage your domains and other internet assets in one central
  location. With DomainMOD, you can keep track of your domains, SSL
  certificates, registrar and SSL accounts, web hosting, DNS servers, IP
  addresses, and more. The application also offers a Bulk Domain Updater,
  allowing you to modify multiple domains at once, saving you time and effort.
  DomainMOD also includes a Data Warehouse feature, which lets you import data
  from your WHM web servers for analysis and reporting. The app is
  mobile-friendly, ensuring you can access your data anytime, anywhere.
  Furthermore, DomainMOD respects your privacy, ensuring only you have access to
  your data.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://domainmod.org/
  - label: Documentation
    url: https://domainmod.org/docs/
  - label: Github
    url: https://github.com/domainmod/domainmod/
contributors:
  - name: Mark Topper
    url: https://github.com/marktopper
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - timezone
  properties:
    projectName:
      type: string
      title: Project
    appServiceName:
      type: string
      title: App Service Name
      default: domainmod
    appServiceImage:
      type: string
      title: App Service Image
      default: domainmod/domainmod
    databaseServiceName:
      type: string
      title: Database Service Name
      default: domainmod-db
    timezone:
      type: string
      title: Timezone
      default: Europe/Copenhagen
