name: Chromium
description: Chromium is an open-source browser project that is designed to
  provide a safer, faster, and more stable way for all users to experience the
  web. This app is a Docker containerized version of Chromium, allowing you to
  deploy and run the Chromium browser in a Docker environment. The app supports
  multiple architectures, including x86-64 and arm64, and can be accessed via
  HTTP or HTTPS. It offers additional environment variables and run
  configurations to enable or disable specific functionality. The app also
  allows you to specify one or multiple Chromium CLI flags, which will be passed
  to the application in full. This containerized version of Chromium is designed
  to function efficiently with modern websites, and includes options for GPU
  acceleration and Docker in Docker (DinD) setup.
instructions: null
changeLog:
  - date: 2022-11-14
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-chromium
  - label: Github
    url: https://github.com/linuxserver/docker-chromium
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: chromium
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/chromium:version-b5a6f5c3
