name: Paperless-ngx
description: Paperless-ngx is a modern document management system designed to
  convert your physical documents into a searchable online archive, helping you
  maintain a clutter-free, paperless environment. It uses advanced OCR
  technology to add selectable text to image-only documents, and allows you to
  organize and index your scanned documents with tags, correspondents, types,
  and more. The app supports a variety of file formats including PDFs, images,
  plain text files, and Office documents. It also features a single-page
  application front end with a dashboard that displays basic statistics and
  allows document upload. With its full-text search functionality, you can
  easily find the documents you need, with results sorted by relevance to your
  search query. The app also includes email processing, enabling it to add
  documents from your email accounts. Moreover, Paperless-ngx is powered by
  machine learning, enabling it to learn from your documents and automatically
  assign tags, correspondents, and types to documents once you've stored a few
  documents in it. It is optimized for multi-core systems, allowing it to
  process multiple documents in parallel.
instructions: Please use the following credentials to login. admin|password
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Documentation
    url: https://paperless-ngx.readthedocs.io/en/latest/
  - label: Github
    url: https://github.com/paperless-ngx/paperless-ngx
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: paperlessngx
    appServiceImage:
      type: string
      title: App Service Image
      default: paperlessngx/paperless-ngx:1.11.3
    redisServiceName:
      type: string
      title: Redis Service Name
      default: paperlessngx-redis
