name: Navidrome
description: Welcome to Navidrome, your personal streaming service! This
  open-source software allows you to access and enjoy your music collection from
  anywhere, through a modern web UI and a wide range of third-party compatible
  mobile apps for both iOS and Android devices. Navidrome is lightweight, fast,
  and self-contained, capable of running well even on resource-limited
  platforms. It can handle large music libraries, and even transcodes your music
  files on the fly to prevent excessive data usage. Built with new technologies
  like GoLang, ReactJS, and Material-UI, Navidrome ensures modern features and
  compatibility. It is also compatible with the de facto standard Music API,
  supporting all its clients and ecosystem. With new releases on a regular
  basis, Navidrome continually adds features and bug fixes to enhance your music
  streaming experience.
instructions: null
changeLog:
  - date: 2023-3-33
    description: first release
links:
  - label: Website
    url: https://www.navidrome.org/
  - label: Documentation
    url: https://www.navidrome.org/docs/
  - label: Github
    url: https://github.com/navidrome/navidrome
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: navidrome
    appServiceImage:
      type: string
      title: App Service Image
      default: deluan/navidrome:0.49.3
