name: Verdaccio
description: Verdaccio is a lightweight, private npm proxy registry built in
  Node.js, designed to simplify and enhance your development workflow. It
  provides a simple, zero-configuration-required local private NPM registry,
  eliminating the need for a full database to get started. Verdaccio comes
  equipped with its own compact database and the capability to proxy other
  registries, such as npmjs.org, while caching the downloaded modules for
  improved efficiency. It allows you to use all the benefits of the npm package
  system in your company without exposing all your code to the public. You can
  link multiple registries, fetch packages from multiple sources in a single
  project, and even publish locally modified versions of third-party packages.
  Verdaccio is compatible with popular npm clients like npm, yarn, and pnpm, and
  supports various plugins for extended storage capabilities.
instructions: null
changeLog:
  - date: 2022-10-31
    description: first release
links:
  - label: Website
    url: https://verdaccio.org/
  - label: Documentation
    url: https://verdaccio.org/docs/what-is-verdaccio
  - label: Github
    url: https://github.com/verdaccio/verdaccio
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: verdaccio
    appServiceImage:
      type: string
      title: App Service Image
      default: verdaccio/verdaccio:5.24.1
