name: Outline Wiki
description: Outline is a team knowledge base and wiki that helps organize your team's information in a structured and searchable manner. It offers an intuitive editing experience with markdown support, slash commands, and rich embeds. You can collaborate on documents in real-time, with comments and threads keeping conversations organized. The platform integrates seamlessly with Slack, allowing you to search and share documents without leaving the chat. Outline also supports public sharing of documents with your own brand colors, logos, and domain. It's designed to be fast, collaborative, and easy to use, with a focus on security and permissions. It also supports multiple languages and offers integrations with tools like Figma, Loom, and more.
instructions: Notice, Auththenication Method is Required to use Outline. To use Other Login Methods, Just fill in dummy Cridentials and edit the env! Check out the Docs https://wiki.generaloutline.com/s/hosting/doc/authentication-7ViKRmRY5o! Notice, Some sort of SMTP is Optinal! Check the env Here https://github.com/outline/outline/blob/main/.env.sample
changeLog:
  - date: 2023-01-15
    description: first release
links:
  - label: Website
    url: https://www.getoutline.com/
  - label: Documentation
    url: https://www.getoutline.com/developers
  - label: Github
    url: https://github.com/outline
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - domainURL
    - googleClient
    - googleClientSecret
    - databaseServiceName
    - redisServiceName
    - minioServiceName

  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: outline
    appServiceImage:
      type: string
      title: App Service Image
      default: outlinewiki/outline:0.67.1
    domainURL:
      type: string
      title: Domain Url
      description: outline.domain.com
    databaseServiceName:
      type: string
      title: Database Service Name
      default: outline-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: outline-redis
    googleClient:
      type: string
      title: Google Client ID
    googleClientSecret:
      type: string
      title: Google Client Secret
    minioServiceName:
      type: string
      title: Minio Service Name
      default: outline-minio
