name: The Lounge
description: "Welcome to The Lounge, your self-hosted web IRC client for the
  21st century. With modern features such as push notifications, link previews,
  and file uploads, The Lounge brings IRC into the modern era. Stay connected to
  IRC servers even when you're offline and resume where you left off on any
  device, thanks to its responsive interface that works smoothly on every
  desktop, smartphone, and tablet. The Lounge supports multiple user accounts,
  allowing you to share your server with friends. It's a free and open-source
  app, licensed under the MIT license, and works on any OS where Node.js runs.
  The Lounge offers two modes: private and public. In private mode, it acts like
  a bouncer and a client combined, offering an experience similar to other
  modern chat applications. In public mode, it acts as an open chat available to
  anyone without registration. Enjoy the convenience of a modern, responsive,
  cross-platform, self-hosted web IRC client with The Lounge."
instructions: To create a user, type thelounge add <name> in the console.
changeLog:
  - date: 2023-07-09
    description: First Release
links:
  - label: Website
    url: https://thelounge.chat/
  - label: Docs
    url: https://thelounge.chat/docs
  - label: GitHub
    url: https://github.com/thelounge
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: thelounge
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/thelounge/thelounge:4
