name: Gogs
description: Gogs is a self-hosted Git service designed to be simple, stable,
  and extensible. It allows you to set up your own Git service in the most
  painless way possible. The app is built with Go, enabling it to run on all
  platforms that Go supports, including Linux, macOS, Windows, and ARM-based
  systems. Gogs is lightweight and has low minimal requirements, making it
  possible to run even on an inexpensive Raspberry Pi. It offers a range of
  features including user dashboard, access to repositories via SSH, HTTP and
  HTTPS protocols, repository and organization management, and more. Gogs is
  100% open source and free of charge, with all source code available under the
  MIT License.
instructions: null
changeLog:
  - date: 2023-3-16
    description: first release
links:
  - label: Website
    url: https://gogs.io/
  - label: Documentation
    url: https://gogs.io/docs
  - label: Github
    url: https://github.com/gogs/gogs
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - sshPort
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gogs
    appServiceImage:
      type: string
      title: App Service Image
      default: gogs/gogs:0.13.0
    sshPort:
      type: number
      title: SSH Port
      default: 2222
