name: SimpleTorrent
description: SimpleTorrent is a self-hosted remote torrent client that allows
  you to manage your torrents remotely. Written in Go (golang), it enables you
  to start torrents remotely and download sets of files on the local disk of the
  server. These files are then retrievable or streamable via HTTP. The app
  offers individual file download control, the ability to run an external
  program on task completion, and a seeding ratio to stop tasks when reached. It
  also provides a download/upload speed limiter and detailed transfer stats in
  the web UI. SimpleTorrent supports real-time updates, is mobile-friendly, and
  offers a fast content server. It also supports IPv6 out of the box and has an
  updated torrent engine from anacrolix/torrent. Additional features include a
  torrent watcher, K8s/docker health-check endpoint, extra trackers from an
  external source, and a protocol handler to magnet.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Documentation
    url: https://github.com/boypt/simple-torrent/wiki
  - label: Github
    url: https://github.com/boypt/simple-torrent
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: simpletorrent
    appServiceImage:
      type: string
      title: App Service Image
      default: boypt/cloud-torrent:1.3.9
