name: Hammond
description: Hammond is a self-hosted vehicle management system designed to
  track fuel and other expenses related to your vehicles. It supports multiple
  users sharing multiple vehicles, making it an ideal solution for families,
  businesses, or any group with shared vehicles. With Hammond, you can manage
  multiple vehicles, track fuel and other expenses, and even save attachments
  against vehicles. The app also features quick entries, allowing you to take a
  photo of a receipt or pump screen for later entry. It provides vehicle-level
  and overall reporting, helping you keep a close eye on your vehicle expenses.
  Furthermore, Hammond allows you to import data from Clarkson or Fuelly, making
  the transition to this system seamless and straightforward.
instructions: null
changeLog:
  - date: 2023-2-21
    description: first release
links:
  - label: Documentation
    url: https://github.com/akhilrex/hammond/tree/master/docs
  - label: Github
    url: https://github.com/akhilrex/hammond
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: hammond
    appServiceImage:
      type: string
      title: App Service Image
      default: akhilrex/hammond:1.0.0
