name: mCaptcha
description: mCaptcha is a proof-of-work based captcha system that prioritizes
  user privacy and offers a fully automated experience. Unlike traditional
  captcha systems, mCaptcha does not track or profile users, ensuring a
  privacy-focused user experience. It is designed to be robust and accurate, not
  relying on IP addresses for rate-limiting, making it suitable for users behind
  NATs. The user experience is silent and seamless, eliminating the need for
  annoying image-based captchas. mCaptcha uses a proof-of-work solution to
  fiercely defend your site, making it more expensive for attackers to target
  your site than for you to respond to their requests. It is a libre software,
  with client libraries licensed under proprietary-friendly free software
  licenses. mCaptcha is also compatible with reCAPTCHA and hCaptcha, making it a
  convenient drop-in replacement. The core functionality of mCaptcha is to use a
  SHA256 based proof-of-work system to rate limit users, providing a token upon
  successful validation that users can then submit with their request or form
  submission to the target website.
instructions: Login with aaronsw:password
changeLog:
  - date: 2023-5-18
    description: first release
links:
  - label: Website
    url: https://mcaptcha.org
  - label: Documentation
    url: https://mcaptcha.org/docs
  - label: Github
    url: https://github.com/mcaptcha/mcaptcha
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mcaptcha
    appServiceImage:
      type: string
      title: App Service Image
      default: mcaptcha/mcaptcha:latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: mcaptcha-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: mcaptcha-redis
