name: Grafana
description: Grafana is a powerful, open-source platform designed to provide
  comprehensive metrics, logs, and trace data visualization. It allows users to
  query, visualize, and alert on their data, offering high-scale distributed
  tracing and scalable, performant metrics. The app also includes features for
  incident response and management, performance testing, and on-call management.
  Grafana can connect to various data sources and applications, providing
  operational dashboards for your data anywhere. It also offers a free forever
  plan, allowing users to monitor their data with 10,000 series metrics, 50 GB
  of logs, 50 GB of traces, and 500 VUh of k6 testing. Grafana is a versatile
  tool for anyone looking to gain insights from their data.
instructions: Login with admin:admin
changeLog:
  - date: 2023-3-15
    description: first release
links:
  - label: Website
    url: https://grafana.com
  - label: Documentation
    url: https://grafana.com/docs
  - label: Github
    url: https://github.com/grafana/grafana
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: grafana
    appServiceImage:
      type: string
      title: App Service Image
      default: grafana/grafana-oss:9.5.1
