name: Ploi Roadmap
description: Roadmap is an open-source software designed to streamline your
  roadmapping process. It offers a completely customizable platform where you
  can mention users in comments, upvote items to prioritize them, and generate
  automatic slugs. The software also features a Filament admin panel and a
  simplified role system that includes administrator, employee, and user roles.
  Roadmap supports OAuth 2 single sign-on with your own application and
  automatically generates OG images, including the branding color you've set up.
  It also integrates with GitHub, allowing you to assign a repository to each
  project and manage issues directly from the roadmap admin. The software is
  built with PHP and requires a database to function.
instructions: After First Deployment, run "php artisan roadmap:install" to setup
  the inital user account.
changeLog:
  - date: 2023-1-6
    description: first release
  - date: 2023-01-27
    description: Package and Image Fix
links:
  - label: Github
    url: https://github.com/ploi-deploy/roadmap
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Mxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - adminNotifications
    - appLanguage
    - appTimezone
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ploi-roadmap
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/easypanel-community/docker-ploi-roadmap:1.43
    databaseServiceName:
      type: string
      title: Database Service Name
      default: ploi-roadmap-db
    adminNotifications:
      type: boolean
      title: Admin Notifications
      default: true
    appLanguage:
      type: string
      title: Language
      default: en
    appTimezone:
      type: string
      title: Timezone
      default: utc
