name: Statping-ng
description: Statping is a web and app status monitoring tool designed for any
  type of project. It automatically fetches your application and generates a
  beautiful, feature-rich status page. This status page generator supports
  MySQL, Postgres, or SQLite on multiple operating systems, ensuring
  future-proof and resilient monitoring. If your server crashes, your Statping
  service will remain online to notify your users of downtime. Lightweight and
  fast, Statping is available for Linux, Mac, and Windows, and even on a
  Raspberry Pi. The mobile app, available on the App Store and Google Play,
  allows you to view services, receive notifications when a service is offline,
  and manage groups, users, services, and messages. Statping can run on any
  server, from Docker to AWS EC2, and offers custom SASS styling for complete
  customization of your status page. It includes email notification via SMTP and
  Slack integration, and allows you to create your own plugins to interact with
  every element of your status page. With its easy-to-use dashboard, you can
  monitor your websites and applications with a basic HTTP GET request or a POST
  request with your own JSON.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://github.com/statping/statping
  - label: Documentation
    url: https://github.com/statping/statping
  - label: Github
    url: https://github.com/statping/statping
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: statping-ng
    appServiceImage:
      type: string
      title: App Service Image
      default: adamboutcher/statping-ng:v0.90.78
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: statping-ng-db
