name: Lychee
description: Lychee is a free, self-hosted photo-management tool designed to
  make managing your photos a breeze. It allows you to upload, move, rename,
  describe, delete, and search your photos all in one place, right from your
  browser. With Lychee, you can easily share your photos and albums with just
  one click, and even protect them with passwords for added security. The app
  also allows you to view your images in full-screen mode, navigate using your
  keyboard, and make your photos public for others to enjoy. Lychee supports
  batch editing with desktop-like multi-select and displays your EXIF and IPTC
  Metadata. You can import your photos from various sources, tag them, or mark
  them as important. Lychee is designed with a beautiful, intuitive interface
  and is perfect for photographers as it offers unlimited storage, no
  compression, and no loss in data.
instructions: Lychee takes a few minutes to get ready. Sit back, relax, and have a coffee!
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Website
    url: https://lycheeorg.github.io/
  - label: Documentation
    url: https://lycheeorg.github.io/docs/
  - label: Github
    url: https://github.com/LycheeOrg/Lychee
  - label: Demo
    url: https://lycheeorg.github.io/demo/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: lychee
    appServiceImage:
      type: string
      title: App Service Image
      default: lycheeorg/lychee:v4.7.4
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
