name: HedgeDoc
description: HedgeDoc, previously known as CodiMD, is an open-source, web-based,
  self-hosted, collaborative markdown editor. It allows you to collaborate on
  notes, graphs, and presentations in real-time. Simply share your note-link
  with your co-workers and they can join in the collaboration. The editor runs
  directly in your browser, allowing you to stay in control of your data by
  keeping it on your server. HedgeDoc also offers a presentation mode for
  building and presenting slides in markdown, and supports a variety of graphs,
  diagrams, and embedded content. It features an easy-to-use permission system
  for managing note permissions, and keeps track of changes to your notes
  through revisions, even allowing you to revert to older versions. Despite its
  extensive features, HedgeDoc has low system requirements and can run smoothly
  even on a Raspberry Pi.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
  - date: 2023-2-24
    description: Update to v1.9.7
  - date: 2023-07-11
    description: Update to v1.9.8 and return to main image
links:
  - label: Website
    url: https://hedgedoc.org/
  - label: Documentation
    url: https://docs.hedgedoc.org/
  - label: Github
    url: https://git.hedgedoc.org/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: hedgedoc
    appServiceImage:
      type: string
      title: App Service Image
      default: quay.io/hedgedoc/hedgedoc:1.9.8
    databaseServiceName:
      type: string
      title: Database Service Name
      default: hedgedoc-db
