name: ICEcoder
description: ICEcoder is a revolutionary browser-based code editor designed to
  streamline and modernize the process of website development. It allows you to
  code directly within your web browser, either online or offline, eliminating
  the need for multiple programs. With ICEcoder, you can test your sites on
  actual web servers and maintain them with ease after development, making for a
  fast and intelligent development process. It's not just limited to online use
  - you can also use it as a desktop code editor, provided you have PHP 7.0+. It
  comes packed with a multitude of features and plugins to enhance your coding
  experience, including multiple cursors, 80+ highlighting themes, a find &
  replace builder, login security, coding assistance, visual code difference
  display, and database management with the Adminer plugin. The latest version,
  ICEcoder 8.1, introduces regex search on find and replace, double click tab to
  collapse file manager, active line number highlighting, and many more
  improvements and bug fixes.
instructions: null
armSupport: true
changeLog:
  - date: 2023-2-19
    description: first release
links:
  - label: Website
    url: https://icecoder.net
  - label: Documentation
    url: https://icecoder.net/manual
  - label: Github
    url: https://github.com/icecoder/ICEcoder
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: icecoder
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/easypanel-community/docker-icecoder:8.1
