name: Odoo
description: Odoo is a comprehensive, integrated software platform designed to
  streamline and automate your business operations. It offers a suite of
  open-source business applications that cover all your company needs, from
  sales and services integration to operations management, website building,
  financial management, and marketing. Odoo's unique value proposition lies in
  its ease of use and full integration. The apps are designed to work seamlessly
  together, allowing you to automate and track everything you do in a
  centralized, online platform accessible from anywhere with any device. With
  Odoo, you can replace multiple applications with a single, cost-effective, and
  modular solution, eliminating the need for painful integrations and providing
  a comprehensive overview of your business. The platform evolves much faster
  than other solutions, with regular annual releases leveraging the expertise of
  thousands of developers and business experts. Whether you need a CRM,
  eCommerce, accounting, inventory, project management, or any other business
  application, Odoo has got you covered.
instructions: You can login with username "admin" and password "umami".
changeLog:
  - date: 2023
    description: first release
links:
  - label: Website
    url: https://www.odoo.com
  - label: Github
    url: https://github.com/odoo/odoo
  - label: Documentation
    url: https://www.odoo.com/page/docs
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: odoo
    appServiceImage:
      type: string
      title: App Service Image
      default: odoo:16.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: odoo-db
