name: Roundcube
description: Roundcube webmail is a browser-based, multilingual IMAP client that
  offers an application-like user interface. It is designed to provide all the
  functionalities you would expect from an email client. This includes MIME
  support, an address book, folder manipulation, message searching, and spell
  checking. The app also supports drag-and-drop message management, multiple
  sender identities, and a full-featured address book with groups and LDAP
  connectors. It offers a threaded message listing, IDNA and SMTPUTF8 support,
  and a responsive skin for multi-device support. Roundcube webmail also
  features built-in caching for fast mailbox access, unlimited users and
  messages, import/export functions, and support for PGP encryption.
instructions: After Roundcube is installed, you can log in to the mail accounts
  on the service where you entered the "SMTP" information.
changeLog:
  - date: 2023-03-15
    description: First Release
links:
  - label: Website
    url: https://roundcube.net/
  - label: Github
    url: https://github.com/roundcube/roundcubemail/
  - label: Docker
    url: https://hub.docker.com/r/roundcube/roundcubemail/
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - roundcubeDefaultHost
    - roundcubeSmtpServer
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: roundcube
    appServiceImage:
      type: string
      title: App Service Image
      default: roundcube/roundcubemail:1.5.3-apache
    roundcubeDefaultHost:
      type: string
      title: Default Host
      description: Hostname of the IMAP server to connect to. For encypted
        connections, prefix the host with tls:// (STARTTLS) or ssl:// (SSL/TLS).
    roundcubeDefaultPort:
      type: number
      title: Default Port
      description: IMAP port number.
      default: 143
    roundcubeSmtpServer:
      type: string
      title: SMTP Server
      description: Hostname of the SMTP server to send mails. For encypted
        connections, prefix the host with tls:// (STARTTLS) or ssl:// (SSL/TLS).
    roundcubeSmtpPort:
      type: number
      title: SMTP Port
      description: SMTP port number.
      default: 587
    roundcubePlugins:
      type: string
      title: Plugins
      description: List of built-in plugins to activate.
      default: archive,zipdownload
    roundcubeUploadMaxFilesize:
      type: string
      title: Upload Max File Size
      description: File upload size limit.
      default: 5M
