name: Papercups
description: Papercups is a privacy-focused, open-source app designed to
  streamline communication with your customers. It provides a powerful dashboard
  to coordinate and reply to messages over various platforms including chat,
  email, Slack, and SMS. The app offers a customizable widget that you can
  tailor to your brand's aesthetics, without the need for any coding. Papercups
  also integrates seamlessly with your existing work environment, eliminating
  the need to log in to another dashboard. It supports HTML, React, React
  Native, and Flutter integrations. The app is built with Elixir on top of BEAM
  for incredible scalability, making it a suitable choice for businesses of all
  sizes. It also offers personalized support, managing your deployment on your
  infrastructure while providing the benefits of self-hosting with the
  reliability and scalability of the cloud.
instructions: null
changeLog:
  - date: 2023-3-20
    description: first release
links:
  - label: Website
    url: https://papercups.io
  - label: Documentation
    url: https://docs.papercups.io/
  - label: Github
    url: https://github.com/papercups-io/papercups
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: papercups
    appServiceImage:
      type: string
      title: App Service Image
      default: papercups/papercups:1.1.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: papercups-db
