name: SearXNG
description: SearXNG is a powerful, privacy-focused metasearch engine that
  aggregates results from over 70 search services, ensuring your searches remain
  private and untracked. It offers secure, encrypted connections and the option
  to use it over Tor for enhanced online anonymity. With about 130 integrated
  search engines and 60 translations, SearXNG provides a comprehensive and
  versatile search experience. The app also offers easy integration of search
  engines and maintains high standards of professional development, including
  continuous integration, quality assurance, and automated UI testing. SearXNG
  was launched in 2021 as a fork of the searx project, and it continues to
  evolve with user-friendly features and improvements.
instructions: null
changeLog:
  - date: 2023-03-30
    description: First Release
links:
  - label: Docs
    url: https://docs.searxng.org/
  - label: Github
    url: https://github.com/searxng/searxng
  - label: Docker
    url: https://hub.docker.com/r/searxng/searxng
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    enableRedis:
      type: boolean
      title: Enable Redis
    appServiceName:
      type: string
      title: App Service Name
      default: searxng
    appServiceImage:
      type: string
      title: App Service Image
      default: searxng/searxng:latest
