name: Mealie
description: Mealie is a self-hosted recipe manager and meal planner designed to
  provide a pleasant user experience for the whole family. It features a RestAPI
  backend and a reactive frontend application built in Vue. With Mealie, you can
  quickly and easily import recipes from various websites using the built-in
  recipe scraper. The app ensures the safety of your data with automatic backups
  in any format supported by Jinja2 templates. It offers a rich and intuitive
  user interface that allows you to create, edit, and delete recipes with ease.
  The recipe editor supports markdown syntax for added convenience. Mealie also
  enables you to create meal plans for the week, month, or year. You can add new
  users, sort them into groups to share recipes and meal plans, and schedule
  webhooks to send notifications to 3rd party services with today's meal plan
  data. The open API gives you full control of the backend server with
  interactive documentation.
instructions: Please use the following credentials to login. changeme@easypanel.io|MyPassword
changeLog:
  - date: 2022-12-11
    description: first release
links:
  - label: Documentation
    url: https://nightly.mealie.io/
  - label: Github
    url: https://github.com/hay-kot/mealie/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mealie
    appServiceImage:
      type: string
      title: App Service Image
      default: hkotel/mealie:v0.5.6
