name: Mastodon
description: Mastodon is a unique social networking app that puts control back
  in your hands. It allows you to curate your own home feed, free from
  algorithms or ads, ensuring you see only what matters most to you. The app
  supports a wide range of content types, including audio, video, and picture
  posts, polls, content warnings, and more, enabling you to express yourself
  freely online. Mastodon is decentralized and open-source, meaning each server
  is a completely independent entity, yet able to interoperate with others to
  form a global social network. The app respects your agency, never serving ads
  or pushing profiles, and is built on open web protocols, allowing it to
  interact with any other platform that implements ActivityPub. With Mastodon,
  you have the power to manage your audience, moderate content, and create a
  social media experience that truly reflects you.
instructions: To create an admin account, type "tootctl accounts create username
  --email user@example.com --confirmed --role Owner" on the console.
changeLog:
  - date: 2023-03-26
    description: First Release
links:
  - label: Website
    url: https://joinmastodon.org
  - label: Docs
    url: https://docs.joinmastodon.org
  - label: Github
    url: https://github.com/mastodon/mastodon
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    enableStreaming:
      type: boolean
      title: Enable Streaming Service
      default: false
    smtpServer:
      type: string
      title: SMTP Server
    smtpPort:
      type: number
      title: SMTP Port
      default: 587
    smtpLogin:
      type: string
      title: SMTP Login
    smtpPassword:
      type: string
      title: SMTP Password
    smtpFromAddress:
      type: string
      title: SMTP From Address
      default: notifications@example.com
    appServiceName:
      type: string
      title: App Service Name
      default: mastodon
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/mastodon/mastodon:v4.1
