name: Corteza
description: Corteza is a powerful, open-source low-code platform designed to
  streamline the process of app development, business process integration, and
  data harmonization. Built with a backend in Golang and a front end in Vue.js,
  Corteza allows you to easily build native web apps and expand your software
  ecosystem with complete control and flexibility. You can connect with any
  record data source, control everything you build, transform your data into a
  standardized JSON format, and build unlimited web applications and process
  workflows using block-based tools and Javascript automations. Corteza is
  cloud-native and deploys via Docker containers, providing a seamless and
  efficient app development experience. It is 100% free and open-source,
  ensuring that it will always be accessible to all.
instructions: Create an account to login. The first account created will have
  administrator priviledges. Go to /admin for the admijnistration interface
changeLog:
  - date: 2023-3-2
    description: first release
links:
  - label: Website
    url: https://cortezaproject.org
  - label: Documentation
    url: https://docs.cortezaproject.org
  - label: Github
    url: https://github.com/cortezaproject/corteza
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: corteza
    appServiceImage:
      type: string
      title: App Service Image
      default: cortezaproject/corteza:2022.9.8
    databaseServiceName:
      type: string
      title: Database Service Name
      default: corteza-db
