name: Home Assistant
description: Home Assistant is an open-source home automation app that
  prioritizes local control and privacy. It allows you to manage and automate a
  wide range of devices and services in your home, from electricity grids and
  solar panels to voice-controlled devices. With its advanced configuration
  options, you can customize your home automation to suit your needs. It also
  offers features like multi-factor authentication for added security. Home
  Assistant is perfect to run on a Raspberry Pi or a local server, providing a
  comprehensive solution for your home automation needs.
instructions: null
changeLog:
  - date: 2022-11-21
    description: first release
links:
  - label: Documentation
    url: https://www.home-assistant.io/docs/
  - label: Github
    url: https://github.com/home-assistant
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: homeassistant
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/homeassistant:latest
