name: Freshrss
description: FreshRSS is a free, self-hostable aggregator for RSS feeds. It
  allows you to gather and read your favorite news sources in one place,
  providing a streamlined and efficient way to stay informed. The app supports
  multiple platforms and can be easily accessed through a web user interface.
  FreshRSS also offers the ability to use external databases, enabling users to
  create a user and database in their MySQL/MariaDB server. Additional
  extensions can be added to enhance the functionality of the app. FreshRSS is
  designed to be simple to use, yet powerful, providing a comprehensive solution
  for RSS feed aggregation.
instructions: null
changeLog:
  - date: 2022-11-14
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-freshrss
  - label: Github
    url: https://github.com/linuxserver/docker-freshrss
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: freshrss
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/freshrss:latest
