name: YAO
description: YAO is a powerful open-source app engine designed to create web
  services and applications in a matter of minutes. It is versatile and suitable
  for a variety of use-cases including AI, IoT, Industrial Internet, Connected
  Vehicles, DevOps, Energy, and Finance. With YAO, you can create a database
  model, write an interface, and describe the interface using JSON, making it a
  truly codeless programming experience. It supports running on ARM devices and
  can be used in IoT, edge computing, and industrial internet. YAO also offers
  easy-to-use Business Intelligence components and functions, empowering
  businesses with more possibilities. It has many built-in processes and
  supports data processing in any form through data flow. The app also features
  a plug-in mechanism based on GRPC for function expansion using Nodejs, Python,
  and other languages. YAO also provides a built-in query engine and offers
  enterprise-level security with permission classification, separation of
  administrator and employee accounts, and API level permission control.
instructions: Use xiang@iqka.com:A123456p+ to login at /xiang/login/admin . Use
  amd64 instead of arm64 if you use a non ARM based system.
changeLog:
  - date: 2023-3-14
    description: first release
links:
  - label: Website
    url: https://yaoapps.com/
  - label: Documentation
    url: https://yaoapps.com/en-US/doc/
  - label: Github
    url: https://github.com/YaoApp/yao
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: yao
    appServiceImage:
      type: string
      title: App Service Image
      default: yaoapp/yao:0.10.3-arm64
    databaseServiceName:
      type: string
      title: Database Service Name
      default: yao-db
