name: OctoPrint
description: OctoPrint is a comprehensive web interface designed to provide full
  remote control and monitoring of your 3D printer. It allows you to manage
  every aspect of your 3D printing jobs directly from your browser. With
  OctoPrint, you can access the embedded webcam feed to watch your printer in
  action, receive constant feedback on the progress of your print job, and even
  view a rendition of the GCODE you are currently printing. The app also enables
  you to monitor and adjust the temperatures of your hotends and print bed on
  the fly, move the print head along all axes, and start, stop, or pause your
  print job at any time. OctoPrint is compatible with most consumer 3D printers
  and its powerful plugin system allows for functionality extension. It is 100%
  open source, allowing everyone to modify it to their own needs. Additional
  features include creating timelapse recordings of your prints, slicing your
  STL files directly within the app, built-in access controls, and the ability
  to add system commands to the menu for easy shutdown or reboot of your
  OctoPrint server or printer.
instructions: null
changeLog:
  - date: 2023-07-11
    description: First Release
links:
  - label: Website
    url: https://octoprint.org
  - label: Docs
    url: https://docs.octoprint.org
  - label: Github
    url: https://github.com/OctoPrint/OctoPrint
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    enableMjpgStreamer:
      type: boolean
      title: Enable MJPG Streamer
      default: false
    appServiceName:
      type: string
      title: App Service Name
      default: octoprint
    appServiceImage:
      type: string
      title: App Service Image
      default: octoprint/octoprint:1.9
