name: Kanboard
description: Kanboard is a free and open-source project management software that
  utilizes the Kanban methodology. It provides a visual and clear overview of
  your tasks, allowing you to easily manage your projects by dragging and
  dropping tasks between columns. The app is designed with simplicity and
  minimalism in mind, limiting the number of features to maintain focus on your
  work. It also includes a search and filter function, enabling you to quickly
  find tasks using a simple query language. Tasks can be broken down into
  sub-tasks, with the ability to add comments, documents, and change various
  aspects such as color, category, assignee, and due date. Kanboard also offers
  automated actions to streamline your workflow, eliminating the need for
  repetitive manual tasks. It supports multiple authentication backends and is
  translated in over 30 languages.
instructions: null
changeLog:
  - date: 2022-08-16
    description: first release
links:
  - label: Website
    url: https://kanboard.org/
  - label: Documentation
    url: https://docs.kanboard.org/en/latest/
  - label: Github
    url: https://github.com/kanboard/kanboard
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: kanboard
    appServiceImage:
      type: string
      title: App Service Image
      default: kanboard/kanboard:v1.2.28
