name: Matomo
description: Matomo is a powerful web analytics platform that allows you to take
  full control of your data. As a leading global web analytics solution, it is
  trusted on over 1 million websites across more than 190 countries. Matomo
  provides an ethical alternative to other analytics platforms, ensuring the
  protection of your data and your customers' privacy. With Matomo, you have
  100% data ownership, meaning you know exactly where your data is stored and
  what's happening to it. The platform offers a comprehensive range of features
  that provide actionable insights and a complete picture of your customers. It
  allows you to securely track personal data in accordance with privacy laws,
  and offers 100% accurate reporting for impactful decision-making. Matomo can
  be customised and extended to meet your every need, and it comes with no data
  limitations, allowing for an unlimited number of websites, users, and
  segments.
instructions: null
changeLog:
  - date: 2022-09-28
    description: first release
links:
  - label: Website
    url: https://matomo.org/
  - label: Documentation
    url: https://matomo.org/guide/installation-maintenance/matomo-on-premise-self-hosted/
  - label: Github
    url: https://github.com/matomo-org/matomo
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: matomo
    appServiceImage:
      type: string
      title: App Service Image
      default: matomo:4.12.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: matomo-db
