name: Gotify
description: Gotify is a simple, self-hosted server for sending and receiving
  messages. It is designed with a user-friendly interface and a straightforward
  API, making it easy to use across different platforms. The core of Gotify is
  the server, which features a WebUI and functionality for sending messages via
  a REST-API, subscribing/receiving messages via a web socket connection, and
  managing users, clients, and applications. Gotify also includes an Android
  client for subscribing to the message stream of the server, creating push
  notifications for newly received messages. Additionally, there is a command
  line client for pushing messages to the server. All these features make Gotify
  a versatile tool for managing and exchanging messages while maintaining
  control over your data.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-2-24
    description: Update to v2.2.4
links:
  - label: Website
    url: https://gotify.net/
  - label: Documentation
    url: https://gotify.net/docs/
  - label: Github
    url: https://github.com/gotify
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gotify
    appServiceImage:
      type: string
      title: App Service Image
      default: gotify/server:2.2.4
    password:
      type: string
      title: Password
    serviceTimezone:
      type: string
      title: Timezone
      default: Europe/London
