name: Nextcloud
description: "Nextcloud Hub 5 is a comprehensive platform that integrates the
  four key Nextcloud products: Files, Talk, Groupware, and Office. It is
  designed to optimize the flow of collaboration, providing a seamless
  experience for users. Nextcloud Files offers an on-premise Universal File
  Access and sync platform with powerful collaboration capabilities and
  interfaces for desktop, mobile, and web. The platform ensures no data leaks to
  third parties, providing you with full control over your data. It is
  customizable, scalable, and can be deployed on-premises or in the cloud.
  Nextcloud is committed to providing technology that fits perfectly with your
  organization, whether it's a government entity, enterprise, service provider,
  or educational institution. It is the most popular self-hosted collaboration
  solution, used by tens of millions of users at thousands of organizations
  across the globe."
instructions: null
changeLog:
  - date: 2022-07-22
    description: first release
links:
  - label: Website
    url: https://nextcloud.com/
  - label: Documentation
    url: https://docs.nextcloud.com/
  - label: Github
    url: https://github.com/nextcloud
contributors:
  - name: Raul Bedeoan
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nextcloud
    appServiceImage:
      type: string
      title: App Service Image
      default: nextcloud:24.0.6
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nextcloud-db
