name: Logseq
description: Logseq is a powerful tool designed to enhance your note-taking and
  task management experience. It allows you to connect your notes, increasing
  your understanding and productivity. With features like PDF Annotations,
  Flashcards, and Whiteboards, it caters to a wide range of users including
  students, academics, writers, project managers, and developers. Logseq helps
  you capture, structure, and review your class notes with ease using the Linked
  References, Queries, and Search features. It also aids in memorizing facts and
  insights using the Flashcards feature. You can organize your thoughts and
  ideas, and quickly turn them into outlines using Block References. The app
  also offers tips and tricks to improve your note-taking skills, whether you're
  a beginner, intermediate, or expert. With Logseq, you can create your own
  processes, generate tables of relevant information, and always find what
  you're looking for. It also helps you stay on top of your relationships,
  conversations, and meetings, making it a safe space for your thoughts. Logseq
  is designed to store your interests, questions, ideas, favorite quotes,
  reminders, reading and meeting notes easily and future-proof. It also offers
  real-time, encrypted file syncing so you'll always have your notes backed up
  and securely available on any device. The Whiteboards feature provides a new
  canvas for your thoughts, allowing you to connect, associate and understand in
  new ways.
instructions: null
changeLog:
  - date: 2023-5-23
    description: first release
links:
  - label: Website
    url: https://logseq.com
  - label: Documentation
    url: https://docs.logseq.com
  - label: Github
    url: https://github.com/logseq/logseq
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: logseq
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/logseq/logseq-webapp
