name: Deluge
description: Deluge is a comprehensive BitTorrent client designed to cater to
  your torrenting needs. It operates on a daemon/client model and is equipped
  with various user interfaces, including GTK-UI, Web-UI, and Console-UI. At its
  core, Deluge uses libtorrent to efficiently manage the BitTorrent protocol.
  The app allows you to start various user-interfaces and the Deluge daemon with
  simple commands. It also provides a web UI that can be accessed at
  http://localhost:8112 with the default password 'deluge'. For advanced users,
  Deluge offers features like bandwidth tweaking, VPN, and reverse proxy.
instructions: null
changeLog:
  - date: 2023-1-25
    description: first release
links:
  - label: Documentation
    url: http://dev.deluge-torrent.org/wiki/UserGuide
  - label: Github
    url: https://github.com/deluge-torrent/deluge
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: deluge
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/deluge:2.1.1
