name: Prowlarr
description: Prowlarr is a powerful indexer manager and proxy designed to
  integrate with various PVR applications. It is built on the popular arr
  .net/reactjs base stack, offering a seamless experience for users. Prowlarr
  supports the management of both Torrent Trackers and Usenet Indexers,
  eliminating the need for per app Indexer setup. It works in harmony with
  LazyLibrarian, Lidarr, Mylar3, Radarr, Readarr, and Sonarr, providing
  comprehensive management of your indexers. The app includes features such as
  Usenet support for 24 indexers natively, Torrent support for over 500
  trackers, support for custom YML definitions, Indexer Sync to various apps,
  manual searching of Trackers & Indexers, and much more. Prowlarr also provides
  Indexer health and status notifications and supports multiple releases pushing
  directly to your download clients.
instructions: null
changeLog:
  - date: 2022-12-26
    description: first release
links:
  - label: Website
    url: https://prowlarr.com/
  - label: Documentation
    url: https://wiki.servarr.com/prowlarr
  - label: Github
    url: https://github.com/Prowlarr/Prowlarr/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: prowlarr
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/prowlarr
