name: Thumbor
description: Thumbor is an intelligent imaging service designed to streamline
  and enhance your image processing tasks. It offers on-demand cropping,
  resizing, and flipping of images, ensuring the most important parts of your
  pictures are always preserved. Leveraging advanced face and feature detection
  algorithms, Thumbor smartly identifies key points in an image for optimal
  cropping and resizing. It also supports a variety of image filters for
  post-processing, which can be applied in a sequence for desired effects.
  Filters include brightness, contrast, grayscale, red-eye, and blur, among
  others. Thumbor also supports the WebP format, a superior image format that
  compresses better than jpeg and png, improving your website's performance.
  With Thumbor, you can store and load images from any location, and it's easy
  to implement a new loader or storage. It's a complete solution for your
  imaging needs, from uploading images to rendering them with smart
  face-recognition cropping.
instructions: null
changeLog:
  - date: 2023-07-10
    description: First Release
links:
  - label: Website
    url: https://www.thumbor.org
  - label: Documentation
    url: https://thumbor.readthedocs.io
  - label: Github
    url: https://github.com/thumbor/thumbor
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: thumbor
    appServiceImage:
      type: string
      title: App Service Image
      default: thumbororg/thumbor:latest
