name: Chatwoot
description: Chatwoot is a new age multi-channel customer experience platform
  designed for businesses of all sizes. It serves as an open-source customer
  engagement suite, providing an alternative to platforms like Intercom,
  Zendesk, and Salesforce Service Cloud. With Chatwoot, you can manage your
  agents' workload, track their performance through auto-updating reports, and
  work smarter with automations. The app allows you to perform key actions on
  multiple conversations at once and provides super quick responses to customer
  conversations, making your agents super productive. It also offers features to
  manage your email, Facebook, Instagram, Line, SMS, Telegram, and Twitter
  customer interactions directly from the platform. Additionally, Chatwoot
  provides detailed insights into your conversations and allows you to measure
  and track your CSAT score on autopilot.
instructions: null
changeLog:
  - date: 2023-1-22
    description: first release
links:
  - label: Documentation
    url: https://www.chatwoot.com/help-center
  - label: Github
    url: https://github.com/chatwoot/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - defaultLocale
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    defaultLocale:
      type: string
      title: Default Locale
      default: en
    appServiceName:
      type: string
      title: App Service Name
      default: chatwoot
    appServiceImage:
      type: string
      title: App Service Image
      default: chatwoot/chatwoot:v2.17.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: chatwoot-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: chatwoot-redis
