name: Activepieces
description: Activepieces is a powerful open-source business automation tool
  designed to streamline your work without the need for coding. It serves as an
  excellent alternative to Zapier, allowing you to automate your daily tasks or
  even your entire business with just a few clicks on the user interface. With
  Activepieces, you can enjoy the flexibility of using our 3rd party no-code
  apps to quickly read and write to your favorite apps. Currently, we support 74
  apps and counting. The tool is self-hosted, ensuring your data remains on your
  machine, providing an added layer of security. Activepieces also offers
  infinite flexibility and powerful logging, making it a robust solution for
  business automation without limits.
instructions: null
changeLog:
  - date: 2023-2-27
    description: first release
  - date: 2023-3-16
    description: Fixed startup, added domain properties and version bump to 0.3.6
  - date: 2023-4-6
    description: Various error corrections were made and version was upgraded to 0.3.9.
  - date: 2023-5-02
    description: Fixed executing flow, and version bumped to 0.3.13
  - date: 2023-6-03
    description: Version bumped to 0.3.15
links:
  - label: Website
    url: https://activepieces.com
  - label: Documentation
    url: https://activepieces.com/docs
  - label: Github
    url: https://github.com/activepieces/activepieces
contributors:
  - name: abuaboud
    url: https://github.com/abuaboud
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: activepieces
    appServiceImage:
      type: string
      title: App Service Image
      default: activepieces/activepieces:0.3.15
    databaseServiceName:
      type: string
      title: Database Service Name
      default: activepieces-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: activepieces-redis
