name: phpMyAdmin
description: phpMyAdmin is a free software tool designed to manage MySQL over
  the web. This powerful tool supports a broad spectrum of operations on MySQL
  and MariaDB. It allows you to perform frequently used operations such as
  managing databases, tables, columns, relations, indexes, users, permissions,
  and more through its user-friendly interface. Additionally, it provides the
  flexibility to directly execute any SQL statement. phpMyAdmin also features an
  intuitive web interface and supports most MySQL features. You can browse and
  drop databases, tables, views, fields, and indexes; create, copy, drop,
  rename, and alter databases, tables, fields, and indexes; manage MySQL user
  accounts and privileges; and much more. It also allows you to import data from
  CSV and SQL, export data to various formats, administer multiple servers,
  create graphics of your database layout in various formats, and create complex
  queries using Query-by-example (QBE).
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.phpmyadmin.net/
  - label: Documentation
    url: https://www.phpmyadmin.net/docs/
  - label: Github
    url: https://github.com/phpmyadmin/phpmyadmin
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: phpmyadmin
    appServiceImage:
      type: string
      title: App Service Image
      default: phpmyadmin:5.2.0
