name: phpMyAdmin
description: phpMyAdmin is a free software tool written in PHP, intended to
  handle the administration of MySQL over the Web. phpMyAdmin supports a wide
  range of operations on MySQL and MariaDB.
instructions:
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.phpmyadmin.net/
  - label: Documentation
    url: https://www.phpmyadmin.net/docs/
  - label: Github
    url: https://github.com/phpmyadmin/phpmyadmin
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - serviceName
    - domain
  properties:
    projectName:
      type: string
      title: Project Name
    serviceName:
      type: string
      title: Service Name
      default: phpmyadmin
    domain:
      type: string
      title: Domain
