name: Mattermost
description: Mattermost is a secure collaboration platform designed to enhance
  the efficiency and productivity of technical and operational teams. It offers
  a range of features including team messaging, custom integrations, audio and
  screen sharing, and workflow automation. Mattermost is designed to improve
  time to response by 90%, decrease incident resolution time, and increase
  information availability by executing complex workflows faster and at a higher
  quality. It also helps in avoiding costly outages and downtime by decreasing
  the frequency and severity of system failures. The platform is built for
  enterprise scalability and can be deployed in air gapped networks and BYOD
  environments. It is also cloud neutral and offers self-host deployment
  options. Mattermost is open source and can be customized to fit your workflow
  with robust integrations or by building your own with its App Framework,
  Plugins, and open APIs.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2022-10-12
    description: ablity to define custom docker image version
  - date: 2022-11-29
    description: Update mattermost to 7.5.1
  - date: 2023-1-26
    description: Update mattermost to 7.7
links:
  - label: Website
    url: https://mattermost.com/
  - label: Github
    url: https://github.com/mattermost/
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Peter Fodor
    url: https://github.com/fodurrr
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mattermost
    appServiceImage:
      type: string
      title: App Service Image
      default: mattermost/mattermost-team-edition:7.10
    databaseServiceName:
      type: string
      title: Database Service Name
      default: mattermost-db
