name: Commento++
description: Commento++ is a free, open-source application designed to provide a
  fast, lightweight comments box that you can embed in your static website. It
  offers a range of features including Markdown support, Disqus import, voting,
  automated spam detection, moderation tools, sticky comments, thread locking,
  and OAuth login. It also supports hot-reloading of comments and email
  notifications. Commento++ is designed to respect your privacy, with no
  adverts, and offers a more attractive comments box compared to other free and
  open-source alternatives. It is significantly lighter and faster than
  alternatives and can be deployed with a single click to a free Heroku account.
  For maximum control, you can also choose to self-host the application.
instructions: null
changeLog:
  - date: 2023-3-25
    description: first release
links:
  - label: Github
    url: https://github.com/souramoo/commentoplusplus
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: commentoplusplus
    appServiceImage:
      type: string
      title: App Service Image
      default: caroga/commentoplusplus:v1.8.7
    databaseServiceName:
      type: string
      title: Database Service Name
      default: commentoplusplus-db
