name: Baserow
description: Baserow is an open-source, no-code database tool that allows you to
  create your own online database without any technical experience. It is a
  user-friendly alternative to Airtable, offering the power of a developer right
  from your browser. Baserow is perfect for organizing your projects, ideas, or
  business processes, allowing you to structure everything according to your
  needs. It is a flexible software that can be tailored to your needs, ensuring
  clear and accessible data for all your team members. With Baserow, you can
  easily integrate with other software, collaborate in real-time, and enjoy
  unlimited rows for your data. It is also developer-friendly, allowing for the
  creation of custom plugins. Baserow offers a free plan for those who want to
  try it out, as well as premium and advanced plans for users with more advanced
  needs.
instructions: It may take several minutes for Baserow to boot up.
changeLog:
  - date: 2022-10-05
    description: First Release
  - date: 2023-07-07
    description: Version update and external redis and database support
links:
  - label: Website
    url: https://baserow.io/
  - label: Gitlab
    url: https://gitlab.com/bramw/baserow
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: baserow
    appServiceImage:
      type: string
      title: App Service Image
      default: baserow/baserow:1.18.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: baserow-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: baserow-redis
