name: Metabase
description: Metabase is a powerful, user-friendly application designed to
  enable your company to explore data independently. It offers fast analytics
  with integrated tooling and a friendly user interface. With Metabase, you can
  go from zero to dashboard in just 2 minutes, allowing you to connect directly
  to over 20+ data sources, from your startup’s production database to massive
  data warehouses, and query immediately without extracts. The application is
  trusted by over 50,000 companies and is accessible to all, with a range of
  plans from free open-source to pay-as-you-go Pro and Enterprise. Metabase
  allows you to create and share interactive dashboards, craft metadata-rich
  models, and free your data from the confines of SQL with a Visual Query
  Builder. It is designed to make self-service analytics a reality, providing a
  simple yet powerful tool for data exploration and dashboarding.
instructions: null
changeLog:
  - date: 2022-11-08
    description: first release
links:
  - label: Website
    url: https://www.metabase.com/
  - label: Documentation
    url: https://www.metabase.com/docs/latest/
  - label: Github
    url: https://github.com/metabase/metabase/
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: metabase
    appServiceImage:
      type: string
      title: App Service Image
      default: metabase/metabase:latest
    metabaseSiteName:
      type: string
      title: Metabase Site Name (Title)
