name: Flarum
description: Experience a modern, fast, and free forum experience with our app.
  Designed with an elegant UI, our app is mobile-first, easily stylable, and
  lightweight, ensuring a seamless experience on any device. It prioritizes
  security and trust, providing a safe environment for users. The app is also
  localised into many languages, with 41 translation packs available, making it
  accessible to users worldwide. Whether you're a leading telephone network
  serving millions of customers, an avid adventurer sharing your experiences, or
  a provider of communication and entertainment, our app is the perfect platform
  for you. It's not just a forum, it's a revolution in community engagement.
instructions: Please use the credentials flarum:flarum to login.
changeLog:
  - date: 2022-10-31
    description: first release
  - date: 2023-2-24
    description: Update to v1.6.2
links:
  - label: Website
    url: https://flarum.org/
  - label: Documentation
    url: https://docs.flarum.org/
  - label: Github
    url: https://github.com/flarum/flarum
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: flarum
    appServiceImage:
      type: string
      title: App Service Image
      default: crazymax/flarum:1.6.2
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mysql
          title: MySQL
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - external
          title: External
    databaseServiceName:
      type: string
      title: Database Service Name (URL if external)
      default: flarum-db
    databasePort:
      type: string
      title: Database Port (blank to default)
    databaseName:
      type: string
      title: Database Name (blank to default)
    databaseUser:
      type: string
      title: Database User (blank to default)
    databaseUserPassword:
      type: string
      title: Database User Password (blank to randomly generated)
