name: Freescout
description: FreeScout is a powerful, open-source help desk and shared inbox
  application. It's a self-hosted alternative to Zendesk & Help Scout, offering
  you complete control over your customer support without compromising on
  privacy. FreeScout is designed to be lightweight yet robust, capable of
  handling unlimited support agents, tickets, and mailboxes. It offers seamless
  email integration, automatic replies, internal notes, conversation forwarding,
  merging, and moving, among other features. The application is mobile-friendly
  and supports multiple languages. It also includes features like push
  notifications, starred conversations, collision detection, and flexible
  notifications for user agents. FreeScout also offers a range of integrations,
  including Slack, WhatsApp, Facebook, and Telegram, and supports translating
  tickets, live chat, time tracking, custom fields, and more. It's the perfect
  solution for those who need professional customer support but can't afford to
  pay for Zendesk or Help Scout.
instructions: null
changeLog:
  - date: 2023-1-4
    description: first release
  - date: 2023-2-23
    description: Update to v1.16.25
links:
  - label: Website
    url: https://freescout.net
  - label: Documentation
    url: https://github.com/freescout-helpdesk/freescout/wiki
  - label: Github
    url: https://github.com/freescout-helpdesk/freescout/
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - adminEmail
    - adminPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: freescout
    appServiceImage:
      type: string
      title: App Service Image
      default: tiredofit/freescout:php8.1-1.16.25
    databaseServiceName:
      type: string
      title: Database Service Name
      default: freescout-db
    adminEmail:
      type: string
      title: Email
      default: changeme@easypanel.io
    adminPassword:
      type: string
      title: Password
      default: changeme
