name: Hasty Paste
description: Hasty Paste is a fast and minimalistic app designed for quickly
  pasting and sharing text. It is primarily used for sharing debug logs and
  similar content to aid developers in providing tech support. The app is
  publicly accessible with no authentication required. It generates random IDs
  for each paste, with an optional 'long' ID to reduce the chances of brute
  force attacks. Users can also add expiring pastes. The app features a dark
  theme and optional syntax highlighting. It is designed to use minimal
  resources and does not require JavaScript. Hasty Paste also allows users to
  choose their file system and offers a custom flat-file system. The app is
  named 'Hasty Paste' to reflect its speed and ease of use.
instructions: Hasty Paste takes a minute or two on first launch.
changeLog:
  - date: 2022-10-30
    description: first release
  - date: 2023-2-24
    description: Update to v1.9.0
links:
  - label: Documentation
    url: https://enchantedcode.co.uk/hasty-paste/
  - label: Github
    url: https://github.com/enchant97/hasty-paste
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: hastypaste
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/enchant97/hasty-paste:1.9.0
    redisServiceName:
      type: string
      title: Redis Service Name
      default: hastypaste-redis
