name: Jirafeau
description: Jirafeau is an open-source software designed for simple and
  efficient file sharing. It operates on a 'one-click-filesharing' principle,
  where you select your file, upload it, and share a link. The app allows you to
  send large files without any size limit, thanks to the HTML5 file API. It also
  provides a real-time progress report, showing speed, percentage, and remaining
  upload time. Jirafeau offers optional password protection for both uploading
  and downloading, and you can set an expiration time for downloads. The app
  also has a self-destruct feature, which deletes the file after the first
  download. It uses base 64 encoding to shorten URLs and allows for maximal
  upload size configuration. Jirafeau also features optional data encryption and
  a small administration interface.
instructions: null
changeLog:
  - date: 2022-11-22
    description: first release
links:
  - label: Github
    url: https://gitlab.com/mojo42/Jirafeau
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: jirafeau
    appServiceImage:
      type: string
      title: App Service Image
      default: jgeusebroek/jirafeau:20221008
