name: Gray Duck Mail
description: Gray Duck Mail is a user-friendly email discussion list application
  that offers an alternative to traditional email discussion group software. It
  is designed to be simple to set up and manage, making the process of running
  an email discussion list effortless. Gray Duck Mail is perfect for managing
  mailing lists between small to medium size groups, such as neighborhoods,
  schools, workplaces, and families. With Gray Duck Mail, you can send one email
  and automatically keep everyone in the loop. The application monitors a remote
  mail server for messages and processes them by relaying the message to all
  list members. It also automatically handles user subscriptions, unsubscription
  requests, and email bounces. Gray Duck Mail works with any external email host
  that allows for POP3/SMTP connections and message forwarding or aliasing. It
  relies totally on an external mail provider, allowing you to use an existing
  web host or email account.
instructions: null
changeLog:
  - date: 2023-3-3
    description: First Release
links:
  - label: Website
    url: https://grayduckmail.com
  - label: Github
    url: https://github.com/wagesj45/gray-duck-mail
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: grayduckmail
    appServiceImage:
      type: string
      title: App Service Image
      default: wagesj45/gray-duck-mail
