name: Cryptpad
description: CryptPad is an open-source collaborative office suite that offers
  end-to-end encryption, ensuring your data remains private and secure. It
  provides a full suite of applications, allowing you to work on various
  projects in real-time with your colleagues or friends. Whether you're planning
  a camping trip or setting up client briefs, CryptPad makes it easy to share
  files and collaborate without the need for account creation or app downloads.
  It's more than just a document editor; it's a secure platform for all your
  collaborative needs.
instructions: null
changeLog:
  - date: 2023-07-14
    description: First Release
links:
  - label: Website
    url: https://cryptpad.org
  - label: Docs
    url: https://docs.cryptpad.org
  - label: Github
    url: https://github.com/cryptpad
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cryptpad
    appServiceImage:
      type: string
      title: App Service Image
      default: promasu/cryptpad:alpine
