name: Zipline
description: Zipline is the next generation ShareX/File upload server, designed
  to make file sharing and management a breeze. With a user-friendly dashboard
  packed with features, Zipline allows you to upload any file type, view your
  files in a gallery, and even shorten URLs for easy sharing. The app also
  provides a way to organize your files with folders for easy access and
  management. Zipline also offers features like image compression, video
  thumbnail generation, and password protection for your uploads. With Zipline,
  you can quickly set up your own instance and configure it to your needs. It
  also offers an extensive API for a more fine-grained control over your
  instance. Zipline is not just a file upload server, it's a comprehensive tool
  for managing and sharing your files with ease and efficiency.
instructions: After installing Zipline for the first time, you may login to the
  dashboard with the username "administrator" and the password "password".
changeLog:
  - date: 2023-01-20
    description: First Release
  - date: 2023-03-22
    description: First Release
links:
  - label: Website
    url: https://zipline.diced.tech/
  - label: Github
    url: https://github.com/diced/zipline
  - label: Documentation
    url: https://zipline.diced.tech/docs/get-started
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: zipline
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/diced/zipline:3.6.4
    databaseServiceName:
      type: string
      title: Database Service Name
      default: zipline-db
