name: Gotenberg
description: Gotenberg is a Docker-powered stateless API designed to handle PDF
  files. It offers a developer-friendly interface to interact with robust tools
  like Chromium and LibreOffice, enabling the conversion of various document
  formats such as HTML, Markdown, Word, Excel, and more into PDF files. The app
  also supports an asynchronous workflow with a webhook feature, allowing you to
  upload the output file to your preferred destination. Gotenberg is a modular
  platform, meaning you can customize each module according to your needs.
  Additionally, it provides the option to build your own Docker image by adding
  new tools and creating modules that offer new routes to the API.
instructions: null
changeLog:
  - date: 2023-02-21
    description: first release
links:
  - label: Website
    url: https://gotenberg.dev/
  - label: Documentation
    url: https://gotenberg.dev/docs/get-started/live-demo
  - label: Github
    url: https://github.com/gotenberg/gotenberg
contributors:
  - name: TheoCouss
    url: https://github.com/TheoCouss
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gotenberg
    appServiceImage:
      type: string
      title: App Service Image
      default: gotenberg/gotenberg:7.8.1
