name: Portainer
description: Portainer is a powerful container management platform trusted by
  over a million users worldwide. It simplifies the deployment, configuration,
  troubleshooting, and securing of containers on Kubernetes, Docker, and Swarm
  across any data center, cloud, network edge, or IIOT device. Portainer is
  designed to accelerate container adoption and reduce deployment times, making
  it easier for teams with little to no knowledge of Kubernetes to work
  autonomously. It also aids in managing and updating deployments, setting up,
  maintaining, and troubleshooting container infrastructure, and ensuring
  security and compliance. Portainer supports hybrid and multi-cloud,
  multi-cluster, multi-device container management, making it a versatile tool
  for managing complex container ecosystems.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.portainer.io/
  - label: Documentation
    url: https://docs.portainer.io/
  - label: Github
    url: https://github.com/portainer/portainer#readme
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: portainer
    appServiceImage:
      type: string
      title: App Service Image
      default: portainer/portainer-ce:2.15.1-alpine
