name: Silicon Notes
description: Silicon Notes is a lightweight, low-friction personal knowledge
  base designed to streamline your note-taking and information organization. The
  app allows you to edit your notes in plaintext using Markdown, with the added
  benefit of language syntax highlighting in the rendered HTML. It offers
  powerful full-text and page title search capabilities, making it easier than
  ever to find the information you need. The app also features bi-directional
  page relationships, allowing you to create a complex web of interconnected
  information. Silicon Notes also includes a table of contents in the left
  sidebar for easy navigation, and a mobile layout that makes it accessible on
  any device. The app's no-frills UI ensures a smooth and distraction-free user
  experience. Silicon Notes is built with a minimal tech stack, relying on a few
  smallish dependencies, making it a lightweight and efficient tool for your
  personal knowledge management.
instructions: null
changeLog:
  - date: 2023-1-28
    description: first release
links:
  - label: Github
    url: https://github.com/cu/silicon
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: silicon
    appServiceImage:
      type: string
      title: App Service Image
      default: bityard/silicon:488df721031f74721483da787427115c7db19711
