name: Wordpress
description: WordPress is an open-source platform that empowers you to create a
  unique online space for your business, interests, or any other purpose. It
  offers a real-time, intuitive editing experience, allowing you to see exactly
  how your site will look as you add, edit, and rearrange your content. With
  flexible design tools and powerful features, you can create any kind of custom
  site. You can start with a blank canvas or choose from a wide variety of
  themes and patterns, customizing every detail from color and fonts to layouts
  and functionality. WordPress also offers over 55,000 plugins to extend your
  site's capabilities, whether you need to add a store, mailing list, portfolio,
  social feed, analytics, or anything else. Your content, design, and data
  always belong to you, and WordPress is committed to keeping your site as
  stable and secure as possible. Whether you're a global creative agency, a
  local business, or a personal blogger, WordPress offers endless possibilities
  for your online presence.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://wordpress.org/
  - label: Documentation
    url: https://learn.wordpress.org
  - label: Github
    url: https://github.com/WordPress/WordPress
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wordpress
    appServiceImage:
      type: string
      title: App Service Image
      default: wordpress:6
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: wordpress-db
