name: Trilium Notes
description: Trilium is a hierarchical note-taking application designed for
  creating and managing large personal knowledge bases. With Trilium, you can
  arrange your notes into an arbitrarily deep tree structure, with the ability
  to place a single note in multiple locations. The app offers rich WYSIWYG note
  editing, including tables, images, and math, with markdown autoformat. It also
  supports editing notes with source code, complete with syntax highlighting.
  Trilium provides seamless note versioning and attributes for note
  organization, querying, and advanced scripting. The app also includes a
  synchronization feature with a self-hosted sync server. For enhanced security,
  Trilium offers strong note encryption with per-note granularity. Other
  features include sketching diagrams with built-in Excalidraw, visualizing
  notes and their relations with relation maps and link maps, and a REST API for
  automation. Trilium is optimized for both usability and performance, capable
  of handling upwards of 100,000 notes.
instructions: null
changeLog:
  - date: 2023-3-22
    description: first release
links:
  - label: Documentation
    url: https://github.com/zadam/trilium/wiki
  - label: Github
    url: https://github.com/zadam/trilium
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: trilium
    appServiceImage:
      type: string
      title: App Service Image
      default: zadam/trilium:0.59.2
