name: Appsmith
description: Appsmith is a powerful tool designed to help engineers build custom
  software on top of their data. It simplifies internal tool development for
  businesses, streamlining operations, automating processes, and integrating
  multiple apps and data sources. Appsmith allows you to quickly build, deploy,
  and share applications that run critical business operations. It features
  intent-based auto-layouts for building responsive apps faster and offers a
  drag-and-drop interface for creating beautiful UIs without writing a single
  line of HTML/CSS. You can connect to any database, SaaS tool, or GraphQL/REST
  API, and query your data directly using SQL or the built-in query builder.
  Appsmith also provides the ability to write in-line JavaScript or reusable
  code blocks to extend your app's functionality, customize your UI, or write
  conditional logic. It's a secure, open-source platform that can be self-hosted
  for total control, privacy, and security.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.appsmith.com/
  - label: Documentation
    url: https://docs.appsmith.com/
  - label: Github
    url: https://github.com/appsmithorg/appsmith
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: appsmith
    appServiceImage:
      type: string
      title: App Service Image
      default: appsmith/appsmith-ce:v1.9.16
