name: Octobox
description: Octobox is an innovative app designed to help you manage your
  GitHub notifications more efficiently. With Octobox, you no longer have to
  worry about losing track of important issues or waking up to hundreds of
  notifications. The app adds an extra 'archived' state to each notification,
  allowing you to mark it as 'done'. If there's any activity on an archived
  thread, issue or PR, Octobox will move it back into your inbox. You can also
  search and filter notifications by repository, organization, type, action,
  state, CI status, and reason. Octobox keeps your notifications up to date with
  issue/pull-request status, CI status, labels, and more. The app is free for
  open source projects and offers enhanced notifications for private projects at
  a cost. Octobox is the perfect tool for developers who want to stay organized
  and focused.
instructions: null
changeLog:
  - date: 2023-3-22
    description: first release
links:
  - label: Website
    url: https://octobox.io
  - label: Documentation
    url: https://octobox.io/documentation
  - label: Github
    url: https://github.com/octobox/octobox
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
    - githubClient
    - githubSecret
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: octobox
    appServiceImage:
      type: string
      title: App Service Image
      default: octoboxio/octobox:ruby-3
    databaseServiceName:
      type: string
      title: Database Service Name
      default: octobox-db
    redisServiceName:
      type: string
      title: Database Service Name
      default: octobox-redis
    githubClient:
      type: string
      title: Github Client ID
    githubSecret:
      type: string
      title: Github Client Secret
