name: CodeX Docs
description: CodeX is a comprehensive platform that brings together passionate
  engineers, designers, students, graduates, and young specialists from around
  the globe. The app is dedicated to creating high-quality open-source projects
  and providing a valuable experience of developing full-fledged products for
  the global market. CodeX offers a range of products including Editor.js, a
  block-styled, API-oriented editor for media that generates useful JSON-output
  with clear data, Hawk.so, a fast and lightweight error tracking service, and
  CodeX Notes, a simple and fast cross-platform notes application based on
  Editor.js and Electron. The platform also offers Capella, a cloud service for
  image storage and delivery, and a platform for integration of services into
  messengers. With a focus on media, social networks, education, augmented
  reality, and medicine, CodeX is a one-stop solution for tech enthusiasts
  looking to make a mark in the global market.
instructions: View All Configuation on the Docs site - https://docs.codex.so/configuration
changeLog:
  - date: 2023-01-23
    description: First Release
links:
  - label: Website
    url: https://codex.so
  - label: Documentation
    url: https://docs.codex.so
  - label: Github
    url: https://github.com/codex-team/codex.docs
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - codexAuthPassword
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    codexAuthPassword:
      type: string
      title: CodeX Auth Password
    appServiceName:
      type: string
      title: App Service Name
      default: codex
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/codex-team/codex.docs:v2.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: codex-db
