name: Weaviate
description: Weaviate is an open-source vector database that allows you to store
  and retrieve data objects based on their semantic properties by indexing them
  with vectors. It can be used stand-alone or with a variety of modules that can
  do the vectorization for you and extend the core capabilities. Weaviate
  provides a lightning-fast pure vector similarity search over raw vectors or
  data objects, even with filters. It combines keyword-based search with vector
  search techniques for state-of-the-art results. You can also use any
  generative model in combination with your data, for example to do Q&A over
  your dataset. Weaviate's next-gen vector database can power a wide range of
  innovative apps.
instructions: null
changeLog:
  - date: 2023-06-30
    description: first release
links:
  - label: Website
    url: https://weaviate.io
  - label: Documentation
    url: https://weaviate.io/developers/weaviate
  - label: Github
    url: https://github.com/weaviate/weaviate
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
    appServiceImage:
      type: string
      title: App Service Image
      default: semitechnologies/weaviate:1.19.8
