name: Plausible
description: Plausible is a simple, lightweight, and open-source web analytics
  tool that serves as a privacy-friendly alternative to Google Analytics. It is
  designed to be intuitive and easy to use, providing essential insights about
  your website's traffic on a single page, without the need for complex menus or
  custom reports. The Plausible script is 45 times smaller than Google
  Analytics, ensuring your site loads faster and contributes to a greener web.
  It respects user privacy by not using cookies or collecting personal data, and
  all data processing is carried out anonymously within the EU. Plausible also
  allows you to track goal conversions, revenue, and campaigns, segment your
  audience, and analyze referral sources. You can share your stats publicly or
  privately, invite team members, and even import your historical stats from
  Google Analytics. It's a powerful tool for understanding your website's
  performance while respecting user privacy.
instructions: null
changeLog:
  - date: 2023-1-5
    description: first release
links:
  - label: Website
    url: https://plausible.io
  - label: Documentation
    url: https://plausible.io/docs
  - label: Github
    url: https://github.com/plausible/plausible
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Derock
    url: https://github.com/ItzDerock
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - clickhouseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: plausible
    appServiceImage:
      type: string
      title: App Service Image
      default: plausible/analytics:v1.5.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: plausible-db
    clickhouseServiceName:
      type: string
      title: Database Service Name
      default: plausible-clickhouse
