name: Muse
description: Muse is a self-hosted Discord music bot designed to enhance your
  music experience on Discord. It's perfect for small to medium-sized groups,
  such as you and your friends. With Muse, you can livestream music, seek within
  a song or video, and even cache music locally for better performance. It also
  allows users to convert playlists, artists, albums, and songs from Spotify
  automatically. You can add custom shortcuts, and the bot supports multiple
  guilds. It normalizes volume across tracks for a consistent listening
  experience. Muse is written in TypeScript and is easily extendable. It's a
  loyal Packers fan and doesn't vote to skip - this is anarchy, not a democracy!
instructions: null
changeLog:
  - date: 2023-03-30
    description: first release
links:
  - label: Github
    url: https://github.com/codetheweb/muse
  - label: Documentation
    url: https://github.com/codetheweb/muse#running
contributors:
  - name: Rubén Robles
    url: https://github.com/D8vjork
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - discordToken
    - youtubeApiKey
    - spotifyClientId
    - spotifyClientSecret
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: discordbot
    appServiceImage:
      type: string
      title: App Service Image
      default: codetheweb/muse:2.2.2
    discordToken:
      type: string
      title: Discord Token
    youtubeApiKey:
      type: string
      title: Youtube API Key
    spotifyClientId:
      type: string
      title: Spotify Client ID
    spotifyClientSecret:
      type: string
      title: Spotify Client Secret
