name: Ampache
description: Ampache is a web-based audio/video streaming application and file
  manager that allows you to access your music and videos from anywhere,
  anytime. With this app, you can browse and manage your music collection
  through a simple web interface, and even synchronize local and remote catalogs
  to create a unique, consistent collection. Ampache also offers music streaming
  capabilities, allowing you to stream your music to your preferred player,
  control it with Localplay, or directly listen on the web page with the HTML5
  player. The app is completely free and open source, and it's designed to work
  on almost any internet-enabled device, including your phone, tablet, or
  television. Ampache is not a media organizer, but a tool that presents an
  already organized collection in a useful way.
instructions: MySQL Username is "admin". The logs will show a line that says
  "mysql -uadmin -pjnzYXLz7cMzq -h<host> -P<port>"". The password is everything
  after "-p", in this case "jnzYXLz7cMzq".
changeLog:
  - date: 2023-03-19
    description: Template created (v5.5.7)
links:
  - label: Website
    url: http://ampache.org/
  - label: Github
    url: https://github.com/ampache/ampache
  - label: Github Docker
    url: https://github.com/ampache/ampache-docker
  - label: DockerHub
    url: https://hub.docker.com/r/ampache/ampache
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - appMediaHostPath
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ampache
    appServiceImage:
      type: string
      title: App Service Image
      default: ampache/ampache:5.6.0
    appMediaHostPath:
      type: string
      title: Media Host Path
