name: Node-RED
description: Node-RED is a unique programming tool designed for creating
  event-driven applications in a low-code environment. It allows you to connect
  hardware devices, APIs, and online services in innovative ways. The app
  features a browser-based editor that simplifies the process of creating flows
  using a wide array of nodes available in the palette. These flows can be
  deployed to its runtime with just a single click. Node-RED also allows you to
  create JavaScript functions within the editor using a rich text editor and
  save useful functions, templates, or flows for future use. Built on Node.js,
  Node-RED is lightweight and can run on low-cost hardware like Raspberry Pi or
  in the cloud. It also supports the import and export of flows in JSON format
  for easy sharing.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Website
    url: https://nodered.org/
  - label: Documentation
    url: https://nodered.org/docs/
  - label: Forum
    url: https://discourse.nodered.org/
  - label: Github
    url: https://github.com/node-red
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nodered
    appServiceImage:
      type: string
      title: App Service Image
      default: nodered/node-red:3.0.2
