name: Wg-easy
description: WireGuard Easy is an all-in-one application designed to simplify
  the installation and management of WireGuard on any Linux host. With a
  user-friendly web interface, it allows you to list, create, edit, delete,
  enable, and disable clients with ease. You can also view a client's QR code
  and download a client's configuration file directly from the app. The app
  provides statistics on which clients are connected and features Tx/Rx charts
  for each connected client. It also supports Gravatar. WireGuard Easy requires
  a host with a kernel that supports WireGuard and Docker installed.
instructions: null
changeLog:
  - date: 2022-12-20
    description: first release
links:
  - label: Website
    url: https://github.com/WeeJeWel/wg-easy
  - label: Documentation
    url: https://github.com/WeeJeWel/wg-easy/wiki
  - label: Github
    url: https://github.com/WeeJeWel/wg-easy
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - appPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wg-easy
    appServiceImage:
      type: string
      title: App Service Image
      default: weejewel/wg-easy:7
    appPassword:
      type: string
      title: Admin Password
