name: LibreTranslate
description: LibreTranslate is a free and open-source machine translation app
  that is entirely self-hosted. Unlike other translation apps, it does not rely
  on proprietary providers such as Google or Azure to perform translations.
  Instead, its translation engine is powered by the open-source Argos Translate
  library. LibreTranslate can translate text between different languages,
  auto-detect the language of the input text, and even handle HTML content. It
  provides a simple and intuitive interface for users to input the text they
  want to translate, select the source and target languages, and get the
  translated text. With LibreTranslate, you can enjoy a reliable, accurate, and
  privacy-friendly translation service right at your fingertips.
instructions: null
changeLog:
  - date: 2020-12-20
    description: first release
links:
  - label: Documentation
    url: https://github.com/LibreTranslate/LibreTranslate/blob/master/README.md
  - label: Github
    url: https://github.com/LibreTranslate/LibreTranslate
contributors:
  - name: kaname-png
    url: https://github.com/kaname-png
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - chartLimit
    - reqLimit
    - bachLimit
    - suggestions
    - disableWebUI
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: libretranslate
    appServiceImage:
      type: string
      title: App Service Image
      default: libretranslate/libretranslate:latest
    chartLimit:
      type: number
      title: Character limit for each translation
      default: 5000
    reqLimit:
      type: number
      title: Rate request limit
      default: 500
    bachLimit:
      type: number
      title: Bach translation limit
      default: 100
    googleAnalytics:
      type: string
      title: Google Analytics
      default: ""
    suggestions:
      type: boolean
      title: Translation suggestions
      default: false
    disableWebUI:
      type: boolean
      title: Disable Web UI
      default: false
