name: Actual Budget
description: Actual is a personal finance tool designed to help you manage your
  finances with ease and convenience. This local-first application is 100% free
  and open-source, providing you with a reliable platform to keep track of your
  financial transactions. It's written in NodeJS and features a synchronization
  element that allows your changes to seamlessly move between devices. This
  means you can access and manage your financial data from any device without
  any hassle. The app is not just about tracking your expenses, it also includes
  features for budgeting, account management, and generating reports and
  filters. With Actual, managing your personal finances becomes a breeze.
instructions: null
changeLog:
  - date: 2023-1-25
    description: first release
links:
  - label: Github
    url: https://github.com/actualbudget/actual
  - label: Documentation
    url: https://actualbudget.github.io/docs
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: actualbudget
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/actualbudget/actual-server:23.2.9
