name: Ghost File Sharing
description: Our app is a powerful tool designed to streamline your workflow and
  enhance productivity. It allows you to easily find code, projects, and people
  on GitHub, making it simpler than ever to collaborate and contribute to
  open-source projects. With this app, you can stay updated with product
  updates, company news, and more by subscribing to our newsletter. It also
  offers a range of features designed to ensure the security of your work,
  making it a reliable choice for enterprises. Whether you're a developer
  looking for a robust platform or a company seeking to leverage the power of
  open-source, our app is the perfect solution for you.
instructions: null
changeLog:
  - date: 2023-01-28
    description: Stable build. Hello, Easypanel!
links:
  - label: Github
    url: https://github.com/voxelin/gh0.st
contributors:
  - name: Saputskyi Petro
    url: https://github.com/voxelin
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gh0.st
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/voxelin/ghost:stable
