name: Substreamer
description: Substreamer is a free client app designed to provide you with a
  seamless and personalized music experience. It works in conjunction with the
  Subsonic music server, allowing you to organize and access your music library
  in a way that suits you best. Substreamer is compatible with Subsonic forks
  such as Airsonic, Madsonic, and others that implement the Subsonic API v1.13
  or higher, including Navidrome and Ampache. This app is packed with features
  that enhance your music listening experience. With Substreamer, your music is
  always at your fingertips, just the way you like it.
instructions: null
changeLog:
  - date: 2023-3-13
    description: first release
links:
  - label: Community
    url: https://reddit.com/substreamer
  - label: Website
    url: https://substreamerapp.com
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: substreamer
    appServiceImage:
      type: string
      title: App Service Image
      default: ghenry22/substreamer:6.0.41
