name: Excalidraw
description: Excalidraw is an open-source virtual whiteboard designed to bring
  your creativity to life. It allows you to create beautiful hand-drawn like
  diagrams, wireframes, or any other visuals you can imagine. The app is
  equipped with an infinite, canvas-based whiteboard that supports a hand-drawn
  like style. It offers a wide range of tools including rectangle, circle,
  diamond, arrow, line, free-draw, eraser, and more. You can customize your
  drawings with the help of image support and shape libraries. The app also
  supports localization and allows you to export your creations to PNG, SVG, and
  clipboard. It also features an open format that lets you export drawings as an
  .excalidraw json file. The app is also equipped with features like
  arrow-binding, labeled arrows, undo/redo, and zoom and panning support.
  Excalidraw also offers real-time collaboration and end-to-end encryption for
  secure and efficient teamwork.
instructions: null
changeLog:
  - date: 2023-3-27
    description: first release
links:
  - label: Website
    url: https://excalidraw.com/
  - label: Github
    url: https://github.com/excalidraw/excalidraw
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: excalidraw
    appServiceImage:
      type: string
      title: App Service Image
      default: excalidraw/excalidraw:sha-4bfc5bb
