name: Wiki.js
description: Wiki.js is a powerful and extensible open source Wiki software
  designed to make documentation a joy to write. It features a beautiful and
  intuitive interface that can be fully customized to your liking, including a
  light and dark mode. The software is compatible with various platforms and
  databases, including PostgreSQL, MySQL, MariaDB, MS SQL Server, and SQLite.
  With Wiki.js, you can manage all aspects of your wiki using the extensive and
  intuitive admin area. The software is built with performance in mind, running
  on the blazing fast Node.js engine. It is designed to intelligently make use
  of available resources, making it scalable whether it's on a tiny Raspberry Pi
  or on a high performance VM in the cloud. Wiki.js also allows you to control
  the privacy of your wiki, making it public, completely private, or a mix of
  both. It offers a wide range of modules that can be turned on/off on demand,
  catering to the unique needs of different teams. These modules include
  authentication, editors, history, localization, media assets, rendering,
  search, storage, user management, and themes. Wiki.js is proudly licensed
  under AGPLv3 and has been downloaded over 50 million times.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-03-22
    description: Update to v2.5.298
links:
  - label: Website
    url: https://js.wiki/
  - label: Documentation
    url: https://docs.requarks.io/
  - label: Github
    url: https://github.com/Requarks/wiki
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wikijs
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/requarks/wiki:2.5.298
    databaseType:
      type: string
      title: Database Type
      default: postgres
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: wikijs-db
