name: Adminer
description: Adminer is a comprehensive database management tool, designed to
  simplify and streamline your database operations. Written in PHP, it is a
  lightweight yet powerful tool that supports a wide range of databases
  including MySQL, MariaDB, PostgreSQL, SQLite, MS SQL, Oracle, Elasticsearch,
  MongoDB and others. With Adminer, you can easily connect to a database server
  using a username and password, select an existing database or create a new
  one, and manage all aspects of your database including tables, columns,
  indexes, foreign keys, triggers, views, stored procedures, and functions. It
  also allows you to execute any SQL command from a text field or a file, and
  export your database structure, data, views, routines, and databases to SQL or
  CSV. Adminer prioritizes security, user experience, performance, feature set,
  and size, making it a reliable and efficient tool for all your database
  management needs.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.adminer.org/
  - label: Github
    url: https://github.com/vrana/adminer/
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: adminer
    appServiceImage:
      type: string
      title: App Service Image
      default: adminer:4.8.1
