name: Owncast
description: Owncast is a free and open-source live video and web chat server
  that works seamlessly with your existing broadcasting software. It gives you
  complete control and ownership over your stream, allowing you to create the
  content you want. The app comes with a frictionless built-in chat feature that
  enables your viewers to engage and be a part of the action. You can include
  custom emotes and build chat bots to encourage viewer engagement. Owncast also
  allows your live stream to reach a wider audience on The Fediverse, including
  platforms like Mastodon and other Fediverse services. It's a self-hosted and
  independent solution for live streaming, offering a high level of performance
  comparable to proprietary platforms.
instructions: null
changeLog:
  - date: 2023-2-21
    description: first release
links:
  - label: Website
    url: https://owncast.online/
  - label: Documentation
    url: https://owncast.online/docs
  - label: Github
    url: https://github.com/owncast/owncast
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: owncast
    appServiceImage:
      type: string
      title: App Service Image
      default: gabekangas/owncast:0.0.13
