name: ToolJet
description: "ToolJet is an open-source low-code framework designed to help you
  build and deploy custom internal tools with ease. It comes with a built-in
  database, ToolJet DB, built on top of PostgreSQL, and also allows you to
  connect to external data sources such as PostgreSQL, MongoDB, MS SQL Server,
  Snowflake, BigQuery, and more. You can also connect to API/GraphQL endpoints,
  SaaS tools like Airtable, Stripe, Google Sheets, and cloud object storage
  services like AWS S3, Google Cloud Storage, and Minio. Once connected, ToolJet
  can run queries on these data sources to fetch and update data. The fetched
  data can be visualized and modified using UI widgets like tables, charts,
  forms, etc. You can also use Javascript or Python queries for writing business
  logic or interacting with the user interface of the application. With ToolJet,
  you can build apps in three simple steps: connect to data sources, build
  queries, and build the user interface using the visual App Builder. ToolJet
  binds together the data sources, queries, and components to convert business
  logic into custom applications."
instructions: null
changeLog:
  - date: 2023-07-09
    description: First Release
links:
  - label: Website
    url: https://docs.tooljet.com
  - label: Docs
    url: https://docs.tooljet.com
  - label: Github
    url: https://github.com/ToolJet/ToolJet
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: tooljet
    appServiceImage:
      type: string
      title: App Service Image
      default: tooljet/tooljet-ce:latest
    databaseServiceName:
      type: string
      title: App Service Name
      default: tooljet-db
