name: Directus
description: Directus is a modern, open-source data platform that instantly
  transforms any SQL database into an API and a beautiful no-code app. It is
  designed to work with any SQL database, allowing you to maintain complete
  control over your new or existing database without the need for migration to a
  proprietary data model. The Directus API layers on top of your database,
  providing both REST and GraphQL APIs for your data. The Directus App enables
  your entire team to safely and intuitively browse, manage, and visualize data.
  It is a flexible platform that can be used as a Backend-as-a-Service, a
  Headless CMS, an Internal Tool Builder, and for Data Management & Analytics.
  With Directus, you can connect external digital experiences, design APIs,
  control data flows, build internal tools, and much more.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://directus.io/
  - label: Documentation
    url: https://docs.directus.io/
  - label: Github
    url: https://github.com/directus/docs
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - adminEmail
    - adminPassword
    - databaseType
    - databaseServiceName
    - redisServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: directus
    appServiceImage:
      type: string
      title: App Service Image
      default: directus/directus:9.18.1
    adminEmail:
      type: string
      title: Admin Email
      description: admin@example.com
    adminPassword:
      type: string
      title: Admin Password
    databaseType:
      type: string
      title: Database Type
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: directus-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: directus-redis
