name: Postgres Backup
description: The postgres-backup-s3 app is a powerful tool designed to backup
  your PostgreSQL databases to Amazon S3. It supports periodic backups, allowing
  you to schedule automatic backups at your convenience. This ensures that your
  data is always safe and can be restored whenever needed. The app also offers
  the option to backup all available databases at once, creating a single
  archive with a timestamp for easy identification. For added security, the app
  provides an encryption feature. By setting an encryption password, your backup
  can be encrypted and only decrypted with the correct password. This app is
  perfect for those who want to ensure their PostgreSQL databases are securely
  backed up in a reliable and efficient manner.
instructions: "In order to test that you configured it properly, remove the
  SCHEDULE variable from the environment, click deploy and check the logs. If
  everything works fine, you can add the SCHEDULE variable back. You can read
  more about the environment variables here:
  https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3"
changeLog:
  - date: 2022-08-05
    description: first release
links:
  - label: Documentation
    url: https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3
  - label: Github
    url: https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - host
    - port
    - user
    - password
    - accessKey
    - secretKey
    - bucket
    - prefix
    - region
    - endpoint
    - schedule
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: postgres-backup
    appServiceImage:
      type: string
      title: App Service Image
      default: easypanel/postgres-backup-s3
    host:
      type: string
      title: Postgres Host
    port:
      type: string
      title: Postgres Port
      default: "5432"
    user:
      type: string
      title: Postgres User
      default: postgres
    password:
      type: string
      title: Postgres Password
    accessKey:
      type: string
      title: S3 Access Key
    secretKey:
      type: string
      title: S3 Secret Key
    bucket:
      type: string
      title: S3 Bucket
    prefix:
      type: string
      title: S3 Prefix
      default: backup
    region:
      type: string
      title: S3 Region
      default: us-west-1
    endpoint:
      type: string
      title: S3 Endpoint
    schedule:
      type: string
      title: Schedule
      default: "@daily"
      description: You can use CRON syntax
