name: Tautuilli
description: Tautulli is a powerful web application designed to monitor,
  analyze, and notify you about your Plex Media Server's activities. It runs
  alongside your Plex Media Server, tracking a variety of statistics including
  what has been watched, who watched it, when and where it was watched, and how
  it was watched. The app presents all these statistics in a clean,
  user-friendly interface with tables and graphs. Tautulli also allows you to
  monitor current activity on your Plex Media Server, log watch history for all
  your users, view streaming trends with intuitive graphs, trigger notifications
  or scripts from events on your Plex server, and keep track of when content is
  added to your Plex library. You can also create and send newsletters for
  recently added media, view and delete all synced content from your server, see
  detailed information on all of your media, and even download the official app
  to view activity and stats on the go. Tautulli is compatible with any system
  that supports python.
instructions: null
changeLog:
  - date: 2023-1-26
    description: first release
links:
  - label: Website
    url: https://tautulli.com/
  - label: Github
    url: https://github.com/Tautulli/Tautulli
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: tautuilli
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/tautulli:2.11.1
