name: Focalboard
description: Mattermost Boards is an open-source project management tool
  designed for technical teams. It centralizes, plans, and tracks all your work
  in one place, helping your organization maintain a single source of truth.
  This ensures your teams stay aligned to complete tasks, reach milestones, and
  achieve their goals. The app allows you to manage all your tasks on a Kanban,
  table, gallery, and calendar view, focusing on the highest priority items with
  board filters. It also offers real-time collaboration features, including card
  comments, @mention teammates, and board permissions to share your board with
  the entire team or specific individuals. Mattermost Boards comes with
  pre-built templates for quick setup or the option to create a fully custom
  board from scratch. It also includes features like unlimited boards, file
  sharing, customizable templates, project cards & tasks, archiving & back-up
  snapshots, and more. Mattermost Boards is an open-source alternative to tools
  like Asana, Trello, and Notion.
instructions: null
changeLog:
  - date: 2023-03-20
    description: First Release
links:
  - label: Website
    url: https://focalboard.com
  - label: Documentation
    url: https://docs.mattermost.com/guides/boards.html
  - label: Github
    url: https://github.com/mattermost/focalboard
  - label: Docker
    url: https://hub.docker.com/r/mattermost/focalboard
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: focalboard
    appServiceImage:
      type: string
      title: App Service Image
      default: mattermost/focalboard:7.10.0
    databaseType:
      type: string
      title: Database Type
      default: sqlite3
      oneOf:
        - enum:
            - sqlite3
          title: SQLite
        - enum:
            - postgres
          title: PostgreSQL
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: focalboard-db
    enablePublicSharedBoards:
      type: boolean
      title: Enable Public Shared Boards
      default: false
    telemetry:
      type: boolean
      title: Telemetry
      default: false
