name: Sonarr
description: Sonarr is a Personal Video Recorder (PVR) designed for Usenet and
  BitTorrent users. It monitors multiple RSS feeds for new episodes of your
  favorite shows and automatically grabs, sorts, and renames them. Sonarr can
  also be configured to automatically upgrade the quality of files already
  downloaded when a better quality format becomes available. It features a
  calendar to see all your upcoming episodes in one convenient location, and a
  manual search to find all the releases and choose the one you want. Sonarr
  also handles failed downloads, automatically blocking the release and trying
  another one until it finds one that works. It is fully integrated with
  SABnzbd, NZBGet, Kodi, and Plex, and supports major platforms including
  Windows, Linux, macOS, and Raspberry Pi.
instructions: null
changeLog:
  - date: 2022-12-26
    description: first release
links:
  - label: Website
    url: https://sonarr.tv/
  - label: Documentation
    url: https://wiki.servarr.com/Sonarr
  - label: Github
    url: https://github.com/Sonarr/Sonarr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: sonarr
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/sonarr:version-3.0.10.1567
