name: Photoview
description: Photoview is a user-friendly photo gallery designed for
  photographers. It allows you to easily navigate through directories filled
  with high-resolution photos and videos. The app syncs with your file system,
  automatically organizing your media based on the file structure. Directories
  become albums filled with the photos and videos found within them. Photoview
  also automatically rescans for new media, keeping your gallery updated.
  Multiple users can be configured, each with their own directory of photos and
  videos, and each user's media is kept private with a username and password.
  Albums and individual photos or videos can be shared through public or
  password-protected links. Photoview also analyzes photos for EXIF metadata,
  displaying this information next to the photo and using it to present photos
  on a map. The app also has a mobile version for iOS, allowing you to quickly
  access your media library from your phone. Photoview supports RAW images,
  automatically extracts metadata from images and videos, and optimizes videos
  for the web. It also generates thumbnails automatically and ensures that your
  media is secure and private.
instructions: You will need to mount the location where your photos are to
  complete the installation.
changeLog:
  - date: 2023-03-16
    description: First Release
links:
  - label: Website
    url: https://photoview.github.io/
  - label: Github
    url: https://github.com/photoview/photoview
  - label: Demo
    url: https://photos.qpqp.dk/
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: photoview
    appServiceImage:
      type: string
      title: App Service Image
      default: viktorstrate/photoview:2.3.13
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
        - enum:
            - postgres
          title: PostgreSQL
        - enum:
            - sqlite
          title: SQLite
    databaseServiceName:
      type: string
      title: Database Service Name
      default: photoview-db
