name: Mstream
description: mStream is a personal music streaming server that allows you to
  access your music collection from anywhere. It's like having your private
  cloud for music. With mStream, you can sync your collection between your
  devices for offline access. It offers high-quality streaming for audiophiles
  and FLAC enthusiasts, allowing you to stream your music uncompressed. mStream
  respects your privacy, it does not collect statistics on your listening
  habits. It's also beneficial for artists as buying music directly means your
  money goes directly to them. The server setup is quick and it runs on any
  operating system. It also has mobile apps for iOS & Android and allows you to
  stream your music in any browser. Other features include gapless playback,
  Milkdrop visualizer, playlist sharing, and drag and drop file uploading. All
  the code for mStream is open source.
instructions: null
changeLog:
  - date: 2023-3-20
    description: first release
links:
  - label: Website
    url: https://mstream.io
  - label: Github
    url: https://github.com/IrosTheBeggar/mStream
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mstream
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/mstream:5.11.4
