name: Weblate
description: Weblate is a powerful, web-based continuous localization system. It
  is designed to simplify the process of translating text from one language to
  another, making it an invaluable tool for projects and companies operating in
  multiple countries. With Weblate, users can easily translate using the
  platform, download and upload translations, and even integrate with version
  control systems for seamless workflow. The app supports a wide range of file
  formats, and it also provides a REST API and Python API for further
  flexibility. Weblate also offers features like automatic suggestions,
  translation memory, and various checks and fixups to ensure high-quality
  translations. Whether you're starting with internationalization or managing an
  established translators community, Weblate has the features to support your
  translation needs.
instructions: Please use the following credentials to login. changeme@easypanel.io|changeme
changeLog:
  - date: 2022-11-23
    description: first release
  - date: 2023-03-22
    description: Update to v4.16
links:
  - label: Documentation
    url: https://docs.weblate.org/en/latest/index.html
  - label: Github
    url: https://github.com/WeblateOrg/weblate
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - redisServiceName
    - emailNoReply
    - emailHost
    - emailUsername
    - emailPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: weblate
    appServiceImage:
      type: string
      title: App Service Image
      default: weblate/weblate:4.16.2-1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: weblate-db
    redisServiceName:
      type: string
      title: Redis Service Name
      default: weblate-redis
    emailNoReply:
      type: string
      title: No Reply Email
    emailHost:
      type: string
      title: Email Host
    emailUsername:
      type: string
      title: Email Username
    emailPassword:
      type: string
      title: Email Password
