name: Radarr
description: Radarr is a movie collection manager designed for Usenet and
  BitTorrent users. It monitors multiple RSS feeds for new movies and interfaces
  with clients and indexers to grab, sort, and rename them. Radarr also has the
  ability to automatically upgrade the quality of existing files in your library
  when a better quality format becomes available. The app features a calendar to
  see all your upcoming movies in one place, manual search to find all the
  releases and choose the one you want, and automatic handling of failed
  downloads. Radarr ensures you get the right release every time with its custom
  formats feature, which allows fine control over release prioritization and
  selection. It also supports major platforms like Windows, Linux, macOS, and
  others.
instructions: null
changeLog:
  - date: 2022-10-30
    description: first release
links:
  - label: Website
    url: https://radarr.video/
  - label: Documentation
    url: https://wiki.servarr.com/radarr
  - label: Github
    url: https://github.com/Radarr/Radarr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: radarr
    appServiceImage:
      type: string
      title: App Service Image
      default: linuxserver/radarr:version-4.4.4.7068
