name: Qdrant
description: Qdrant is a powerful vector database and vector similarity search
  engine designed to power the next generation of AI applications. It deploys as
  an API service, providing search for the nearest high-dimensional vectors.
  This allows embeddings or neural network encoders to be turned into
  full-fledged applications for matching, searching, recommending, and much
  more. Qdrant supports a large variety of data types and query conditions,
  including string matching, numerical ranges, geo-locations, and more. It is
  cloud-native and scales horizontally, ensuring efficient utilization of
  resources. With Qdrant, you can build and deploy semantic neural search on
  your data in minutes, understand user behavior in real time, and find similar
  images or detect duplicates with ease.
instructions: null
changeLog:
  - date: 2023-06-30
    description: first release
links:
  - label: Website
    url: https://qdrant.tech/
  - label: Documentation
    url: https://qdrant.tech/documentation/
  - label: Github
    url: https://github.com/qdrant/qdrant
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
    appServiceImage:
      type: string
      title: App Service Image
      default: qdrant/qdrant:v1.3.0
