name: OneDev
description: OneDev is a versatile app designed to streamline your project
  management and development processes. It offers a comprehensive suite of
  features including pull requests, issue tracking, and build management. With
  OneDev, you can easily manage your projects, track commits, and handle
  branches and tags. The app also provides a platform for managing pull
  requests, merging them, and discarding when necessary. It allows you to keep
  track of open and closed issues, as well as those that have been released.
  OneDev also offers a robust build management system, enabling you to monitor
  successful builds across various projects. The app is designed to support
  multiple projects, each with its own set of files, commits, branches, tags,
  pull requests, and builds. With OneDev, you can streamline your workflow,
  enhance collaboration, and improve productivity in your development projects.
instructions: null
changeLog:
  - date: 2023-02-9
    description: first release
links:
  - label: Website
    url: https://code.onedev.io/
  - label: Documentation
    url: https://docs.onedev.io/
  - label: Github
    url: https://code.onedev.io/onedev/server
contributors:
  - name: spaceb0t
    url: https://github.com/spacec0de
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: onedev
    appServiceImage:
      type: string
      title: App Service Image
      default: 1dev/server:8.1.6
    databaseServiceName:
      type: string
      title: Database Service Name
      default: onedev-db
