name: Sshwifty
description: Sshwifty is a web-based SSH and Telnet client that allows you to
  access these services directly from any standard web browser. It can be
  deployed on your computer or server, providing a convenient and accessible
  interface for SSH and Telnet connections. Sshwifty is designed to be highly
  configurable, allowing you to set up multiple servers, define presets for
  known remotes, and even restrict connections to preset remotes only. It also
  supports secure connections through TLS, and can be configured to connect
  through a Socks5 proxy. Whether you need to connect to a remote server or a
  local machine, Sshwifty provides a flexible and user-friendly solution.
instructions: null
changeLog:
  - date: 2022-12-20
    description: first release
links:
  - label: Github
    url: https://github.com/nirui/sshwifty
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: sshwifty
    appServiceImage:
      type: string
      title: App Service Image
      default: niruix/sshwifty:0.2.33-beta-release
