name: Bookstack
description: "BookStack is a free and open-source platform designed to help you
  organize and store information in a simple and efficient way. It is a
  self-hosted solution that allows you to create, edit, and manage content
  through an easy-to-use interface. The content is divided into three real-world
  groups: Books, Chapters, and Pages, making it easy to navigate and find the
  information you need. The platform also includes a powerful search feature
  that allows you to search at the book level or across all books, chapters, and
  pages. You can also link directly to any paragraph, keeping your documentation
  interconnected. BookStack offers configuration options that let you customize
  the system to suit your needs, including changing the name, logo, and
  registration options. It also includes built-in diagrams.net drawing
  capability for creating diagrams within your documentation, a markdown editor
  for those who prefer to write in markdown, and integrated authentication
  options. The platform supports multiple languages and offers both dark and
  light modes for a comfortable user experience. It also includes a full role
  and permission system, multi-factor authentication, and features like
  cross-book sorting, page revisions, and image management."
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.bookstackapp.com/
  - label: Documentation
    url: https://www.bookstackapp.com/docs/
  - label: Github
    url: https://github.com/BookStackApp/BookStack
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: bookstack
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/bookstack:23.05.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: bookstack-db
