name: Gitea
description: Gitea is a lightweight DevOps platform designed to streamline
  operations from planning to production. It enables the creation and management
  of repositories, exploration of commit history and code files, review and
  merging of code commits, and more. Gitea also supports standard Git features,
  including tags, cherry-picking, hooks, and integrated collaboration tools. It
  features an integrated CI/CD system, Gitea Actions, that is compatible with
  GitHub Actions. With Gitea, you can efficiently manage a project's
  requirements, features, and bugs through issue tasks, labeling, and kanban
  project boards. It supports more than 20 different kinds of public or private
  package management. Gitea is an open-source project that accelerates
  development and collaboration, offering universal compatibility and flexible
  deployment options. It also provides a powerful built-in CI/CD system and is
  developed with a focus on security. Gitea can be tailored to your requirements
  and is integrated with your favorite tools to boost your workflow.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-2-24
    description: Update to v1.18.4
links:
  - label: Website
    url: https://gitea.io/en-us/
  - label: Documentation
    url: https://docs.gitea.io/en-us/
  - label: Github
    url: https://github.com/go-gitea/
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gitea
    appServiceImage:
      type: string
      title: App Service Image
      default: gitea/gitea:1.19.2
    databaseType:
      type: string
      title: Database Type
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: gitea-db
