name: LinkStack
description: LinkStack is a powerful open-source alternative to Linktree,
  designed to provide an efficient solution for managing and sharing links
  online. It offers a highly customizable link sharing platform with an
  intuitive, user-friendly interface. Unlike other link management platforms,
  LinkStack allows users to host their links on their own web server or web
  hosting provider, giving them complete control over their online presence.
  This makes LinkStack an ideal solution for businesses and organizations
  looking to manage multiple links. With LinkStack, users can easily link to
  their own custom page and provide their followers with access to all the links
  they need in one convenient location. LinkStack also offers a self-hosted
  option for users who want complete control over their data without having it
  sold to third-party companies. The platform can be easily implemented through
  a simple drag and drop process, eliminating the need for complex terminal
  commands or source code manipulation. LinkStack is committed to providing a
  free, privacy-focused solution for managing and sharing links online, without
  sacrificing user privacy and control over their data.
instructions: Use the SQLite DB type in the installation wizard
changeLog:
  - date: 2023-5-22
    description: first release
links:
  - label: Github
    url: https://github.com/linkstackorg/linkstack
  - label: Website
    url: https://linkstack.org
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - serverAdmin
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: linkstack
    appServiceImage:
      type: string
      title: App Service Image
      default: linkstackorg/linkstack:V4
    serverAdmin:
      type: string
      title: Server Admin
      default: changeme@easypanel.io
