name: Typebot
description: Typebot is an innovative app designed to revolutionize the way you
  collect information. It allows you to build advanced chatbots visually, using
  powerful blocks to create unique chat experiences. You can embed these
  chatbots anywhere on your web or mobile apps and start collecting results
  instantly. Typebot is designed to replace your old school forms with chatbots,
  leading to an increase in customer satisfaction, retention, and a threefold
  increase in your conversion rate compared to traditional forms. With Typebot,
  you can easily drag and drop blocks to create your app, and even add custom
  code for your specific needs. It also offers native integration blocks and
  instructions on how to embed the chatbot on various platforms. One of the main
  advantages of Typebot is its real-time data collection feature, ensuring that
  you won't lose any valuable data. It also offers many more powerful features
  such as hidden fields, team collaboration, linking to sub chatbots, custom
  code, custom domains, and folder management. Typebot is loved by teams and
  creators from all around the world for its intelligent features and
  drag-and-drop simplicity.
instructions: Open the builder URL to access typebot.
changeLog:
  - date: 2023-02-27
    description: first release
  - date: 2023-03-13
    description: Update to v2.11.4
  - date: 2023-03-22
    description: Update to v2.11.6
links:
  - label: Website
    url: https://typebot.io
  - label: Documentation
    url: https://docs.typebot.io/
  - label: Github
    url: https://github.com/baptisteArno/typebot.io/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - builderServiceName
    - viewerServiceName
    - builderDomain
    - viewerDomain
    - builderServiceImage
    - viewerServiceImage
    - storageServiceImage
    - databaseServiceName
    - storageServiceName
    - githubClientId
    - githubClientSecret
    - adminEmail
  properties:
    projectName:
      type: string
      title: Project Name
    viewerServiceName:
      type: string
      title: Viewer Service Name
      default: typebot-viewer
    builderServiceName:
      type: string
      title: Builder Service Name
      default: typebot-builder
    builderDomain:
      type: string
      title: Builder Domain
    viewerDomain:
      type: string
      title: Viewer Domain
    builderServiceImage:
      type: string
      title: Builder Service Image
      default: baptistearno/typebot-builder:2.11.6
    viewerServiceImage:
      type: string
      title: Viewer Service Image
      default: baptistearno/typebot-viewer:2.11.6
    storageServiceImage:
      type: string
      title: Storage Service Image
      default: bitnami/minio:2022.12.12
    databaseServiceName:
      type: string
      title: Database Service Name
      default: typebot-db
    storageServiceName:
      type: string
      title: Storage Service Name
      default: typebot-minio
    githubClientId:
      type: string
      title: Github Client ID
    githubClientSecret:
      type: string
      title: Github Client Secret
    adminEmail:
      type: string
      title: Email to make administrator
