name: Syncthing
description: Syncthing is a powerful, real-time file synchronization program
  designed to keep your data secure and under your control. It enables the
  synchronization of files between two or more computers, ensuring your data is
  always up-to-date across your devices. Syncthing prioritizes your privacy and
  security, with no data ever stored on a central server that could be
  compromised. All communication is encrypted and authenticated, with only
  devices you have explicitly allowed able to connect to your other devices. The
  app is easy to use, with a responsive and powerful interface accessible via
  your browser. It works across various operating systems including Mac OS X,
  Windows, Linux, FreeBSD, Solaris, OpenBSD, and many others. Syncthing doesn't
  require complex configuration or IP addresses, it simply works, over LAN and
  over the Internet. You can synchronize as many folders as you need with
  different people or just between your own devices.
instructions: null
changeLog:
  - date: 2023-07-10
    description: First Release
links:
  - label: Website
    url: https://syncthing.net
  - label: Docs
    url: https://docs.syncthing.net
  - label: GitHub
    url: https://github.com/syncthing/syncthing
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: syncthing
    appServiceImage:
      type: string
      title: App Service Image
      default: syncthing/syncthing:1
