name: Dashdot
description: Dash. (or dashdot) is a visually stunning, modern server dashboard
  designed with a glassmorphism aesthetic. It's built on the latest technology
  and is intended for use with smaller VPS and private servers. The dashboard is
  feature-rich, offering a dark/light mode, customizable widgets, beautiful
  animations and styles, and support for multiple architectures. It provides a
  high level of personalization options, allowing you to tailor the dashboard to
  your specific needs. Dash. is an open-source project, welcoming contributions
  from those interested in further developing the platform.
instructions: null
changeLog:
  - date: 2023-3-29
    description: first release
links:
  - label: Website
    url: https://getdashdot.com/
  - label: Github
    url: https://github.com/MauriceNino/dashdot
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: dashdot
    appServiceImage:
      type: string
      title: App Service Image
      default: mauricenino/dashdot:5.1.1
