name: Miniflux
description: Miniflux is a minimalist and opinionated feed reader designed to
  prioritize content and readability. It optimizes the page layout, fonts, and
  colors to ensure that they are screen-friendly. If you have feeds that display
  only a summary, Miniflux fetches the original article automatically. The app
  is designed with simplicity in mind, focusing on essential features and
  avoiding bloated software. It is fast and efficient, allowing you to navigate
  through the application using keyboard shortcuts and quickly scan your unread
  items with a lightweight user interface. Miniflux also respects your privacy,
  ensuring that no one resells your private data or tracks your usage. It
  automatically removes pixel trackers and does not feature any advertising or
  user tracking. Miniflux is a free, open-source project distributed under the
  permissive Apache 2.0 License.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://miniflux.app/
  - label: Documentation
    url: https://miniflux.app/docs/
  - label: Github
    url: https://github.com/miniflux
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - adminUsername
    - adminPassword
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    adminUsername:
      type: string
      title: Admin Username
    adminPassword:
      type: string
      title: Admin Password
    appServiceName:
      type: string
      title: App Service Name
      default: miniflux
    appServiceImage:
      type: string
      title: App Service Image
      default: miniflux/miniflux:2.0.38
    databaseServiceName:
      type: string
      title: Database Service Name
      default: miniflux-db
