name: Flowise
description: Flowise is an open-source UI visual tool that allows you to build
  your own customized LLM (Language Learning Model) flow with ease. It is built
  on top of LangChainJS and is written in Node Typescript/Javascript. With
  Flowise, you can see your LLM apps running live, making the process of
  building and testing faster and more efficient. The app is extensible,
  allowing for custom component integrations. It offers a variety of features
  such as QnA retrieval chain, language translation chain, and a conversational
  agent with memory for chat models. Flowise is designed to make the process of
  visualizing and building LLM apps simple and accessible.
instructions: null
changeLog:
  - date: 2023-06-22
    description: first release
links:
  - label: Website
    url: https://flowiseai.com
  - label: Documentation
    url: https://docs.flowiseai.com
  - label: Github
    url: https://github.com/FlowiseAI/Flowise
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - username
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: flowise
    appServiceImage:
      type: string
      title: App Service Image
      default: flowiseai/flowise
    username:
      type: string
      title: Username
    password:
      type: string
      title: Password
