name: Kavita
description: Kavita is a high-speed, sleekly designed, self-hosted digital
  library that supports a wide range of file formats. It allows you to quickly
  resume your reading from your homepage, browse your Manga, Comics, and Books,
  and search for your favorite manga with ease. Kavita also provides full
  support for all fields from ComicInfo.xml (and EPUB) for metadata filtering.
  It features built-in ratings and reviews for each Manga, integrated chapters
  and volumes, and user & library management. Kavita also includes a responsive
  Manga/Comic/Image Reader with impressive caching for a seamless reading
  experience, and a customizable Book reader. It also provides server and user
  stats, and premium features with a Kavita+ Subscription. Kavita supports a
  wide array of file formats for Manga/Comics, Books, and Raw Images. It also
  offers user management and sharing features, allowing you to create users and
  share your libraries with them. Kavita is fast, efficient, and responsive,
  offering full text search, grouping and organizing features, full metadata
  support and filtering ability, and cool stats for individual user accounts and
  your server.
instructions: null
changeLog:
  - date: 2022-12-21
    description: first release
links:
  - label: Website
    url: https://www.kavitareader.com/
  - label: Documentation
    url: https://wiki.kavitareader.com/
  - label: Github
    url: https://github.com/Kareadita/Kavita
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: kavita
    appServiceImage:
      type: string
      title: App Service Image
      default: kizaing/kavita:0.7.1
    serviceTimezone:
      type: string
      title: Timezone
      default: America/New_York
