name: Dashy
description: Dashy is the ultimate homepage for your homelab, designed to be
  your personal, privacy-respecting dashboard. It is highly customizable and
  easy to use, offering a unique user experience with its built-in themes and UI
  color palette editor. Dashy can auto-fetch icons from the favicon of each of
  your apps or services, and it provides an instant overview of the health of
  each of your apps with status indicators. It also features a simple
  authentication feature for protecting your dashboard, and supports multiple
  users with granular controls. Dashy comes with 50+ pre-built widgets for
  displaying dynamic content from any API-enabled service. It offers alternate
  views for a minimal view or a workspace view, and allows you to choose how to
  launch your apps. Dashy also includes a search and shortcuts feature for easy
  navigation, and an optional cloud backup and sync service for off-site config
  backup. The app supports multiple languages and is easily configurable through
  a simple YAML file or directly through the UI.
instructions: After deploying the project, it may take a while before the app is
  available (5 minutes).
changeLog:
  - date: 2022-08-18
    description: first release
links:
  - label: Website
    url: https://dashy.to/
  - label: Documentation
    url: https://dashy.to/docs/
  - label: Github
    url: https://github.com/lissy93/dashy
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: dashy
    appServiceImage:
      type: string
      title: App Service Image
      default: lissy93/dashy:2.1.1
