name: Fider
description: Fider is a feature-rich solution designed to help you understand
  and prioritize your customers' needs. It allows your customers to share their
  ideas, vote, and discuss what they need the most. With Fider, you can keep
  everyone informed about the status of their suggestions, whether they are
  started, completed, or declined. The app offers a one-click sign-in feature,
  making it easy for visitors to contribute. You can customize Fider to match
  your brand's identity, and even control access to your site by making it
  private. The app also supports multiple languages, making it accessible to a
  global audience. Fider allows you to tag your content for easy organization
  and uses the popular Markdown language for text styling. It also provides a
  public API for integration into your process and can integrate with any system
  that supports Webhook. With Fider, you can collect valuable feedback, respond
  to suggestions, and keep your audience in the loop, all in one place.
instructions: Fider REQUIRES email in order for installation to work!
changeLog:
  - date: 2022-11-19
    description: first release
links:
  - label: Website
    url: https://fider.io
  - label: Documentation
    url: https://fider.io/docs
  - label: Github
    url: https://github.com/getfider/fider
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - emailNoReply
    - emailHost
    - emailPort
    - emailUsername
    - emailPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: fider
    appServiceImage:
      type: string
      title: App Service Image
      default: getfider/fider:stable
    databaseServiceName:
      type: string
      title: Database Service Name
      default: fider-db
    emailNoReply:
      type: string
      title: No Reply Email
    emailHost:
      type: string
      title: Email Host
    emailPort:
      type: number
      title: Email Port
      default: 587
    emailUsername:
      type: string
      title: Email Username
    emailPassword:
      type: string
      title: Email Password
