name: Limesurvey
description: "Welcome to LimeSurvey, the world's #1 survey platform designed to
  provide you with the best online survey tool that's fresh, quick, and
  anonymous. Whether you're a student, professional, or enterprise, LimeSurvey
  allows you to design a survey and gather insightful data, all for free. With
  LimeSurvey, you can create a simple questionnaire or poll, or even a
  sophisticated survey with complex validation rules, conditional logic, and
  quota management. It's the perfect alternative to Google Forms or Doodle.
  LimeSurvey is also the optimal online survey tool for research institutes,
  universities, and other educational establishments, offering free surveys,
  polls, and other open-source possibilities. With easy-to-use templates and an
  on-hand customer service team, LimeSurvey is your go-to solution for all your
  survey needs."
instructions: null
changeLog:
  - date: 2023-01-24
    description: first release
links:
  - label: Website
    url: https://limesurvey.org/
  - label: Documentation
    url: https://manual.limesurvey.org
  - label: Github
    url: https://github.com/LimeSurvey/LimeSurvey
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - limesurveyUsername
    - limesurveyPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: limesurvey
    appServiceImage:
      type: string
      title: App Service Image
      default: tiredofit/limesurvey:1.5.10
    databaseServiceName:
      type: string
      title: Database Service Name
      default: limesurvey-db
    limesurveyUsername:
      type: string
      title: Username
    limesurveyPassword:
      type: string
      title: Password
