name: Botpress
description: Botpress is a revolutionary platform that allows you to build
  next-generation chatbots powered by OpenAI. It offers an intuitive visual flow
  editor to bring your users’ conversations to life. With Botpress, you can
  create chatbots that are always on brand, thanks to ChatGPT’s copywriting
  abilities. The platform also provides a range of GPT-first tools and features
  such as dynamic knowledge ingestion, sentiment analysis, automatic
  self-improvement, data enhancements, and AI recommendations. Botpress supports
  100+ languages, enabling you to launch your chatbot globally. It also offers
  one-click deployment across various channels. With Botpress, building
  human-like chatbots has never been this easy.
instructions: Botpress needs at least 10 GB of RAM to run!
changeLog:
  - date: 2023-5-18
    description: first release
links:
  - label: Website
    url: https://botpress.com
  - label: Documentation
    url: https://botpress.com/docs
  - label: Github
    url: https://github.com/botpress/botpress
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: botpress
    appServiceImage:
      type: string
      title: App Service Image
      default: botpress/server:12.30.8
    databaseServiceName:
      type: string
      title: Database Service Name
      default: botpress-db
