name: EspoCRM
description: EspoCRM is a powerful web application designed to streamline your
  company's relationships. This versatile tool allows you to manage and evaluate
  all types of relationships, including people, companies, projects, and
  opportunities, all within an easy-to-use and intuitive interface. EspoCRM is
  trusted by over 50,000 companies across 163 countries, and has been enhancing
  business operations for 9 years. It is widely used across various sectors such
  as wholesale and retail trade, e-commerce, banking, call-centers,
  manufacturing, education, travel & tourism, real estate, healthcare, and
  insurance. EspoCRM is designed to skyrocket your sales, transform your
  marketing strategy, and deliver an exceptional customer experience. It is a
  free self-hosted and cloud CRM software that can be used simultaneously by
  many people. Increase your company’s profitability and build customer loyalty
  with EspoCRM, your open source sales tool.
instructions: null
changeLog:
  - date: 2023-07-03
    description: First Release
links:
  - label: Website
    url: https://espocrm.com
  - label: Demo
    url: https://demo.espocrm.com
  - label: Documentation
    url: https://docs.espocrm.com
  - label: Github
    url: https://github.com/espocrm
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - adminUsername
    - adminPassword
    - appServiceName
    - appServiceImage
    - databaseServiceType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    adminUsername:
      type: string
      title: Admin Username
    adminPassword:
      type: string
      title: Admin Password
    appServiceName:
      type: string
      title: App Service Name
      default: espocrm
    appServiceImage:
      type: string
      title: App Service Image
      default: espocrm/espocrm:7-apache
    databaseServiceType:
      type: string
      title: Database Service Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: espocrm-db
