name: Visual Studio Code Server
description: The LinuxServer.io team presents the docker-code-server, a powerful
  tool that allows you to run VS Code on a remote server, accessible through
  your browser. This means you can code on your Chromebook, tablet, and laptop
  with a consistent development environment. If you're using a Windows or Mac
  workstation, you can more easily develop for Linux. The app also allows you to
  leverage large cloud servers to speed up tests, compilations, downloads, and
  more. It helps preserve battery life when you're on the go, as all intensive
  computation runs on your server, eliminating the need for running excess
  instances of Chrome.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Documentation
    url: https://github.com/linuxserver/docker-code-server/blob/master/README.md
  - label: Github
    url: https://github.com/linuxserver/docker-code-server
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - password
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    password:
      type: string
      title: VS Code Server Password
    appServiceName:
      type: string
      title: App Service Name
      default: vsc-server
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/code-server:4.9.1-ls148
