name: Drone Runner
description: Drone.io is a self-service Continuous Integration platform designed
  for busy development teams. It automates software build and testing, making it
  easier for teams to manage their development process. The platform allows for
  configuration as a code, with pipelines configured through a simple,
  easy-to-read file committed to your git repository. Each pipeline step is
  executed inside an isolated Docker container that is automatically downloaded
  at runtime. Drone.io integrates seamlessly with multiple source code
  management systems, including GitHub, GitHubEnterprise, Bitbucket, and GitLab.
  It supports multiple operating systems and architectures, and works with any
  language, database, or service that runs inside a Docker container. The
  platform also allows for advanced customization, including custom access
  controls, approval workflows, secret management, and yaml syntax extensions.
  Drone.io ensures that every build runs in an isolated Docker container,
  providing full control and preventing conflicting builds on shared servers.
instructions: null
changeLog:
  - date: 2022-08-04
    description: first release
links:
  - label: Website
    url: https://drone.io/
  - label: Documentation
    url: https://github.com/harness/drone#setup-documentation
  - label: Github
    url: https://github.com/harness/drone
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - host
    - secret
    - runners
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: drone-runner
    appServiceImage:
      type: string
      title: App Service Image
      default: drone/drone-runner-docker:1.8.2
    host:
      type: string
      title: Drone Server Hostname
      default: drone.company.com
    secret:
      type: string
      title: RPC Secret
      default: Secret
    rpcProtocol:
      type: string
      title: RPC Protocol
      default: https
      oneOf:
        - enum:
            - https
          title: https
        - enum:
            - http
          title: http
    runners:
      type: string
      title: Runner Capacity
      default: "2"
