name: Nango
description: Nango is a powerful app designed to simplify and accelerate the
  process of building integrations. It provides a unified API, allowing you to
  drastically simplify your integration code and avoid dealing with each
  external API's schema and quirks. With Nango, you can authorize any
  integration using our drop-in UI, and securely manage your users' credentials.
  The app also enables continuous data synchronization with external APIs, using
  one of 100+ pre-built integrations, or you can customize them or build your
  own. Nango also supports 2-way syncs, write-backs, and real-time webhooks.
  It's designed for engineering teams that want full control without the hassle,
  allowing you to build exactly the integration your customers need, in code.
  With Nango, you can leave the maintenance, scaling, and API specific quirks to
  us, and focus on what you do best.
instructions: Check the environment tab for your API key. Follow the
  instructions in the FILE mount.
changeLog:
  - date: 2023-3-13
    description: first release
links:
  - label: Website
    url: https://nango.dev
  - label: Documentation
    url: https://docs.nango.dev
  - label: Github
    url: https://github.com/NangoHQ/nango
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - webUsername
    - webPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nango
    appServiceImage:
      type: string
      title: App Service Image
      default: nango.docker.scarf.sh/nangohq/nango-server:0.10.3
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nango-db
    webUsername:
      type: string
      title: Username
    webPassword:
      type: string
      title: Password
