name: Filebrowser
description: File Browser is a versatile app designed to provide a file managing
  interface within a specified directory. It's a powerful tool that allows you
  to upload, delete, preview, rename, and edit your files with ease. The app
  supports the creation of multiple users, with each user having their own
  directory, making it an ideal solution for managing files in a multi-user
  environment. File Browser also offers a range of customization options,
  including the ability to change the way users authenticate with the server,
  execute shell commands before or after certain events, and personalize the
  installation with custom branding. It can be used as a standalone app,
  offering a comprehensive and user-friendly solution for all your file
  management needs.
instructions: 'Default credentials: User:"admin" Password:"admin"'
changeLog:
  - date: 2022-08-09
    description: first release
  - date: 2023-2-24
    description: Update to v2.23.0
links:
  - label: Website
    url: https://filebrowser.org/
  - label: Github
    url: https://github.com/filebrowser/filebrowser
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: filebrowser
    appServiceImage:
      type: string
      title: App Service Image
      default: filebrowser/filebrowser:v2-s6
