name: Rocket.Chat
description: Rocket.Chat SIX is a secure and scalable collaboration platform
  designed to enhance team productivity and customer service experiences. It
  allows you to own your data and offers extensive customization and integration
  options. The platform brings together messages, projects, and tasks into one
  place, enabling teams to work more efficiently. It also provides an
  omnichannel customer service experience, allowing businesses to engage in
  contextual interactions with customers, fostering long-term relationships and
  improved business outcomes. Additionally, Rocket.Chat SIX features a chat
  engine to drive higher user engagement within your app or website. The
  platform is built for teams that need more control, offering end-to-end
  encryption, compliance with various data protection regulations, and a wide
  range of deployment options to meet your security needs.
instructions: null
changeLog:
  - date: 2022-08-10
    description: first release
  - date: 2023-3-20
    description: Update to v5.4.5
links:
  - label: Website
    url: https://rocket.chat/
  - label: Documentation
    url: https://docs.rocket.chat/
  - label: Github
    url: https://github.com/RocketChat/Rocket.Chat
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rocketchat
    appServiceImage:
      type: string
      title: App Service Image
      default: rocketchat/rocket.chat:5.4.5
    databaseServiceName:
      type: string
      title: Database Service Name
      default: rocketchat-db
