name: Easyshortener
description: Easyshortener is a multi-user link shortening application designed
  for simplicity and security. It allows multiple users to manage their links
  from a built-in administration panel. The app is built with a focus on user
  experience, ensuring it is easy to use. It also features built-in two-factor
  authentication, providing an extra layer of security for your peace of mind.
  Easyshortener is built for Docker, making it easy to deploy with your favorite
  container engine. Additionally, the app allows for registration and redirect
  tracking for all links, and can be set to force HTTPS connection for enhanced
  security.
instructions: null
changeLog:
  - date: 2023-3-23
    description: first release
links:
  - label: Github
    url: https://github.com/easypanel-community/easyshortener
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: easyshortener
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/easypanel-community/easyshortener:1.1.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: easyshortener-db
